In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [5]:
df = Unifier.get_dataframe(name="kalshi_macro_series_daily", asof_date='2026-10-23', limit=10)
display(df)

,series_ticker,title,category,categories,tags,frequency,fee_type,fee_multiplier,settlement_sources,additional_prohibitions,contract_url,contract_terms_url,volume,last_updated_ts,exchange_index,asof_datetime,asof_date
0,ACPI,US annual inflation,Economics,[Economics],[Inflation],annual,quadratic,1,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/ACPI.pdf,0.00,2026-10-15 08:14:10.230,0,2026-10-22 02:10:12.997,2026-10-22
1,CPI,CPI,Economics,[Economics],[Inflation],monthly,quadratic,1,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/CPI.pdf,0.00,2026-10-15 08:14:10.230,0,2026-10-22 02:10:12.997,2026-10-22
2,CPICOREYOY,Core inflation,Economics,[Economics],[Inflation],monthly,quadratic,1,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/YOYCP...,0.00,2026-10-15 08:14:10.230,0,2026-10-22 02:10:12.997,2026-10-22
3,CPIYOY,Inflation,Economics,[Economics],[Inflation],monthly,quadratic,1,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/YOYCP...,0.00,2026-10-15 08:14:10.230,0,2026-10-22 02:10:12.997,2026-10-22
4,FED,Fed funds rate,Economics,[Economics],[Interest rates],custom,quadratic,1,"[{""name"":""Federal Reserve Board of Governors"",...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/FED.pdf,0.00,2026-10-15 08:14:10.230,0,2026-10-22 02:10:12.997,2026-10-22
5,FEDDECISION,Fed meeting,Economics,[Economics],[Interest rates],custom,quadratic,1,"[{""name"":""Federal Reserve"",""url"":""https://www....",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/FEDDE...,0.00,2026-10-15 08:14:10.230,0,2026-10-22 02:10:12.997,2026-10-22
6,KXACPI,US annual inflation,Economics,[Economics],[Inflation],annual,quadratic,1,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/ACPI.pdf,2028523.00,2026-10-15 08:14:10.230,0,2026-10-22 02:10:12.997,2026-10-22
7,KXCPI,CPI,Economics,[Economics],[Inflation],monthly,quadratic_with_maker_fees,1,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/CPI.pdf,26396536.00,2026-10-15 07:57:20.405,0,2026-10-22 02:10:12.997,2026-10-22
8,KXCPICOREYOY,Core inflation,Economics,[Economics],[Inflation],monthly,quadratic,1,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/YOYCP...,4064485.00,2026-10-15 08:14:10.230,0,2026-10-22 02:10:12.997,2026-10-22
9,KXCPIYOY,Inflation,Economics,[Economics],[Inflation],monthly,quadratic_with_maker_fees,1,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/YOYCP...,38333204.00,2026-10-15 08:14:10.230,0,2026-10-22 02:10:12.997,2026-10-22

## Retrieve data for a specific date range using the back_to and up_to parameters

In [6]:
df = Unifier.get_dataframe(name='kalshi_macro_series_daily', back_to='2026-10-19', up_to='2026-10-23', limit=10)
display(df)

,series_ticker,title,category,categories,tags,frequency,fee_type,fee_multiplier,settlement_sources,additional_prohibitions,contract_url,contract_terms_url,volume,last_updated_ts,exchange_index,asof_datetime,asof_date
0,ACPI,US annual inflation,Economics,[Economics],[Inflation],annual,quadratic,1,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/ACPI.pdf,0.00,2026-10-15 08:14:10.230,0,2026-10-22 02:10:12.997,2026-10-22
1,CPI,CPI,Economics,[Economics],[Inflation],monthly,quadratic,1,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/CPI.pdf,0.00,2026-10-15 08:14:10.230,0,2026-10-22 02:10:12.997,2026-10-22
2,CPICOREYOY,Core inflation,Economics,[Economics],[Inflation],monthly,quadratic,1,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/YOYCP...,0.00,2026-10-15 08:14:10.230,0,2026-10-22 02:10:12.997,2026-10-22
3,CPIYOY,Inflation,Economics,[Economics],[Inflation],monthly,quadratic,1,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/YOYCP...,0.00,2026-10-15 08:14:10.230,0,2026-10-22 02:10:12.997,2026-10-22
4,FED,Fed funds rate,Economics,[Economics],[Interest rates],custom,quadratic,1,"[{""name"":""Federal Reserve Board of Governors"",...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/FED.pdf,0.00,2026-10-15 08:14:10.230,0,2026-10-22 02:10:12.997,2026-10-22
5,FEDDECISION,Fed meeting,Economics,[Economics],[Interest rates],custom,quadratic,1,"[{""name"":""Federal Reserve"",""url"":""https://www....",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/FEDDE...,0.00,2026-10-15 08:14:10.230,0,2026-10-22 02:10:12.997,2026-10-22
6,KXACPI,US annual inflation,Economics,[Economics],[Inflation],annual,quadratic,1,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/ACPI.pdf,2028523.00,2026-10-15 08:14:10.230,0,2026-10-22 02:10:12.997,2026-10-22
7,KXCPI,CPI,Economics,[Economics],[Inflation],monthly,quadratic_with_maker_fees,1,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/CPI.pdf,26396536.00,2026-10-15 07:57:20.405,0,2026-10-22 02:10:12.997,2026-10-22
8,KXCPICOREYOY,Core inflation,Economics,[Economics],[Inflation],monthly,quadratic,1,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/YOYCP...,4064485.00,2026-10-15 08:14:10.230,0,2026-10-22 02:10:12.997,2026-10-22
9,KXCPIYOY,Inflation,Economics,[Economics],[Inflation],monthly,quadratic_with_maker_fees,1,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/YOYCP...,38333204.00,2026-10-15 08:14:10.230,0,2026-10-22 02:10:12.997,2026-10-22

## Retrieve data for a specific date with a specific series_ticker (key='series_ticker') using the asof_date parameter

In [7]:
df = Unifier.get_dataframe(name='kalshi_macro_series_daily',key='KXCPIYOY', asof_date='2026-10-23', limit=10)
display(df)

,series_ticker,title,category,categories,tags,frequency,fee_type,fee_multiplier,settlement_sources,additional_prohibitions,contract_url,contract_terms_url,volume,last_updated_ts,exchange_index,asof_datetime,asof_date
0,KXCPIYOY,Inflation,Economics,[Economics],[Inflation],monthly,quadratic_with_maker_fees,1,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/YOYCP...,38333204.00,2026-10-15 08:14:10.230,0,2026-10-22 02:10:12.997,2026-10-22

## Retrieve data for a specific date range with a specific series_ticker (key='series_ticker') using the back_to and up_to parameters

In [8]:
df = Unifier.get_dataframe(name='kalshi_macro_series_daily',key='KXCPIYOY', back_to='2026-10-19', up_to='2026-10-23', limit=10)
display(df)

,series_ticker,title,category,categories,tags,frequency,fee_type,fee_multiplier,settlement_sources,additional_prohibitions,contract_url,contract_terms_url,volume,last_updated_ts,exchange_index,asof_datetime,asof_date
0,KXCPIYOY,Inflation,Economics,[Economics],[Inflation],monthly,quadratic_with_maker_fees,1,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/YOYCP...,38333204.00,2026-10-15 08:14:10.230,0,2026-10-22 02:10:12.997,2026-10-22

## Download data file for a specific date using asof_date

In [9]:
Unifier.replicate(name="kalshi_macro_series_daily", target_location="./data", asof_date='2026-10-22')

Downloading using native python implementation for kalshi_macro_series_daily...
Found 1 files to download.
Native replication completed for kalshi_macro_series_daily. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_macro_series_daily", target_location="./data")