In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="kalshi_macro_orderbook_snapshots", asof_date='2026-10-22', limit=10)
display(df)

,ticker,event_ticker,series_ticker,yes_bid,yes_bid_size,yes_ask,yes_ask_size,no_bid,no_bid_size,no_ask,...,spread,yes_levels,no_levels,yes_depth,no_depth,yes_depth_notional,no_depth_notional,is_empty,asof_datetime,asof_date
0,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,0.9100,540.00,0.9200,1173.82,0.0800,1173.82,0.0900,...,0.0100,11,3,7745.08,2515.09,665.7339,110.5790,False,2026-10-22 13:14:57.527,2026-10-22
1,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,0.9100,50.00,0.9200,1994.00,0.0800,1994.00,0.0900,...,0.0100,13,3,2043.08,3333.27,415.8857,175.7934,False,2026-10-22 20:05:01.431,2026-10-22
2,KXCPI-26DEC-T0.0,KXCPI-26DEC,KXCPI,0.9100,541.06,0.9300,1687.00,0.0700,1687.00,0.0900,...,0.0200,14,7,14104.44,5453.14,1177.1596,218.7932,False,2026-10-22 13:14:57.527,2026-10-22
3,KXCPI-26DEC-T0.0,KXCPI-26DEC,KXCPI,0.9100,1.06,0.9200,14.00,0.0800,14.00,0.0900,...,0.0100,16,8,11993.12,5619.46,973.2928,296.4213,False,2026-10-22 20:05:01.431,2026-10-22
4,KXCPI-26DEC-T0.1,KXCPI-26DEC,KXCPI,0.8600,391.00,0.8900,687.00,0.1100,687.00,0.1400,...,0.0300,11,8,12654.76,4392.00,1026.0976,223.1600,False,2026-10-22 13:14:57.527,2026-10-22
5,KXCPI-26DEC-T0.1,KXCPI-26DEC,KXCPI,0.7800,100.00,0.8100,1578.94,0.1900,1578.94,0.2200,...,0.0300,16,10,15307.04,7278.94,1129.6924,788.8886,False,2026-10-22 20:05:01.431,2026-10-22
6,KXCPI-26DEC-T0.2,KXCPI-26DEC,KXCPI,0.4400,2.00,0.6300,44.00,0.3700,44.00,0.5600,...,0.1900,8,11,1451.00,4315.00,161.2800,368.4200,False,2026-10-22 13:14:57.527,2026-10-22
7,KXCPI-26DEC-T0.2,KXCPI-26DEC,KXCPI,0.4300,607.00,0.6200,44.00,0.3800,44.00,0.5700,...,0.1900,8,11,1765.00,4393.00,281.8500,394.8200,False,2026-10-22 20:05:01.431,2026-10-22
8,KXCPI-26DEC-T0.3,KXCPI-26DEC,KXCPI,0.1300,43.45,0.4000,44.00,0.6000,44.00,0.8700,...,0.2700,5,7,2783.45,1602.00,52.8385,53.2800,False,2026-10-22 13:14:57.527,2026-10-22
9,KXCPI-26DEC-T0.3,KXCPI-26DEC,KXCPI,0.2300,14.00,0.4100,44.00,0.5900,44.00,0.7700,...,0.1800,8,8,2019.00,2141.00,191.1300,151.4400,False,2026-10-22 20:05:01.431,2026-10-22

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='kalshi_macro_orderbook_snapshots', back_to='2026-10-22', up_to='2026-10-23', limit=10)
display(df)

,ticker,event_ticker,series_ticker,yes_bid,yes_bid_size,yes_ask,yes_ask_size,no_bid,no_bid_size,no_ask,...,spread,yes_levels,no_levels,yes_depth,no_depth,yes_depth_notional,no_depth_notional,is_empty,asof_datetime,asof_date
0,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,0.9100,540.00,0.9200,1173.82,0.0800,1173.82,0.0900,...,0.0100,11,3,7745.08,2515.09,665.7339,110.5790,False,2026-10-22 13:14:57.527,2026-10-22
1,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,0.9100,50.00,0.9200,1994.00,0.0800,1994.00,0.0900,...,0.0100,13,3,2043.08,3333.27,415.8857,175.7934,False,2026-10-22 20:05:01.431,2026-10-22
2,KXCPI-26DEC-T0.0,KXCPI-26DEC,KXCPI,0.9100,541.06,0.9300,1687.00,0.0700,1687.00,0.0900,...,0.0200,14,7,14104.44,5453.14,1177.1596,218.7932,False,2026-10-22 13:14:57.527,2026-10-22
3,KXCPI-26DEC-T0.0,KXCPI-26DEC,KXCPI,0.9100,1.06,0.9200,14.00,0.0800,14.00,0.0900,...,0.0100,16,8,11993.12,5619.46,973.2928,296.4213,False,2026-10-22 20:05:01.431,2026-10-22
4,KXCPI-26DEC-T0.1,KXCPI-26DEC,KXCPI,0.8600,391.00,0.8900,687.00,0.1100,687.00,0.1400,...,0.0300,11,8,12654.76,4392.00,1026.0976,223.1600,False,2026-10-22 13:14:57.527,2026-10-22
5,KXCPI-26DEC-T0.1,KXCPI-26DEC,KXCPI,0.7800,100.00,0.8100,1578.94,0.1900,1578.94,0.2200,...,0.0300,16,10,15307.04,7278.94,1129.6924,788.8886,False,2026-10-22 20:05:01.431,2026-10-22
6,KXCPI-26DEC-T0.2,KXCPI-26DEC,KXCPI,0.4400,2.00,0.6300,44.00,0.3700,44.00,0.5600,...,0.1900,8,11,1451.00,4315.00,161.2800,368.4200,False,2026-10-22 13:14:57.527,2026-10-22
7,KXCPI-26DEC-T0.2,KXCPI-26DEC,KXCPI,0.4300,607.00,0.6200,44.00,0.3800,44.00,0.5700,...,0.1900,8,11,1765.00,4393.00,281.8500,394.8200,False,2026-10-22 20:05:01.431,2026-10-22
8,KXCPI-26DEC-T0.3,KXCPI-26DEC,KXCPI,0.1300,43.45,0.4000,44.00,0.6000,44.00,0.8700,...,0.2700,5,7,2783.45,1602.00,52.8385,53.2800,False,2026-10-22 13:14:57.527,2026-10-22
9,KXCPI-26DEC-T0.3,KXCPI-26DEC,KXCPI,0.2300,14.00,0.4100,44.00,0.5900,44.00,0.7700,...,0.1800,8,8,2019.00,2141.00,191.1300,151.4400,False,2026-10-22 20:05:01.431,2026-10-22

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='kalshi_macro_orderbook_snapshots',key='KXFED-26DEC-T4.50', asof_date='2026-10-22', limit=10)
display(df)

,ticker,event_ticker,series_ticker,yes_bid,yes_bid_size,yes_ask,yes_ask_size,no_bid,no_bid_size,no_ask,...,spread,yes_levels,no_levels,yes_depth,no_depth,yes_depth_notional,no_depth_notional,is_empty,asof_datetime,asof_date
0,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,0.0500,14.46,0.0600,25.00,0.9400,25.00,0.9500,...,0.0100,5,27,106369.88,1071743.91,1568.6349,70101.5157,False,2026-10-22 13:14:57.527,2026-10-22
1,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,0.0400,5845.59,0.0500,5010.54,0.9500,5010.54,0.9600,...,0.0100,4,30,106355.42,1077647.45,1563.6127,76034.1687,False,2026-10-22 20:05:01.431,2026-10-22

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='kalshi_macro_orderbook_snapshots',key='KXFED-26DEC-T4.50', back_to='2026-10-22', up_to='2026-10-23', limit=10)
display(df)

,ticker,event_ticker,series_ticker,yes_bid,yes_bid_size,yes_ask,yes_ask_size,no_bid,no_bid_size,no_ask,...,spread,yes_levels,no_levels,yes_depth,no_depth,yes_depth_notional,no_depth_notional,is_empty,asof_datetime,asof_date
0,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,0.0500,14.46,0.0600,25.00,0.9400,25.00,0.9500,...,0.0100,5,27,106369.88,1071743.91,1568.6349,70101.5157,False,2026-10-22 13:14:57.527,2026-10-22
1,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,0.0400,5845.59,0.0500,5010.54,0.9500,5010.54,0.9600,...,0.0100,4,30,106355.42,1077647.45,1563.6127,76034.1687,False,2026-10-22 20:05:01.431,2026-10-22

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="kalshi_macro_orderbook_snapshots", target_location="./data", asof_date='2026-10-22')

Downloading using native python implementation for kalshi_macro_orderbook_snapshots...
Found 2 files to download.
Native replication completed for kalshi_macro_orderbook_snapshots. Downloaded 2 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_macro_orderbook_snapshots", target_location="./data")