In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [10]:
df = Unifier.get_dataframe(name="kalshi_macro_events_daily", asof_date='2026-10-23', limit=10)
display(df)

,event_ticker,series_ticker,title,sub_title,category,mutually_exclusive,collateral_return_type,strike_date,strike_period,settlement_sources,fee_type_override,fee_multiplier_override,last_updated_ts,exchange_index,asof_datetime,asof_date
0,KXCPI-26DEC,KXCPI,CPI in December,In Dec 2026,Economics,False,DIRECNET,NaN,NaN,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",None,None,2026-10-16 21:21:25.296,0,2026-10-22 02:10:15.098,2026-10-22
1,KXCPI-26NOV,KXCPI,CPI in November,In Nov 2026,Economics,False,DIRECNET,NaN,NaN,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",None,None,2026-10-16 21:20:56.351,0,2026-10-22 02:10:15.098,2026-10-22
2,KXCPI-26OCT,KXCPI,CPI in October,In Oct 2026,Economics,False,DIRECNET,NaN,NaN,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",None,None,2026-10-16 21:19:23.327,0,2026-10-22 02:10:15.098,2026-10-22
3,KXCPICOREYOY-26DEC,KXCPICOREYOY,Core CPI YoY in December,Dec 2026,Economics,False,DIRECNET,NaN,December 2026,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",None,None,2026-10-17 18:06:56.041,0,2026-10-22 02:10:15.098,2026-10-22
4,KXCPICOREYOY-26NOV,KXCPICOREYOY,Core CPI YoY in November,Nov 2026,Economics,False,DIRECNET,NaN,November 2026,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",None,None,2026-10-17 18:05:22.803,0,2026-10-22 02:10:15.098,2026-10-22
5,KXCPIYOY-26DEC,KXCPIYOY,CPI YoY in December,In Dec 2026,Economics,False,DIRECNET,NaN,NaN,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",None,None,2026-10-17 18:12:10.116,0,2026-10-22 02:10:15.098,2026-10-22
6,KXCPIYOY-26NOV,KXCPIYOY,CPI YoY in November,In Nov 2026,Economics,False,DIRECNET,NaN,NaN,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",None,None,2026-10-17 18:12:10.127,0,2026-10-22 02:10:15.098,2026-10-22
7,KXFED-26DEC,KXFED,Fed funds rate after Dec 2026 meeting?,"On Dec 9, 2026",Economics,False,DIRECNET,2026-12-09 19:00:00.000,NaN,"[{""name"":""Federal Reserve Board of Governors"",...",None,None,2026-10-15 13:58:06.438,0,2026-10-22 02:10:15.098,2026-10-22
8,KXFED-26OCT,KXFED,Fed funds rate after Oct 2026 meeting?,"On Oct 28, 2026",Economics,False,DIRECNET,2026-10-28 18:00:00.000,NaN,"[{""name"":""Federal Reserve Board of Governors"",...",None,None,2026-10-15 13:58:06.438,0,2026-10-22 02:10:15.098,2026-10-22
9,KXFED-27APR,KXFED,Fed funds rate after Apr 2027 meeting?,"On Apr 28, 2027",Economics,False,DIRECNET,2027-04-28 18:00:00.000,NaN,"[{""name"":""Federal Reserve Board of Governors"",...",None,None,2026-10-15 20:47:47.242,0,2026-10-22 02:10:15.098,2026-10-22

## Retrieve data for a specific date range using the back_to and up_to parameters

In [9]:
df = Unifier.get_dataframe(name='kalshi_macro_events_daily', back_to='2026-10-19', up_to='2026-10-23', limit=100)
display(df)

,event_ticker,series_ticker,title,sub_title,category,mutually_exclusive,collateral_return_type,strike_date,strike_period,settlement_sources,fee_type_override,fee_multiplier_override,last_updated_ts,exchange_index,asof_datetime,asof_date
0,KXCPI-26DEC,KXCPI,CPI in December,In Dec 2026,Economics,False,DIRECNET,NaN,NaN,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",None,None,2026-10-16 21:21:25.296,0,2026-10-22 02:10:15.098,2026-10-22
1,KXCPI-26NOV,KXCPI,CPI in November,In Nov 2026,Economics,False,DIRECNET,NaN,NaN,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",None,None,2026-10-16 21:20:56.351,0,2026-10-22 02:10:15.098,2026-10-22
2,KXCPI-26OCT,KXCPI,CPI in October,In Oct 2026,Economics,False,DIRECNET,NaN,NaN,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",None,None,2026-10-16 21:19:23.327,0,2026-10-22 02:10:15.098,2026-10-22
3,KXCPICOREYOY-26DEC,KXCPICOREYOY,Core CPI YoY in December,Dec 2026,Economics,False,DIRECNET,NaN,December 2026,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",None,None,2026-10-17 18:06:56.041,0,2026-10-22 02:10:15.098,2026-10-22
4,KXCPICOREYOY-26NOV,KXCPICOREYOY,Core CPI YoY in November,Nov 2026,Economics,False,DIRECNET,NaN,November 2026,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",None,None,2026-10-17 18:05:22.803,0,2026-10-22 02:10:15.098,2026-10-22
5,KXCPIYOY-26DEC,KXCPIYOY,CPI YoY in December,In Dec 2026,Economics,False,DIRECNET,NaN,NaN,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",None,None,2026-10-17 18:12:10.116,0,2026-10-22 02:10:15.098,2026-10-22
6,KXCPIYOY-26NOV,KXCPIYOY,CPI YoY in November,In Nov 2026,Economics,False,DIRECNET,NaN,NaN,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",None,None,2026-10-17 18:12:10.127,0,2026-10-22 02:10:15.098,2026-10-22
7,KXFED-26DEC,KXFED,Fed funds rate after Dec 2026 meeting?,"On Dec 9, 2026",Economics,False,DIRECNET,2026-12-09 19:00:00.000,NaN,"[{""name"":""Federal Reserve Board of Governors"",...",None,None,2026-10-15 13:58:06.438,0,2026-10-22 02:10:15.098,2026-10-22
8,KXFED-26OCT,KXFED,Fed funds rate after Oct 2026 meeting?,"On Oct 28, 2026",Economics,False,DIRECNET,2026-10-28 18:00:00.000,NaN,"[{""name"":""Federal Reserve Board of Governors"",...",None,None,2026-10-15 13:58:06.438,0,2026-10-22 02:10:15.098,2026-10-22
9,KXFED-27APR,KXFED,Fed funds rate after Apr 2027 meeting?,"On Apr 28, 2027",Economics,False,DIRECNET,2027-04-28 18:00:00.000,NaN,"[{""name"":""Federal Reserve Board of Governors"",...",None,None,2026-10-15 20:47:47.242,0,2026-10-22 02:10:15.098,2026-10-22
10,KXFED-27DEC,KXFED,Fed funds rate after Dec 2027 meeting?,"On Dec 8, 2027",Economics,False,DIRECNET,2027-12-08 19:00:00.000,NaN,"[{""name"":""Federal Reserve Board of Governors"",...",None,None,2026-10-15 21:19:19.286,0,2026-10-22 02:10:15.098,2026-10-22
11,KXFED-27JAN,KXFED,Fed funds rate after Jan 2027 meeting?,"On Jan 27, 2027",Economics,False,DIRECNET,2027-01-27 19:00:00.000,NaN,"[{""name"":""Federal Reserve Board of Governors"",...",None,None,2026-10-15 20:47:47.242,0,2026-10-22 02:10:15.098,2026-10-22
12,KXFED-27JUL,KXFED,Fed funds rate after Jul 2027 meeting?,"On Jul 28, 2027",Economics,False,DIRECNET,2027-07-28 18:00:00.000,NaN,"[{""name"":""Federal Reserve Board of Governors"",...",None,None,2026-10-15 21:19:19.407,0,2026-10-22 02:10:15.098,2026-10-22
13,KXFED-27JUN,KXFED,Fed funds rate after Jun 2027 meeting?,"On Jun 9, 2027",Economics,False,DIRECNET,2027-06-09 18:00:00.000,NaN,"[{""name"":""Federal Reserve Board of Governors"",...",None,None,2026-10-15 21:19:19.474,0,2026-10-22 02:10:15.098,2026-10-22
14,KXFED-27MAR,KXFED,Fed funds rate after Mar 2027 meeting?,"On Mar 17, 2027",Economics,False,DIRECNET,2027-03-17 18:00:00.000,NaN,"[{""name"":""Federal Reserve Board of Governors"",...",None,None,2026-10-15 20:47:47.242,0,2026-10-22 02:10:15.098,2026-10-22
15,KXFED-27OCT,KXFED,Fed funds rate after Oct 2027 meeting?,"On Oct 27, 2027",Economics,False,DIRECNET,2027-10-27 18:00:00.000,NaN,"[{""name"":""Federal Reserve Board of Governors"",...",None,None,2026-10-15 21:19:19.362,0,2026-10-22 02:10:15.098,2026-10-22
16,KXFED-27SEP,KXFED,Fed funds rate after Sep 2027 meeting?,"On Sep 15, 2027",Economics,False,DIRECNET,2027-09-15 18:00:00.000,NaN,"[{""name"":""Federal Reserve Board of Governors"",...",None,None,2026-10-15 21:19:19.382,0,2026-10-22 02:10:15.098,2026-10-22
17,KXFED-28JAN,KXFED,Fed funds rate after Jan 2028 meeting?,"On Jan 26, 2028",Economics,False,DIRECNET,2028-01-26 19:00:00.000,NaN,"[{""name"":""Federal Reserve Board of Governors"",...",None,None,2026-10-15 21:16:33.287,0,2026-10-22 02:10:15.098,2026-10-22
18,KXFEDDECISION-26DEC,KXFEDDECISION,Fed decision in Dec 2026?,"On Dec 9, 2026",Economics,True,MECNET,2026-12-09 19:00:00.000,NaN,"[{""name"":""Federal Reserve"",""url"":""https://www....",None,None,2026-10-16 14:30:21.263,0,2026-10-22 02:10:15.098,2026-10-22
19,KXFEDDECISION-26OCT,KXFEDDECISION,Fed decision in Oct 2026?,"On Oct 28, 2026",Economics,True,MECNET,2026-10-28 18:00:00.000,NaN,"[{""name"":""Federal Reserve"",""url"":""https://www....",None,None,2026-10-16 14:34:59.038,0,2026-10-22 02:10:15.098,2026-10-22
20,KXFEDDECISION-27APR,KXFEDDECISION,Fed decision in Apr 2027?,"On Apr 28, 2027",Economics,True,MECNET,2027-04-28 18:00:00.000,NaN,"[{""name"":""Federal Reserve"",""url"":""https://www....",None,None,2026-10-16 14:20:32.175,0,2026-10-22 02:10:15.098,2026-10-22
21,KXFEDDECISION-27DEC,KXFEDDECISION,Fed decision in Dec 2027?,"On Dec 8, 2027",Economics,True,MECNET,2027-12-08 19:00:00.000,NaN,"[{""name"":""Federal Reserve"",""url"":""https://www....",None,None,2026-10-16 14:17:36.460,0,2026-10-22 02:10:15.098,2026-10-22
22,KXFEDDECISION-27JAN,KXFEDDECISION,Fed decision in Jan 2027?,"On Jan 27, 2027",Economics,True,MECNET,2027-01-27 19:00:00.000,NaN,"[{""name"":""Federal Reserve"",""url"":""https://www....",None,None,2026-10-16 14:23:42.702,0,2026-10-22 02:10:15.098,2026-10-22
23,KXFEDDECISION-27JUL,KXFEDDECISION,Fed decision in Jul 2027?,"On Jul 28, 2027",Economics,True,MECNET,2027-07-28 18:00:00.000,NaN,"[{""name"":""Federal Reserve"",""url"":""https://www....",None,None,2026-10-16 14:20:32.175,0,2026-10-22 02:10:15.098,2026-10-22
24,KXFEDDECISION-27JUN,KXFEDDECISION,Fed decision in Jun 2027?,"On Jun 9, 2027",Economics,True,MECNET,2027-06-09 18:00:00.000,NaN,"[{""name"":""Federal Reserve"",""url"":""https://www....",None,None,2026-10-16 14:20:32.175,0,2026-10-22 02:10:15.098,2026-10-22
25,KXFEDDECISION-27MAR,KXFEDDECISION,Fed decision in Mar 2027?,"On Mar 17, 2027",Economics,True,MECNET,2027-03-17 18:00:00.000,NaN,"[{""name"":""Federal Reserve"",""url"":""https://www....",None,None,2026-10-16 14:22:00.356,0,2026-10-22 02:10:15.098,2026-10-22
26,KXFEDDECISION-27OCT,KXFEDDECISION,Fed decision in Oct 2027?,"On Oct 27, 2027",Economics,True,MECNET,2027-10-27 18:00:00.000,NaN,"[{""name"":""Federal Reserve"",""url"":""https://www....",None,None,2026-10-16 14:19:02.479,0,2026-10-22 02:10:15.098,2026-10-22
27,KXFEDDECISION-27SEP,KXFEDDECISION,Fed decision in Sep 2027?,"On Sep 15, 2027",Economics,True,MECNET,2027-09-15 18:00:00.000,NaN,"[{""name"":""Federal Reserve"",""url"":""https://www....",None,None,2026-10-16 14:19:02.479,0,2026-10-22 02:10:15.098,2026-10-22
28,KXFEDDECISION-28JAN,KXFEDDECISION,Fed decision in Jan 2028?,"On Jan 26, 2028",Economics,True,MECNET,2028-01-26 19:00:00.000,NaN,"[{""name"":""Federal Reserve"",""url"":""https://www....",None,None,2026-10-16 03:27:45.997,0,2026-10-22 02:10:15.098,2026-10-22
29,KXGDPYEAR-26,KXGDPYEAR,US real GDP growth in 2026?,2026,Economics,True,MECNET,NaN,NaN,"[{""name"":""Bureau of Economic Analysis"",""url"":""...",None,None,2026-08-27 19:17:51.008,0,2026-10-22 02:10:15.098,2026-10-22
30,KXGDPYEAR-27,KXGDPYEAR,US real GDP growth in 2027?,2027,Economics,True,MECNET,NaN,NaN,"[{""name"":""Bureau of Economic Analysis"",""url"":""...",None,None,2026-08-27 19:17:51.008,0,2026-10-22 02:10:15.098,2026-10-22
31,KXGDPYEAR-28,KXGDPYEAR,US real GDP growth in 2028?,2028,Economics,True,MECNET,NaN,NaN,"[{""name"":""Bureau of Economic Analysis"",""url"":""...",None,None,2026-08-27 19:17:51.008,0,2026-10-22 02:10:15.098,2026-10-22
32,KXGDPYEAR-29,KXGDPYEAR,US real GDP growth in 2029?,2029,Economics,True,MECNET,NaN,NaN,"[{""name"":""Bureau of Economic Analysis"",""url"":""...",None,None,2026-08-27 19:17:51.008,0,2026-10-22 02:10:15.098,2026-10-22
33,KXGDPYEAR-30,KXGDPYEAR,US real GDP growth in 2030?,2030,Economics,True,MECNET,NaN,NaN,"[{""name"":""Bureau of Economic Analysis"",""url"":""...",None,None,2026-08-27 19:17:51.008,0,2026-10-22 02:10:15.098,2026-10-22
34,KXGDPYEAR-31,KXGDPYEAR,US real GDP growth in 2031?,2031,Economics,True,MECNET,NaN,NaN,"[{""name"":""Bureau of Economic Analysis"",""url"":""...",None,None,2026-08-27 19:17:51.008,0,2026-10-22 02:10:15.098,2026-10-22
35,KXGDPYEAR-32,KXGDPYEAR,US real GDP growth in 2032?,2032,Economics,True,MECNET,NaN,NaN,"[{""name"":""Bureau of Economic Analysis"",""url"":""...",None,None,2026-08-27 19:17:51.008,0,2026-10-22 02:10:15.098,2026-10-22
36,KXGDPYEAR-33,KXGDPYEAR,US real GDP growth in 2033?,2033,Economics,True,MECNET,NaN,NaN,"[{""name"":""Bureau of Economic Analysis"",""url"":""...",None,None,2026-08-27 19:17:51.008,0,2026-10-22 02:10:15.098,2026-10-22
37,KXGDPYEAR-34,KXGDPYEAR,US real GDP growth in 2034?,2034,Economics,True,MECNET,NaN,NaN,"[{""name"":""Bureau of Economic Analysis"",""url"":""...",None,None,2026-08-27 19:17:51.008,0,2026-10-22 02:10:15.098,2026-10-22
38,KXGDPYEAR-35,KXGDPYEAR,US real GDP growth in 2035?,2035,Economics,True,MECNET,NaN,NaN,"[{""name"":""Bureau of Economic Analysis"",""url"":""...",None,None,2026-08-27 19:17:51.008,0,2026-10-22 02:10:15.098,2026-10-22
39,KXGDPYEAR-36,KXGDPYEAR,US real GDP growth in 2036?,2036,Economics,True,MECNET,NaN,NaN,"[{""name"":""Bureau of Economic Analysis"",""url"":""...",None,None,2026-08-27 19:17:51.008,0,2026-10-22 02:10:15.098,2026-10-22
40,KXPAYROLLS-26NOV,KXPAYROLLS,Jobs numbers in Nov 2026?,In Nov 2026,Economics,False,DIRECNET,NaN,November 2026,"[{""name"":""BLS"",""url"":""https://www.bls.gov/news...",None,None,2026-10-16 02:57:33.406,0,2026-10-22 02:10:15.098,2026-10-22
41,KXPAYROLLS-26OCT,KXPAYROLLS,Jobs numbers in October 2026?,In Oct 2026,Economics,False,DIRECNET,NaN,October 2026,"[{""name"":""BLS"",""url"":""https://www.bls.gov/news...",None,None,2026-10-16 02:57:33.406,0,2026-10-22 02:10:15.098,2026-10-22
42,KXU3-26NOV,KXU3,Unemployment in November,In Nov 2026,Economics,False,DIRECNET,NaN,NaN,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",None,None,2026-10-16 03:07:51.321,0,2026-10-22 02:10:15.098,2026-10-22
43,KXU3-26OCT,KXU3,Unemployment in October,In Oct 2026,Economics,False,DIRECNET,NaN,NaN,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",None,None,2026-10-16 03:09:26.214,0,2026-10-22 02:10:15.098,2026-10-22

## Retrieve data for a specific date with a specific event_ticker (key='event_ticker') using the asof_date parameter

In [11]:
df = Unifier.get_dataframe(name='kalshi_macro_events_daily',key='KXCPIYOY-26NOV', asof_date='2026-10-22', limit=10)
display(df)

,event_ticker,series_ticker,title,sub_title,category,mutually_exclusive,collateral_return_type,strike_date,strike_period,settlement_sources,fee_type_override,fee_multiplier_override,last_updated_ts,exchange_index,asof_datetime,asof_date
0,KXCPIYOY-26NOV,KXCPIYOY,CPI YoY in November,In Nov 2026,Economics,False,DIRECNET,None,None,"[{""name"":""Bureau of Labor Statistics"",""url"":""h...",None,None,2026-10-17 18:12:10.127,0,2026-10-22 02:10:15.098,2026-10-22

## Retrieve data for a specific date range with a specific event_ticker (key='event_ticker') using the back_to and up_to parameters

In [12]:
df = Unifier.get_dataframe(name='kalshi_macro_events_daily',key='KXCPIYOY-26NOV', back_to='2026-10-19', up_to='2026-10-22', limit=10)
display(df)

Empty DataFrame
Columns: []
Index: []

## Download data file for a specific date using asof_date

In [13]:
Unifier.replicate(name="kalshi_macro_events_daily", target_location="./data", asof_date='2026-10-22')

Downloading using native python implementation for kalshi_macro_events_daily...
Found 1 files to download.
Native replication completed for kalshi_macro_events_daily. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_macro_events_daily", target_location="./data")