In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="kalshi_macro_daily_bid_ask_moments", asof_date='2026-10-21', limit=10)
display(df)

,dataset,series_ticker,contract_preamble,expiry_date,method,n_bins,daily_volume,mean,median,mode,skewness,kurtosis,variance,asof_datetime,asof_date
0,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26SEP,2026-10-14,threshold,16,27274.83,2.444898,2.400,2.500,0.564103,0.074951,0.008800,2026-10-21 14:08:20.788,2026-10-10
1,fed_levels,KXFED,KXFED-26DEC,2026-12-09,threshold,12,7092.92,4.135204,4.125,4.125,0.114286,2.478844,0.026682,2026-10-21 14:08:20.788,2026-10-10
2,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,4235.95,3.917092,3.875,3.875,1.064516,0.951439,0.007476,2026-10-21 14:08:20.788,2026-10-10
3,fed_levels,KXFED,KXFED-27JAN,2027-01-27,threshold,26,1.00,4.734694,4.375,5.625,0.568548,-0.427589,0.586182,2026-10-21 14:08:20.788,2026-10-10
4,fed_levels,KXFED,KXFED-27MAR,2027-03-17,threshold,26,0.00,4.059949,3.625,3.625,0.749451,-0.654037,0.444429,2026-10-21 14:08:20.788,2026-10-10
5,headline_cpi_releases,KXCPIYOY,KXCPIYOY-26SEP,2026-10-14,threshold,22,52086.49,3.636735,3.600,3.600,0.493151,2.666916,0.010691,2026-10-21 14:08:20.788,2026-10-10
6,headline_cpi_releases_mom,KXCPI,KXCPI-26SEP,2026-10-14,threshold,15,197368.99,0.566837,0.600,0.600,-0.481481,0.123016,0.007523,2026-10-21 14:08:20.788,2026-10-10
7,unemployment_releases,KXU3,KXU3-26OCT,2026-11-06,threshold,15,3066.53,4.197449,4.200,4.200,-0.034483,3.349513,0.012289,2026-10-21 14:08:20.788,2026-10-10
8,fed_levels,KXFED,KXFED-26DEC,2026-12-09,threshold,12,2087.60,3.989796,3.875,3.875,0.608108,2.883465,0.059526,2026-10-21 14:05:38.819,2026-09-13
9,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,152.30,3.897959,3.875,3.875,0.281250,0.755690,0.017968,2026-10-21 14:05:38.819,2026-09-13

## Retrieve data for a specific date range using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='kalshi_macro_daily_bid_ask_moments', back_to='2026-09-01', up_to='2026-10-22', limit=10)
display(df)

,dataset,series_ticker,contract_preamble,expiry_date,method,n_bins,daily_volume,mean,median,mode,skewness,kurtosis,variance,asof_datetime,asof_date
0,fed_levels,KXFED,KXFED-26DEC,2026-12-09,threshold,12,2087.60,3.989796,3.875,3.875,0.608108,2.883465,0.059526,2026-10-21 14:05:38.819,2026-09-13
1,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,152.30,3.897959,3.875,3.875,0.281250,0.755690,0.017968,2026-10-21 14:05:38.819,2026-09-13
2,fed_levels,KXFED,KXFED-26SEP,2026-09-16,threshold,12,26520.82,3.827806,3.875,3.875,-1.057143,0.542682,0.007658,2026-10-21 14:05:38.819,2026-09-13
3,fed_levels,KXFED,KXFED-27JAN,2027-01-27,threshold,19,261.78,3.617347,3.625,3.625,-0.028037,8.530384,0.226982,2026-10-21 14:05:38.819,2026-09-13
4,unemployment_releases,KXU3,KXU3-26SEP,2026-10-02,threshold,15,1786.22,4.121429,4.100,4.200,0.179487,1.174448,0.025561,2026-10-21 14:05:38.819,2026-09-13
5,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26SEP,2026-10-14,threshold,16,27274.83,2.444898,2.400,2.500,0.564103,0.074951,0.008800,2026-10-21 14:08:20.788,2026-10-10
6,fed_levels,KXFED,KXFED-26DEC,2026-12-09,threshold,12,7092.92,4.135204,4.125,4.125,0.114286,2.478844,0.026682,2026-10-21 14:08:20.788,2026-10-10
7,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,4235.95,3.917092,3.875,3.875,1.064516,0.951439,0.007476,2026-10-21 14:08:20.788,2026-10-10
8,fed_levels,KXFED,KXFED-27JAN,2027-01-27,threshold,26,1.00,4.734694,4.375,5.625,0.568548,-0.427589,0.586182,2026-10-21 14:08:20.788,2026-10-10
9,fed_levels,KXFED,KXFED-27MAR,2027-03-17,threshold,26,0.00,4.059949,3.625,3.625,0.749451,-0.654037,0.444429,2026-10-21 14:08:20.788,2026-10-10

## Retrieve data for a specific date with a specific contract_preamble (key='contract_preamble') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='kalshi_macro_daily_bid_ask_moments',key='KXFED-26OCT', asof_date='2026-10-22', limit=10)
display(df)

,dataset,series_ticker,contract_preamble,expiry_date,method,n_bins,daily_volume,mean,median,mode,skewness,kurtosis,variance,asof_datetime,asof_date
0,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,16845.38,3.960459,3.875,3.875,1.030769,-1.113497,0.012148,2026-10-21 14:06:03.550,2026-10-01
1,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,1646.46,4.035714,4.125,4.125,-1.000000,0.358967,0.012436,2026-10-21 14:05:56.570,2026-09-26
2,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,26924.50,3.932398,3.875,3.875,1.046512,-0.444378,0.009779,2026-10-21 14:08:27.916,2026-10-15
3,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,3054.14,3.933673,3.875,3.875,0.547619,0.613817,0.021430,2026-10-21 14:05:42.843,2026-09-16
4,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,152.30,3.897959,3.875,3.875,0.281250,0.755690,0.017968,2026-10-21 14:05:38.819,2026-09-13
5,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,1906.57,3.924745,3.875,3.875,1.054054,1.244171,0.008048,2026-10-21 14:08:13.477,2026-10-05
6,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,6267.04,3.900510,3.875,3.875,1.111111,4.398535,0.004451,2026-10-21 14:08:33.729,2026-10-19
7,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,2725.90,3.913265,3.875,3.875,1.071429,3.155896,0.006189,2026-10-21 14:06:07.631,2026-10-04
8,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,66916.81,3.984694,3.875,3.875,1.023810,-1.409633,0.012840,2026-10-21 14:06:02.164,2026-09-30
9,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,2992.43,3.915816,3.875,3.875,1.066667,1.117260,0.007263,2026-10-21 14:08:29.380,2026-10-16

## Retrieve data for a specific date range with a specific contract_preamble (key='contract_preamble') using the back_to and up_to parameters

In [8]:
df = Unifier.get_dataframe(name='kalshi_macro_daily_bid_ask_moments',key='KXFED-26OCT', back_to='2026-09-01', up_to='2026-10-22', limit=10)
display(df)

,dataset,series_ticker,contract_preamble,expiry_date,method,n_bins,daily_volume,mean,median,mode,skewness,kurtosis,variance,asof_datetime,asof_date
0,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,16845.38,3.960459,3.875,3.875,1.030769,-1.113497,0.012148,2026-10-21 14:06:03.550,2026-10-01
1,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,1317.37,4.039541,4.125,4.125,-1.000000,0.445552,0.012148,2026-10-21 14:05:59.341,2026-09-28
2,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,10011.07,4.038265,4.125,4.125,-1.000000,-1.254970,0.012885,2026-10-21 14:05:53.761,2026-09-24
3,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,2096.49,3.781888,3.875,3.875,-0.768421,1.066659,0.024812,2026-10-21 14:05:26.441,2026-09-04
4,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,9335.12,4.053571,4.125,4.125,-1.000000,0.936320,0.010842,2026-10-21 14:06:00.734,2026-09-29
5,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,127.00,3.792092,3.875,3.875,-0.730337,1.327995,0.023420,2026-10-21 14:05:30.682,2026-09-07
6,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,319.47,3.926020,3.875,3.875,1.052632,1.090290,0.008239,2026-10-21 14:08:15.065,2026-10-06
7,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,26924.50,3.932398,3.875,3.875,1.046512,-0.444378,0.009779,2026-10-21 14:08:27.916,2026-10-15
8,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,625.11,3.918367,3.875,3.875,1.062500,0.795591,0.007686,2026-10-21 14:08:19.347,2026-10-09
9,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,17779.66,3.934949,3.875,3.875,1.044444,-0.603166,0.010118,2026-10-21 14:08:16.488,2026-10-07

## Download data file for a specific date using asof_date

In [9]:
Unifier.replicate(name="kalshi_macro_daily_bid_ask_moments", target_location="./data", asof_date='2026-10-21')

Downloading using native python implementation for kalshi_macro_daily_bid_ask_moments...
Found 1 files to download.
Native replication completed for kalshi_macro_daily_bid_ask_moments. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_macro_daily_bid_ask_moments", target_location="./data")