In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="kalshi_macro_candles_1d", asof_date='2026-10-21', limit=10)
display(df)

,ticker,period_minutes,timestamp,date,yes_bid_open,yes_bid_high,yes_bid_low,yes_bid_close,yes_ask_open,yes_ask_high,...,price_high,price_low,price_close,price_mean,price_previous,volume,open_interest,source_tier,asof_datetime,asof_date
0,KXCPI-26NOV-T-0.1,1440,2026-10-10 04:00:00.000,2026-10-10,0.8100,0.8500,0.8000,0.8100,0.9400,0.9400,...,0.9000,0.8100,0.8400,0.8615,0.8400,48.00,1085.21,live,2026-10-21 14:07:46.717,2026-10-10
1,KXCPI-26NOV-T0.0,1440,2026-10-10 04:00:00.000,2026-10-10,0.7400,0.7500,0.7200,0.7300,0.8000,0.8200,...,0.7800,0.7300,0.7300,0.7320,0.7400,164.00,1500.13,live,2026-10-21 14:07:46.717,2026-10-10
2,KXCPI-26NOV-T0.1,1440,2026-10-10 04:00:00.000,2026-10-10,0.6000,0.6400,0.5900,0.6100,0.6100,0.7900,...,0.7000,0.6000,0.6200,0.6381,0.6400,4.00,2430.28,live,2026-10-21 14:07:46.717,2026-10-10
3,KXCPI-26NOV-T0.2,1440,2026-10-10 04:00:00.000,2026-10-10,0.4300,0.4400,0.4100,0.4400,0.4700,0.4700,...,0.4500,0.4100,0.4500,0.4307,0.4100,57.00,4865.92,live,2026-10-21 14:07:46.717,2026-10-10
4,KXCPI-26NOV-T0.3,1440,2026-10-10 04:00:00.000,2026-10-10,0.1700,0.1800,0.1300,0.1600,0.2000,0.2200,...,0.2000,0.1700,0.2000,0.1750,0.3400,6.00,2636.88,live,2026-10-21 14:07:46.717,2026-10-10
5,KXCPI-26OCT-T-0.1,1440,2026-10-10 04:00:00.000,2026-10-10,0.9200,0.9400,0.9100,0.9400,0.9600,0.9600,...,0.9500,0.9100,0.9400,0.9179,0.9300,399.00,3606.09,live,2026-10-21 14:07:46.717,2026-10-10
6,KXCPI-26OCT-T0.0,1440,2026-10-10 04:00:00.000,2026-10-10,0.8500,0.8800,0.8100,0.8800,0.8800,0.9200,...,0.8900,0.8700,0.8800,0.8777,0.8700,74.00,13420.74,live,2026-10-21 14:07:46.717,2026-10-10
7,KXCPI-26OCT-T0.1,1440,2026-10-10 04:00:00.000,2026-10-10,0.7200,0.7600,0.7000,0.7500,0.7500,0.8800,...,0.7700,0.7500,0.7700,0.7659,0.7100,22.00,2013.68,live,2026-10-21 14:07:46.717,2026-10-10
8,KXCPI-26OCT-T0.2,1440,2026-10-10 04:00:00.000,2026-10-10,0.4600,0.4600,0.3000,0.4600,0.4900,0.4900,...,0.4900,0.4500,0.4900,0.4844,0.4900,42.94,2762.68,live,2026-10-21 14:07:46.717,2026-10-10
9,KXCPI-26OCT-T0.4,1440,2026-10-10 04:00:00.000,2026-10-10,0.1400,0.1600,0.1300,0.1400,0.1500,0.1700,...,0.1500,0.1400,0.1400,0.1408,0.1500,271.00,3586.03,live,2026-10-21 14:07:46.717,2026-10-10

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='kalshi_macro_candles_1d', back_to='2026-10-01', up_to='2026-10-21', limit=100)
display(df)

,ticker,period_minutes,timestamp,date,yes_bid_open,yes_bid_high,yes_bid_low,yes_bid_close,yes_ask_open,yes_ask_high,...,price_high,price_low,price_close,price_mean,price_previous,volume,open_interest,source_tier,asof_datetime,asof_date
0,KXCPI-26NOV-T-0.1,1440,2026-10-10 04:00:00.000,2026-10-10,0.8100,0.8500,0.8000,0.8100,0.9400,0.9400,...,0.9000,0.8100,0.8400,0.8615,0.8400,48.00,1085.21,live,2026-10-21 14:07:46.717,2026-10-10
1,KXCPI-26NOV-T0.0,1440,2026-10-10 04:00:00.000,2026-10-10,0.7400,0.7500,0.7200,0.7300,0.8000,0.8200,...,0.7800,0.7300,0.7300,0.7320,0.7400,164.00,1500.13,live,2026-10-21 14:07:46.717,2026-10-10
2,KXCPI-26NOV-T0.1,1440,2026-10-10 04:00:00.000,2026-10-10,0.6000,0.6400,0.5900,0.6100,0.6100,0.7900,...,0.7000,0.6000,0.6200,0.6381,0.6400,4.00,2430.28,live,2026-10-21 14:07:46.717,2026-10-10
3,KXCPI-26NOV-T0.2,1440,2026-10-10 04:00:00.000,2026-10-10,0.4300,0.4400,0.4100,0.4400,0.4700,0.4700,...,0.4500,0.4100,0.4500,0.4307,0.4100,57.00,4865.92,live,2026-10-21 14:07:46.717,2026-10-10
4,KXCPI-26NOV-T0.3,1440,2026-10-10 04:00:00.000,2026-10-10,0.1700,0.1800,0.1300,0.1600,0.2000,0.2200,...,0.2000,0.1700,0.2000,0.1750,0.3400,6.00,2636.88,live,2026-10-21 14:07:46.717,2026-10-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,KXCPI-26NOV-T0.2,1440,2026-10-05 04:00:00.000,2026-10-05,0.2700,0.4900,0.2100,0.3700,0.3800,0.5400,...,0.5000,0.3200,0.3200,0.3532,0.2600,78.00,4916.92,live,2026-10-21 14:07:31.346,2026-10-05
96,KXCPI-26NOV-T0.5,1440,2026-10-05 04:00:00.000,2026-10-05,0.0200,0.0200,0.0200,0.0200,0.0300,0.0300,...,0.0200,0.0200,0.0200,0.0200,0.0300,4.00,983.98,live,2026-10-21 14:07:31.346,2026-10-05
97,KXCPI-26OCT-T-0.1,1440,2026-10-05 04:00:00.000,2026-10-05,0.9200,0.9600,0.8700,0.8700,0.9500,0.9800,...,0.9800,0.9200,0.9500,0.9578,0.9500,387.00,3673.80,live,2026-10-21 14:07:31.346,2026-10-05
98,KXCPI-26OCT-T0.0,1440,2026-10-05 04:00:00.000,2026-10-05,0.9400,0.9400,0.9100,0.9100,0.9500,0.9500,...,0.9400,0.9200,0.9200,0.9239,0.9400,590.27,16117.73,live,2026-10-21 14:07:31.346,2026-10-05
99,KXCPI-26OCT-T0.1,1440,2026-10-05 04:00:00.000,2026-10-05,0.8800,0.9000,0.8500,0.8800,0.9400,0.9700,...,0.9500,0.8600,0.9500,0.9038,0.8800,121.00,2587.92,live,2026-10-21 14:07:31.346,2026-10-05

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='kalshi_macro_candles_1d',key='KXFED-26OCT-T4.00', asof_date='2026-10-21', limit=100)
display(df)

,ticker,period_minutes,timestamp,date,yes_bid_open,yes_bid_high,yes_bid_low,yes_bid_close,yes_ask_open,yes_ask_high,...,price_high,price_low,price_close,price_mean,price_previous,volume,open_interest,source_tier,asof_datetime,asof_date
0,KXFED-26OCT-T4.00,1440,2026-09-26 04:00:00.000,2026-09-26,0.6600,0.6700,0.6200,0.6300,0.6800,0.6800,...,0.6700,0.6200,0.6400,0.6505,0.6700,1520.68,33365.18,live,2026-10-21 14:05:00.537,2026-09-26
1,KXFED-26OCT-T4.00,1440,2026-09-25 04:00:00.000,2026-09-25,0.6400,0.6900,0.6200,0.6600,0.6500,0.7200,...,0.7000,0.6300,0.6700,0.6712,0.6400,2597.39,33326.22,live,2026-10-21 14:04:55.332,2026-09-25
2,KXFED-26OCT-T4.00,1440,2026-10-09 04:00:00.000,2026-10-09,0.1300,0.1800,0.1300,0.1700,0.1600,0.2400,...,0.1800,0.1500,0.1700,0.1641,0.1300,189.43,61269.00,live,2026-10-21 14:07:40.716,2026-10-09
3,KXFED-26OCT-T4.00,1440,2026-10-16 04:00:00.000,2026-10-16,0.2300,0.3400,0.1400,0.1500,0.2400,0.3600,...,0.3600,0.2200,0.2300,0.2814,0.2400,2034.15,74941.97,live,2026-10-21 14:08:01.480,2026-10-16
4,KXFED-26OCT-T4.00,1440,2026-10-14 04:00:00.000,2026-10-14,0.1800,0.2200,0.1600,0.2000,0.1900,0.2400,...,0.2400,0.1700,0.2100,0.2011,0.1900,715.63,70653.11,live,2026-10-21 14:07:54.476,2026-10-14
5,KXFED-26OCT-T4.00,1440,2026-09-19 04:00:00.000,2026-09-19,0.5000,0.6100,0.3400,0.5700,0.5100,0.6200,...,0.6100,0.3500,0.5800,0.4875,0.5100,14185.92,28399.87,live,2026-10-21 14:04:37.988,2026-09-19
6,KXFED-26OCT-T4.00,1440,2026-10-17 04:00:00.000,2026-10-17,0.1500,0.1600,0.1300,0.1400,0.1900,0.2000,...,0.2000,0.1300,0.1500,0.1504,0.2300,7747.85,72568.83,live,2026-10-21 14:08:01.800,2026-10-17
7,KXFED-26OCT-T4.00,1440,2026-09-15 04:00:00.000,2026-09-15,0.2500,0.3200,0.2500,0.3100,0.2800,0.3400,...,0.3200,0.2600,0.3100,0.3021,0.2800,680.53,12530.46,live,2026-10-21 14:04:26.198,2026-09-15
8,KXFED-26OCT-T4.00,1440,2026-10-05 04:00:00.000,2026-10-05,0.1400,0.2800,0.0600,0.2000,0.1800,0.3800,...,0.3700,0.1400,0.1900,0.2319,0.1900,994.75,76572.17,live,2026-10-21 14:07:31.346,2026-10-05
9,KXFED-26OCT-T4.00,1440,2026-09-23 04:00:00.000,2026-09-23,0.5200,0.5300,0.4500,0.5200,0.5300,0.5600,...,0.5400,0.4800,0.5400,0.5039,0.5200,2610.43,30275.29,live,2026-10-21 14:04:49.947,2026-09-23
10,KXFED-26OCT-T4.00,1440,2026-09-20 04:00:00.000,2026-09-20,0.5700,0.5900,0.5600,0.5600,0.5800,0.6000,...,0.6000,0.5700,0.5700,0.5882,0.5800,1106.23,28615.55,live,2026-10-21 14:04:44.234,2026-09-20
11,KXFED-26OCT-T4.00,1440,2026-10-06 04:00:00.000,2026-10-06,0.2000,0.2100,0.1500,0.2000,0.2100,0.2400,...,0.2400,0.1800,0.2000,0.2004,0.1900,194.13,76693.68,live,2026-10-21 14:07:31.815,2026-10-06
12,KXFED-26OCT-T4.00,1440,2026-10-19 04:00:00.000,2026-10-19,0.1200,0.1400,0.0900,0.1000,0.1500,0.1600,...,0.1600,0.0900,0.1200,0.1342,0.1400,185.11,71692.95,live,2026-10-21 14:08:11.680,2026-10-19
13,KXFED-26OCT-T4.00,1440,2026-09-08 04:00:00.000,2026-09-08,0.0600,0.0600,0.0400,0.0600,0.0900,0.0900,...,0.0900,0.0900,0.0900,0.0900,0.0800,22.00,9057.79,live,2026-10-21 14:04:03.733,2026-09-08
14,KXFED-26OCT-T4.00,1440,2026-10-08 04:00:00.000,2026-10-08,0.2200,0.2200,0.1300,0.1300,0.2700,0.3400,...,0.2700,0.1300,0.1300,0.1711,0.1900,17465.07,61218.34,live,2026-10-21 14:07:31.421,2026-10-08
15,KXFED-26OCT-T4.00,1440,2026-10-01 04:00:00.000,2026-10-01,0.4300,0.4500,0.2800,0.3300,0.4500,0.4700,...,0.4600,0.3000,0.3600,0.3403,0.4600,13861.25,81506.22,live,2026-10-21 14:05:15.384,2026-10-01
16,KXFED-26OCT-T4.00,1440,2026-10-10 04:00:00.000,2026-10-10,0.1700,0.1800,0.1700,0.1700,0.1900,0.2700,...,0.1900,0.1700,0.1800,0.1815,0.1700,237.24,61458.73,live,2026-10-21 14:07:46.717,2026-10-10
17,KXFED-26OCT-T4.00,1440,2026-09-22 04:00:00.000,2026-09-22,0.5400,0.5500,0.5000,0.5200,0.5600,0.5700,...,0.5600,0.5000,0.5200,0.5074,0.5400,902.68,27922.68,live,2026-10-21 14:04:45.990,2026-09-22
18,KXFED-26OCT-T4.00,1440,2026-09-27 04:00:00.000,2026-09-27,0.6300,0.6400,0.6200,0.6300,0.6400,0.6500,...,0.6500,0.6200,0.6300,0.6390,0.6400,265.25,33448.68,live,2026-10-21 14:05:01.078,2026-09-27
19,KXFED-26OCT-T4.00,1440,2026-10-02 04:00:00.000,2026-10-02,0.3300,0.3700,0.2400,0.2700,0.3600,0.4800,...,0.4400,0.2400,0.2700,0.2981,0.3600,9907.05,76290.63,live,2026-10-21 14:05:18.314,2026-10-02
20,KXFED-26OCT-T4.00,1440,2026-10-20 04:00:00.000,2026-10-20,0.1000,0.1500,0.0800,0.1500,0.1200,0.1700,...,0.1700,0.1000,0.1600,0.1380,0.1200,1182.14,71883.13,live,2026-10-22 02:33:07.037,2026-10-20
21,KXFED-26OCT-T4.00,1440,2026-10-04 04:00:00.000,2026-10-04,0.1900,0.2300,0.0700,0.1400,0.2100,0.2500,...,0.2500,0.0800,0.1900,0.1865,0.1900,814.88,76424.31,live,2026-10-21 14:05:24.363,2026-10-04
22,KXFED-26OCT-T4.00,1440,2026-10-15 04:00:00.000,2026-10-15,0.2000,0.5000,0.1600,0.2300,0.2200,0.5200,...,0.5200,0.1800,0.2400,0.4151,0.2100,15475.67,74501.95,live,2026-10-21 14:08:00.677,2026-10-15
23,KXFED-26OCT-T4.00,1440,2026-10-03 04:00:00.000,2026-10-03,0.2700,0.2800,0.0600,0.1900,0.2800,0.3100,...,0.2900,0.1300,0.1900,0.1742,0.2700,9083.53,76371.88,live,2026-10-21 14:05:22.239,2026-10-03
24,KXFED-26OCT-T4.00,1440,2026-09-18 04:00:00.000,2026-09-18,0.4600,0.5100,0.4600,0.5000,0.4700,0.5400,...,0.5400,0.4600,0.5100,0.4787,0.4600,1486.33,21738.60,live,2026-10-21 14:04:34.422,2026-09-18
25,KXFED-26OCT-T4.00,1440,2026-10-11 04:00:00.000,2026-10-11,0.1700,0.1700,0.1600,0.1600,0.1800,0.1800,...,0.1800,0.1600,0.1600,0.1723,0.1800,306.50,61552.22,live,2026-10-21 14:07:47.105,2026-10-11
26,KXFED-26OCT-T4.00,1440,2026-09-13 04:00:00.000,2026-09-13,0.1800,0.2100,0.1700,0.2100,0.2100,0.2300,...,0.2300,0.1900,0.2200,0.2049,0.2300,57.30,11048.09,live,2026-10-21 14:04:18.371,2026-09-13
27,KXFED-26OCT-T4.00,1440,2026-09-24 04:00:00.000,2026-09-24,0.5200,0.6800,0.5000,0.6400,0.5300,0.6900,...,0.6800,0.5200,0.6400,0.6188,0.5400,6913.64,33317.69,live,2026-10-21 14:04:58.670,2026-09-24
28,KXFED-26OCT-T4.00,1440,2026-10-12 04:00:00.000,2026-10-12,0.1600,0.1600,0.1600,0.1600,0.1700,0.1700,...,0.1700,0.1700,0.1700,0.1700,0.1600,147.90,61700.12,live,2026-10-21 14:07:41.562,2026-10-12
29,KXFED-26OCT-T4.00,1440,2026-10-18 04:00:00.000,2026-10-18,0.1400,0.1400,0.0200,0.1200,0.1500,0.1500,...,0.1500,0.0200,0.1400,0.0737,0.1500,4587.45,71598.00,live,2026-10-21 14:08:08.403,2026-10-18
30,KXFED-26OCT-T4.00,1440,2026-09-21 04:00:00.000,2026-09-21,0.5600,0.6200,0.5300,0.5400,0.5700,0.6800,...,0.6800,0.5400,0.5400,0.6596,0.5700,4626.24,28080.46,live,2026-10-21 14:04:44.312,2026-09-21
31,KXFED-26OCT-T4.00,1440,2026-09-17 04:00:00.000,2026-09-17,0.3300,0.4800,0.2600,0.4600,0.3400,0.5100,...,0.5000,0.2600,0.4600,0.4047,0.3200,11455.64,21450.71,live,2026-10-21 14:04:31.592,2026-09-17
32,KXFED-26OCT-T4.00,1440,2026-09-28 04:00:00.000,2026-09-28,0.6300,0.6500,0.6200,0.6400,0.6400,0.6600,...,0.6600,0.6200,0.6600,0.6552,0.6300,1010.50,33668.81,live,2026-10-21 14:05:06.575,2026-09-28
33,KXFED-26OCT-T4.00,1440,2026-10-07 04:00:00.000,2026-10-07,0.2000,0.2300,0.1400,0.2200,0.2200,0.3200,...,0.2900,0.1700,0.1900,0.1718,0.2000,17218.56,76997.46,live,2026-10-21 14:07:32.365,2026-10-07
34,KXFED-26OCT-T4.00,1440,2026-09-04 04:00:00.000,2026-09-04,0.0600,0.0600,0.0400,0.0500,0.0900,0.0900,...,NaN,NaN,NaN,NaN,0.0600,0.00,6972.01,live,2026-10-21 14:03:55.517,2026-09-04
35,KXFED-26OCT-T4.00,1440,2026-09-12 04:00:00.000,2026-09-12,0.0700,0.1900,0.0400,0.1800,0.1000,0.2300,...,0.2300,0.1000,0.2300,0.1173,0.1000,1682.60,11047.10,live,2026-10-21 14:04:14.984,2026-09-12
36,KXFED-26OCT-T4.00,1440,2026-09-07 04:00:00.000,2026-09-07,0.0400,0.0600,0.0300,0.0600,0.0900,0.0900,...,NaN,NaN,NaN,NaN,0.0800,0.00,9038.95,live,2026-10-21 14:03:55.209,2026-09-07
37,KXFED-26OCT-T4.00,1440,2026-09-10 04:00:00.000,2026-09-10,0.0700,0.0700,0.0400,0.0700,0.0900,0.0900,...,0.0900,0.0900,0.0900,0.0900,0.0900,17.44,9554.16,live,2026-10-21 14:04:08.270,2026-09-10
38,KXFED-26OCT-T4.00,1440,2026-09-05 04:00:00.000,2026-09-05,0.0500,0.0700,0.0200,0.0300,0.0900,0.0900,...,0.0600,0.0300,0.0300,0.0342,0.0600,128.00,7012.70,live,2026-10-21 14:03:50.808,2026-09-05
39,KXFED-26OCT-T4.00,1440,2026-09-30 04:00:00.000,2026-09-30,0.7000,0.7000,0.3900,0.4300,0.7100,0.7100,...,0.7100,0.4100,0.4600,0.6641,0.7100,60610.85,81318.25,live,2026-10-21 14:05:13.909,2026-09-30
40,KXFED-26OCT-T4.00,1440,2026-09-29 04:00:00.000,2026-09-29,0.6400,0.7000,0.6400,0.7000,0.6600,0.7100,...,0.7100,0.6500,0.7100,0.6641,0.6600,4520.76,33562.18,live,2026-10-21 14:05:13.359,2026-09-29
41,KXFED-26OCT-T4.00,1440,2026-02-09 05:00:00.000,2026-02-09,0.0200,0.0300,0.0200,0.0200,0.4800,0.4800,...,0.0200,0.0200,0.0200,0.0200,0.0300,1.00,132.00,live,2026-10-21 11:58:14.356,2026-02-09
42,KXFED-26OCT-T4.00,1440,2026-02-08 05:00:00.000,2026-02-08,0.0200,0.0200,0.0200,0.0200,0.4800,0.4800,...,NaN,NaN,NaN,NaN,0.0300,0.00,132.00,live,2026-10-21 11:58:13.283,2026-02-08
43,KXFED-26OCT-T4.00,1440,2026-10-13 04:00:00.000,2026-10-13,0.1600,0.1800,0.1500,0.1800,0.1700,0.2000,...,0.2000,0.1500,0.1900,0.1702,0.1700,10345.62,70693.21,live,2026-10-21 14:07:53.046,2026-10-13
44,KXFED-26OCT-T4.00,1440,2026-02-04 05:00:00.000,2026-02-04,0.0200,0.0300,0.0200,0.0300,0.0900,0.1700,...,NaN,NaN,NaN,NaN,0.0200,0.00,89.00,live,2026-10-21 11:56:54.907,2026-02-04
45,KXFED-26OCT-T4.00,1440,2026-01-11 05:00:00.000,2026-01-11,0.0200,0.0200,0.0200,0.0200,0.0900,0.0900,...,0.0200,0.0200,0.0200,0.0200,0.0900,10.00,89.00,live,2026-10-21 11:48:33.462,2026-01-11
46,KXFED-26OCT-T4.00,1440,2026-09-11 04:00:00.000,2026-09-11,0.0700,0.0700,0.0000,0.0700,0.0800,0.1100,...,0.1000,0.0700,0.1000,0.0958,0.0900,1156.02,10040.06,live,2026-10-21 14:04:10.936,2026-09-11
47,KXFED-26OCT-T4.00,1440,2026-09-14 04:00:00.000,2026-09-14,0.2100,0.2500,0.2100,0.2500,0.2200,0.3000,...,0.2800,0.2100,0.2800,0.2421,0.2200,968.27,11992.11,live,2026-10-21 14:04:22.746,2026-09-14
48,KXFED-26OCT-T4.00,1440,2026-09-16 04:00:00.000,2026-09-16,0.3100,0.3500,0.2700,0.3300,0.3200,0.3700,...,0.3400,0.3000,0.3200,0.3194,0.3100,1884.14,13073.78,live,2026-10-21 14:04:30.514,2026-09-16
49,KXFED-26OCT-T4.00,1440,2026-01-08 05:00:00.000,2026-01-08,0.0200,0.0200,0.0200,0.0200,0.0900,0.1700,...,0.0900,0.0900,0.0900,0.0900,0.0300,10.00,99.00,live,2026-10-21 11:47:56.448,2026-01-08
50,KXFED-26OCT-T4.00,1440,2025-10-27 04:00:00.000,2025-10-27,0.0400,0.0400,0.0300,0.0300,0.1300,0.1400,...,NaN,NaN,NaN,NaN,NaN,0.00,0.00,live,2026-10-21 11:29:32.791,2025-10-27
51,KXFED-26OCT-T4.00,1440,2026-09-09 04:00:00.000,2026-09-09,0.0600,0.0700,0.0600,0.0700,0.0800,0.0900,...,0.0900,0.0900,0.0900,0.0900,0.0900,478.93,9536.72,live,2026-10-21 14:04:06.468,2026-09-09
52,KXFED-26OCT-T4.00,1440,2026-10-21 04:00:00.000,2026-10-21,0.1500,0.1500,0.1100,0.1200,0.1600,0.1600,...,0.1600,0.1200,0.1300,0.1356,0.1600,307.45,71906.43,live,2026-10-22 02:33:04.883,2026-10-21

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='kalshi_macro_candles_1d',key='KXFED-26OCT-T4.00', back_to='2026-10-01', up_to='2026-10-21', limit=10)
display(df)

,ticker,period_minutes,timestamp,date,yes_bid_open,yes_bid_high,yes_bid_low,yes_bid_close,yes_ask_open,yes_ask_high,...,price_high,price_low,price_close,price_mean,price_previous,volume,open_interest,source_tier,asof_datetime,asof_date
0,KXFED-26OCT-T4.00,1440,2026-10-18 04:00:00.000,2026-10-18,0.1400,0.1400,0.0200,0.1200,0.1500,0.1500,...,0.1500,0.0200,0.1400,0.0737,0.1500,4587.45,71598.00,live,2026-10-21 14:08:08.403,2026-10-18
1,KXFED-26OCT-T4.00,1440,2026-10-16 04:00:00.000,2026-10-16,0.2300,0.3400,0.1400,0.1500,0.2400,0.3600,...,0.3600,0.2200,0.2300,0.2814,0.2400,2034.15,74941.97,live,2026-10-21 14:08:01.480,2026-10-16
2,KXFED-26OCT-T4.00,1440,2026-10-17 04:00:00.000,2026-10-17,0.1500,0.1600,0.1300,0.1400,0.1900,0.2000,...,0.2000,0.1300,0.1500,0.1504,0.2300,7747.85,72568.83,live,2026-10-21 14:08:01.800,2026-10-17
3,KXFED-26OCT-T4.00,1440,2026-10-13 04:00:00.000,2026-10-13,0.1600,0.1800,0.1500,0.1800,0.1700,0.2000,...,0.2000,0.1500,0.1900,0.1702,0.1700,10345.62,70693.21,live,2026-10-21 14:07:53.046,2026-10-13
4,KXFED-26OCT-T4.00,1440,2026-10-20 04:00:00.000,2026-10-20,0.1000,0.1500,0.0800,0.1500,0.1200,0.1700,...,0.1700,0.1000,0.1600,0.1380,0.1200,1182.14,71883.13,live,2026-10-22 02:33:07.037,2026-10-20
5,KXFED-26OCT-T4.00,1440,2026-10-15 04:00:00.000,2026-10-15,0.2000,0.5000,0.1600,0.2300,0.2200,0.5200,...,0.5200,0.1800,0.2400,0.4151,0.2100,15475.67,74501.95,live,2026-10-21 14:08:00.677,2026-10-15
6,KXFED-26OCT-T4.00,1440,2026-10-10 04:00:00.000,2026-10-10,0.1700,0.1800,0.1700,0.1700,0.1900,0.2700,...,0.1900,0.1700,0.1800,0.1815,0.1700,237.24,61458.73,live,2026-10-21 14:07:46.717,2026-10-10
7,KXFED-26OCT-T4.00,1440,2026-10-03 04:00:00.000,2026-10-03,0.2700,0.2800,0.0600,0.1900,0.2800,0.3100,...,0.2900,0.1300,0.1900,0.1742,0.2700,9083.53,76371.88,live,2026-10-21 14:05:22.239,2026-10-03
8,KXFED-26OCT-T4.00,1440,2026-10-02 04:00:00.000,2026-10-02,0.3300,0.3700,0.2400,0.2700,0.3600,0.4800,...,0.4400,0.2400,0.2700,0.2981,0.3600,9907.05,76290.63,live,2026-10-21 14:05:18.314,2026-10-02
9,KXFED-26OCT-T4.00,1440,2026-10-14 04:00:00.000,2026-10-14,0.1800,0.2200,0.1600,0.2000,0.1900,0.2400,...,0.2400,0.1700,0.2100,0.2011,0.1900,715.63,70653.11,live,2026-10-21 14:07:54.476,2026-10-14

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="kalshi_macro_candles_1d", target_location="./data", asof_date='2026-10-21')

Downloading using native python implementation for kalshi_macro_candles_1d...
Found 1 files to download.
Native replication completed for kalshi_macro_candles_1d. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_macro_candles_1d", target_location="./data")