In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [5]:
df = Unifier.get_dataframe(name="kalshi_macro_markets_daily", asof_date='2026-10-22', limit=10)
display(df)

,ticker,event_ticker,series_ticker,market_type,title,yes_sub_title,no_sub_title,status,result,created_time,...,rules_secondary,price_level_structure,yes_bid_size,yes_ask_size,updated_time,expected_expiration_time,expiration_value,settlement_timer_seconds,asof_datetime,asof_date
0,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,binary,Will CPI rise more than -0.1% in December 2026?,Above -0.1%,Above -0.1%,active,None,2026-09-17 15:05:43.164,...,Please note: the Expiration Value is the singl...,linear_cent,1217.00,1260.82,2026-10-16 21:21:25.304,2027-01-13 14:56:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22
1,KXCPI-26DEC-T0.0,KXCPI-26DEC,KXCPI,binary,Will CPI rise more than 0.0% in December 2026?,Above 0.0%,Above 0.0%,active,None,2026-09-17 15:05:43.164,...,Please note: the Expiration Value is the singl...,linear_cent,1203.07,1674.00,2026-10-16 21:21:25.304,2027-01-13 14:56:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22
2,KXCPI-26DEC-T0.1,KXCPI-26DEC,KXCPI,binary,Will CPI rise more than 0.1% in December 2026?,Above 0.1%,Above 0.1%,active,None,2026-09-17 15:05:43.164,...,Please note: the Expiration Value is the singl...,linear_cent,3.00,8.00,2026-10-16 21:21:25.304,2027-01-13 14:56:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22
3,KXCPI-26DEC-T0.2,KXCPI-26DEC,KXCPI,binary,Will CPI rise more than 0.2% in December 2026?,Above 0.2%,Above 0.2%,active,None,2026-09-17 15:05:43.164,...,Please note: the Expiration Value is the singl...,linear_cent,3.00,1.00,2026-10-16 21:21:25.304,2027-01-13 14:56:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22
4,KXCPI-26DEC-T0.3,KXCPI-26DEC,KXCPI,binary,Will CPI rise more than 0.3% in December 2026?,Above 0.3%,Above 0.3%,active,None,2026-09-17 15:05:43.164,...,Please note: the Expiration Value is the singl...,linear_cent,3.00,3.00,2026-10-16 21:21:25.304,2027-01-13 14:56:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22
5,KXCPI-26DEC-T0.4,KXCPI-26DEC,KXCPI,binary,Will CPI rise more than 0.4% in December 2026?,Above 0.4%,Above 0.4%,active,None,2026-09-17 15:05:43.164,...,Please note: the Expiration Value is the singl...,linear_cent,2845.00,3.00,2026-10-16 21:21:25.304,2027-01-13 14:56:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22
6,KXCPI-26DEC-T0.5,KXCPI-26DEC,KXCPI,binary,Will CPI rise more than 0.5% in December 2026?,Above 0.5%,Above 0.5%,active,None,2026-09-17 15:05:43.164,...,Please note: the Expiration Value is the singl...,linear_cent,6026.00,1716.89,2026-10-16 21:21:25.304,2027-01-13 14:56:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22
7,KXCPI-26DEC-T0.6,KXCPI-26DEC,KXCPI,binary,Will CPI rise more than 0.6% in December 2026?,Above 0.6%,Above 0.6%,active,None,2026-09-17 15:05:43.164,...,Please note: the Expiration Value is the singl...,linear_cent,14.00,9.00,2026-10-16 21:21:25.304,2027-01-13 14:56:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22
8,KXCPI-26DEC-T0.7,KXCPI-26DEC,KXCPI,binary,Will CPI rise more than 0.7% in December 2026?,Above 0.7%,Above 0.7%,active,None,2026-09-17 15:05:43.164,...,Please note: the Expiration Value is the singl...,linear_cent,2847.00,3.00,2026-10-16 21:21:25.304,2027-01-13 14:56:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22
9,KXCPI-26DEC-T0.8,KXCPI-26DEC,KXCPI,binary,Will CPI rise more than 0.8% in December 2026?,Above 0.8%,Above 0.8%,active,None,2026-09-17 15:05:43.164,...,Please note: the Expiration Value is the singl...,linear_cent,3088.00,1798.00,2026-10-16 21:21:25.304,2027-01-13 14:56:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22

## Retrieve data for a specific date range using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='kalshi_macro_markets_daily', back_to='2026-10-19', up_to='2026-10-23', limit=10)
display(df)

,ticker,event_ticker,series_ticker,market_type,title,yes_sub_title,no_sub_title,status,result,created_time,...,rules_secondary,price_level_structure,yes_bid_size,yes_ask_size,updated_time,expected_expiration_time,expiration_value,settlement_timer_seconds,asof_datetime,asof_date
0,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,binary,Will CPI rise more than -0.1% in December 2026?,Above -0.1%,Above -0.1%,active,None,2026-09-17 15:05:43.164,...,Please note: the Expiration Value is the singl...,linear_cent,1217.00,1260.82,2026-10-16 21:21:25.304,2027-01-13 14:56:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22
1,KXCPI-26DEC-T0.0,KXCPI-26DEC,KXCPI,binary,Will CPI rise more than 0.0% in December 2026?,Above 0.0%,Above 0.0%,active,None,2026-09-17 15:05:43.164,...,Please note: the Expiration Value is the singl...,linear_cent,1203.07,1674.00,2026-10-16 21:21:25.304,2027-01-13 14:56:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22
2,KXCPI-26DEC-T0.1,KXCPI-26DEC,KXCPI,binary,Will CPI rise more than 0.1% in December 2026?,Above 0.1%,Above 0.1%,active,None,2026-09-17 15:05:43.164,...,Please note: the Expiration Value is the singl...,linear_cent,3.00,8.00,2026-10-16 21:21:25.304,2027-01-13 14:56:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22
3,KXCPI-26DEC-T0.2,KXCPI-26DEC,KXCPI,binary,Will CPI rise more than 0.2% in December 2026?,Above 0.2%,Above 0.2%,active,None,2026-09-17 15:05:43.164,...,Please note: the Expiration Value is the singl...,linear_cent,3.00,1.00,2026-10-16 21:21:25.304,2027-01-13 14:56:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22
4,KXCPI-26DEC-T0.3,KXCPI-26DEC,KXCPI,binary,Will CPI rise more than 0.3% in December 2026?,Above 0.3%,Above 0.3%,active,None,2026-09-17 15:05:43.164,...,Please note: the Expiration Value is the singl...,linear_cent,3.00,3.00,2026-10-16 21:21:25.304,2027-01-13 14:56:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22
5,KXCPI-26DEC-T0.4,KXCPI-26DEC,KXCPI,binary,Will CPI rise more than 0.4% in December 2026?,Above 0.4%,Above 0.4%,active,None,2026-09-17 15:05:43.164,...,Please note: the Expiration Value is the singl...,linear_cent,2845.00,3.00,2026-10-16 21:21:25.304,2027-01-13 14:56:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22
6,KXCPI-26DEC-T0.5,KXCPI-26DEC,KXCPI,binary,Will CPI rise more than 0.5% in December 2026?,Above 0.5%,Above 0.5%,active,None,2026-09-17 15:05:43.164,...,Please note: the Expiration Value is the singl...,linear_cent,6026.00,1716.89,2026-10-16 21:21:25.304,2027-01-13 14:56:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22
7,KXCPI-26DEC-T0.6,KXCPI-26DEC,KXCPI,binary,Will CPI rise more than 0.6% in December 2026?,Above 0.6%,Above 0.6%,active,None,2026-09-17 15:05:43.164,...,Please note: the Expiration Value is the singl...,linear_cent,14.00,9.00,2026-10-16 21:21:25.304,2027-01-13 14:56:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22
8,KXCPI-26DEC-T0.7,KXCPI-26DEC,KXCPI,binary,Will CPI rise more than 0.7% in December 2026?,Above 0.7%,Above 0.7%,active,None,2026-09-17 15:05:43.164,...,Please note: the Expiration Value is the singl...,linear_cent,2847.00,3.00,2026-10-16 21:21:25.304,2027-01-13 14:56:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22
9,KXCPI-26DEC-T0.8,KXCPI-26DEC,KXCPI,binary,Will CPI rise more than 0.8% in December 2026?,Above 0.8%,Above 0.8%,active,None,2026-09-17 15:05:43.164,...,Please note: the Expiration Value is the singl...,linear_cent,3088.00,1798.00,2026-10-16 21:21:25.304,2027-01-13 14:56:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [8]:
df = Unifier.get_dataframe(name='kalshi_macro_markets_daily',key='KXCPIYOY-26NOV-T3.9', asof_date='2026-10-23', limit=10)
display(df)

,ticker,event_ticker,series_ticker,market_type,title,yes_sub_title,no_sub_title,status,result,created_time,...,rules_secondary,price_level_structure,yes_bid_size,yes_ask_size,updated_time,expected_expiration_time,expiration_value,settlement_timer_seconds,asof_datetime,asof_date
0,KXCPIYOY-26NOV-T3.9,KXCPIYOY-26NOV,KXCPIYOY,binary,Will the rate of CPI inflation be above 3.9% f...,Above 3.9%,Above 3.9%,active,None,2026-06-10 16:59:20.761,...,In the case of a delay in data caused by a fed...,linear_cent,346.54,33.72,2026-10-17 18:10:08.054,2026-12-10 15:00:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [9]:
df = Unifier.get_dataframe(name='kalshi_macro_markets_daily',key='KXCPIYOY-26NOV-T3.9', back_to='2026-10-19', up_to='2026-10-23', limit=10)
display(df)

,ticker,event_ticker,series_ticker,market_type,title,yes_sub_title,no_sub_title,status,result,created_time,...,rules_secondary,price_level_structure,yes_bid_size,yes_ask_size,updated_time,expected_expiration_time,expiration_value,settlement_timer_seconds,asof_datetime,asof_date
0,KXCPIYOY-26NOV-T3.9,KXCPIYOY-26NOV,KXCPIYOY,binary,Will the rate of CPI inflation be above 3.9% f...,Above 3.9%,Above 3.9%,active,None,2026-06-10 16:59:20.761,...,In the case of a delay in data caused by a fed...,linear_cent,346.54,33.72,2026-10-17 18:10:08.054,2026-12-10 15:00:00.000,None,300,2026-10-22 02:10:15.098,2026-10-22

## Download data file for a specific date using asof_date

In [10]:
Unifier.replicate(name="kalshi_macro_markets_daily", target_location="./data", asof_date='2026-10-22')

Downloading using native python implementation for kalshi_macro_markets_daily...
Found 1 files to download.
Native replication completed for kalshi_macro_markets_daily. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_macro_markets_daily", target_location="./data")