In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="kalshi_macro_orderbook_levels", asof_date='2026-10-22', limit=10)
display(df)

,ticker,event_ticker,series_ticker,side,level,price,quantity,cum_quantity,implied_ask,asof_datetime,asof_date
0,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,no,1,0.0800,1173.82,1173.82,0.9200,2026-10-22 13:14:57.527,2026-10-22
1,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,no,2,0.0200,326.07,1499.89,0.9800,2026-10-22 13:14:57.527,2026-10-22
2,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,no,3,0.0100,1015.20,2515.09,0.9900,2026-10-22 13:14:57.527,2026-10-22
3,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,yes,1,0.9100,540.00,540.00,0.0900,2026-10-22 13:14:57.527,2026-10-22
4,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,yes,2,0.8600,12.69,552.69,0.1400,2026-10-22 13:14:57.527,2026-10-22
5,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,yes,3,0.8500,3.00,555.69,0.1500,2026-10-22 13:14:57.527,2026-10-22
6,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,yes,4,0.6700,17.31,573.00,0.3300,2026-10-22 13:14:57.527,2026-10-22
7,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,yes,5,0.6600,3.08,576.08,0.3400,2026-10-22 13:14:57.527,2026-10-22
8,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,yes,6,0.2000,3.00,579.08,0.8000,2026-10-22 13:14:57.527,2026-10-22
9,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,yes,7,0.1000,58.00,637.08,0.9000,2026-10-22 13:14:57.527,2026-10-22

## Retrieve data for a specific date range using the back_to and up_to parameters

In [ ]:
df = Unifier.get_dataframe(name='kalshi_macro_orderbook_levels', back_to='2026-10-22', up_to='2026-10-23', limit=100)
display(df)

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [5]:
df = Unifier.get_dataframe(name='kalshi_macro_orderbook_levels',key='KXFED-26DEC-T4.50', asof_date='2026-10-22', limit=10)
display(df)

,ticker,event_ticker,series_ticker,side,level,price,quantity,cum_quantity,implied_ask,asof_datetime,asof_date
0,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,no,1,0.9400,25.00,25.00,0.0600,2026-10-22 13:14:57.527,2026-10-22
1,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,no,2,0.9300,1998.24,2023.24,0.0700,2026-10-22 13:14:57.527,2026-10-22
2,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,no,3,0.9200,2044.56,4067.80,0.0800,2026-10-22 13:14:57.527,2026-10-22
3,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,no,4,0.9100,2143.97,6211.77,0.0900,2026-10-22 13:14:57.527,2026-10-22
4,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,no,5,0.9000,10000.00,16211.77,0.1000,2026-10-22 13:14:57.527,2026-10-22
5,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,no,6,0.8900,231.14,16442.91,0.1100,2026-10-22 13:14:57.527,2026-10-22
6,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,no,7,0.8800,200.00,16642.91,0.1200,2026-10-22 13:14:57.527,2026-10-22
7,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,no,8,0.8500,1200.00,17842.91,0.1500,2026-10-22 13:14:57.527,2026-10-22
8,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,no,9,0.8100,10100.00,27942.91,0.1900,2026-10-22 13:14:57.527,2026-10-22
9,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,no,10,0.6000,570.00,28512.91,0.4000,2026-10-22 13:14:57.527,2026-10-22

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [6]:
df = Unifier.get_dataframe(name='kalshi_macro_orderbook_levels',key='KXFED-26DEC-T4.50', back_to='2026-10-22', up_to='2026-10-23', limit=10)
display(df)

,ticker,event_ticker,series_ticker,side,level,price,quantity,cum_quantity,implied_ask,asof_datetime,asof_date
0,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,no,1,0.9400,25.00,25.00,0.0600,2026-10-22 13:14:57.527,2026-10-22
1,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,no,2,0.9300,1998.24,2023.24,0.0700,2026-10-22 13:14:57.527,2026-10-22
2,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,no,3,0.9200,2044.56,4067.80,0.0800,2026-10-22 13:14:57.527,2026-10-22
3,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,no,4,0.9100,2143.97,6211.77,0.0900,2026-10-22 13:14:57.527,2026-10-22
4,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,no,5,0.9000,10000.00,16211.77,0.1000,2026-10-22 13:14:57.527,2026-10-22
5,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,no,6,0.8900,231.14,16442.91,0.1100,2026-10-22 13:14:57.527,2026-10-22
6,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,no,7,0.8800,200.00,16642.91,0.1200,2026-10-22 13:14:57.527,2026-10-22
7,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,no,8,0.8500,1200.00,17842.91,0.1500,2026-10-22 13:14:57.527,2026-10-22
8,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,no,9,0.8100,10100.00,27942.91,0.1900,2026-10-22 13:14:57.527,2026-10-22
9,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,no,10,0.6000,570.00,28512.91,0.4000,2026-10-22 13:14:57.527,2026-10-22

## Download data file for a specific date using asof_date

In [7]:
Unifier.replicate(name="kalshi_macro_orderbook_levels", target_location="./data", asof_date='2026-10-22')

Downloading using native python implementation for kalshi_macro_orderbook_levels...
Found 2 files to download.
Native replication completed for kalshi_macro_orderbook_levels. Downloaded 2 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_macro_orderbook_levels", target_location="./data")