In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [5]:
df = Unifier.get_dataframe(name="kalshi_macro_daily_moments", asof_date='2026-10-22', limit=10)
display(df)

,dataset,series_ticker,contract_preamble,expiry_date,method,n_bins,daily_volume,mean,median,mode,skewness,kurtosis,variance,asof_datetime,asof_date
0,fed_levels,KXFED,KXFED-26DEC,2026-12-09,threshold,12,1984.69,4.114796,4.125,4.125,-0.105263,3.127605,0.034335,2026-10-22 02:33:10.152,2026-10-21
1,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,2241.94,3.903061,3.875,3.875,1.000000,3.895521,0.006228,2026-10-22 02:33:10.152,2026-10-21
2,fed_levels,KXFED,KXFED-27JAN,2027-01-27,threshold,26,0.00,4.341837,4.250,4.125,0.934066,-0.523069,0.077344,2026-10-22 02:33:10.152,2026-10-21
3,fed_levels,KXFED,KXFED-27MAR,2027-03-17,threshold,25,0.00,4.857143,4.875,4.625,-0.061947,0.078912,0.144452,2026-10-22 02:33:10.152,2026-10-21
4,gdp_end_of_year,KXGDPYEAR,KXGDPYEAR-26,2027-02-28,bins,14,1985.49,2.298415,2.300,2.300,-0.002908,4.429251,1.048983,2026-10-22 02:33:10.152,2026-10-21
5,gdp_end_of_year,KXGDPYEAR,KXGDPYEAR-27,2028-02-28,bins,12,0.00,2.025680,2.300,2.300,-0.250449,0.565868,2.018301,2026-10-22 02:33:10.152,2026-10-21
6,gdp_end_of_year,KXGDPYEAR,KXGDPYEAR-28,2029-02-28,bins,7,0.00,2.036044,0.800,2.800,0.753887,-0.660823,4.209888,2026-10-22 02:33:10.152,2026-10-21
7,gdp_end_of_year,KXGDPYEAR,KXGDPYEAR-30,2031-02-28,bins,13,0.00,2.394499,2.300,2.800,0.079585,-0.020407,2.406015,2026-10-22 02:33:10.152,2026-10-21
8,gdp_end_of_year,KXGDPYEAR,KXGDPYEAR-31,2032-02-29,bins,8,0.00,3.006735,3.300,2.300,-0.191812,-1.075148,3.411225,2026-10-22 02:33:10.152,2026-10-21
9,gdp_end_of_year,KXGDPYEAR,KXGDPYEAR-32,2033-02-28,bins,14,0.00,2.682209,2.300,2.300,0.241683,-1.160552,3.613772,2026-10-22 02:33:10.152,2026-10-21

## Retrieve data for a specific date range using the back_to and up_to parameters

In [6]:
df = Unifier.get_dataframe(name='kalshi_macro_daily_moments', back_to='2026-09-01', up_to='2026-10-22', limit=10)
display(df)

,dataset,series_ticker,contract_preamble,expiry_date,method,n_bins,daily_volume,mean,median,mode,skewness,kurtosis,variance,asof_datetime,asof_date
0,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-25OCT,2025-11-13,threshold,5,0,3.082653,3.100,3.000,-0.195402,-0.836074,0.012046,2026-10-21 11:30:35.093,2025-10-19
1,fed_levels,KXFED,FED-25DEC,2025-12-10,threshold,12,4,3.635204,3.625,3.625,0.090909,3.385700,0.044539,2026-10-21 11:30:35.093,2025-10-19
2,fed_levels,KXFED,FED-25OCT,2025-10-29,threshold,12,35629,3.867347,3.875,3.875,-0.333333,17.312128,0.008232,2026-10-21 11:30:35.093,2025-10-19
3,fed_levels,KXFED,KXFED-26JAN,2026-01-28,threshold,4,0,3.635204,3.625,3.375,0.051282,-0.764625,0.067498,2026-10-21 11:30:35.093,2025-10-19
4,fed_levels,KXFED,KXFED-26MAR,2026-03-18,threshold,4,0,3.604592,3.625,3.375,-0.121212,-0.675958,0.046777,2026-10-21 11:30:35.093,2025-10-19
5,gdp_end_of_year,KXGDPYEAR,KXGDPYEAR-25,2026-02-20,bins,12,234,2.018049,1.800,2.300,0.452225,4.319056,0.536031,2026-10-21 11:30:35.093,2025-10-19
6,headline_cpi_end_of_year,KXACPI,KXACPI-2025,2026-01-13,bins,11,0,3.190787,3.300,3.300,-0.216696,2.371951,0.673922,2026-10-21 11:30:35.093,2025-10-19
7,headline_cpi_releases,KXCPIYOY,KXCPIYOY-25OCT,2025-11-13,threshold,9,508,3.048980,3.100,3.100,-0.595238,1.230286,0.012703,2026-10-21 11:30:35.093,2025-10-19
8,headline_cpi_releases_mom,KXCPI,KXCPI-25OCT,2025-11-13,threshold,7,201,0.225510,0.200,0.200,0.342466,1.153697,0.012512,2026-10-21 11:30:35.093,2025-10-19
9,unemployment_releases,KXU3,KXU3-25OCT,2025-11-07,threshold,7,447,4.387755,4.400,4.300,-0.115385,-0.050112,0.020258,2026-10-21 11:30:35.093,2025-10-19

## Retrieve data for a specific date with a specific contract_preamble (key='contract_preamble') using the asof_date parameter

In [8]:
df = Unifier.get_dataframe(name='kalshi_macro_daily_moments',key='KXFED-26OCT', asof_date='2026-10-22', limit=10)
display(df)

,dataset,series_ticker,contract_preamble,expiry_date,method,n_bins,daily_volume,mean,median,mode,skewness,kurtosis,variance,asof_datetime,asof_date
0,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,2241.94,3.903061,3.875,3.875,1.000000,3.895521,0.006228,2026-10-22 02:33:10.152,2026-10-21
1,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,3349.89,3.936224,3.875,3.875,1.000000,1.011434,0.012833,2026-10-21 14:06:07.631,2026-10-04
2,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,1900.63,3.908163,3.875,3.875,1.000000,2.578144,0.007191,2026-10-21 14:08:35.165,2026-10-20
3,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,2088.07,3.798469,3.875,3.875,-0.681818,-0.132713,0.024755,2026-10-21 14:05:27.905,2026-09-05
4,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,189.30,3.897959,3.875,3.875,0.257143,-0.249334,0.021794,2026-10-21 14:05:37.481,2026-09-12
5,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,17918.90,4.017857,4.125,4.125,-0.954545,-0.979794,0.017857,2026-10-21 14:05:45.525,2026-09-18
6,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,66877.16,3.992347,3.875,3.875,1.000000,-2.005149,0.015566,2026-10-21 14:06:00.734,2026-09-29
7,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,2889.67,4.020408,4.125,4.125,-0.953488,-0.944072,0.017760,2026-10-21 14:05:46.861,2026-09-19
8,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,278.83,4.033163,4.125,4.125,-0.947368,-0.679765,0.017076,2026-10-21 14:05:56.570,2026-09-26
9,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,3730.75,4.043367,4.125,4.125,-0.941176,-0.343629,0.016295,2026-10-21 14:05:53.761,2026-09-24

## Retrieve data for a specific date range with a specific contract_preamble (key='contract_preamble') using the back_to and up_to parameters

In [9]:
df = Unifier.get_dataframe(name='kalshi_macro_daily_moments',key='KXFED-26OCT', back_to='2026-09-01', up_to='2026-10-22', limit=10)
display(df)

,dataset,series_ticker,contract_preamble,expiry_date,method,n_bins,daily_volume,mean,median,mode,skewness,kurtosis,variance,asof_datetime,asof_date
0,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,1900.63,3.908163,3.875,3.875,1.000000,2.578144,0.007191,2026-10-21 14:08:35.165,2026-10-20
1,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,3349.89,3.936224,3.875,3.875,1.000000,1.011434,0.012833,2026-10-21 14:06:07.631,2026-10-04
2,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,63.00,3.892857,3.875,3.875,0.212121,-0.089857,0.020727,2026-10-21 14:05:38.819,2026-09-13
3,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,6079.32,4.022959,4.125,4.125,-0.952381,-0.902995,0.017649,2026-10-21 14:05:48.230,2026-09-20
4,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,2042.11,4.005102,4.125,4.125,-0.959184,-1.084121,0.018150,2026-10-21 14:05:49.590,2026-09-21
5,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,17918.90,4.017857,4.125,4.125,-0.954545,-0.979794,0.017857,2026-10-21 14:05:45.525,2026-09-18
6,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,10103.23,4.056122,4.125,4.125,-0.931034,-0.777179,0.013751,2026-10-21 14:05:59.341,2026-09-28
7,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,2088.07,3.798469,3.875,3.875,-0.681818,-0.132713,0.024755,2026-10-21 14:05:27.905,2026-09-05
8,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,25142.05,3.989796,3.875,3.875,0.957447,-1.056708,0.018072,2026-10-21 14:05:42.843,2026-09-16
9,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,12,4255.05,3.818878,3.875,3.875,-0.550000,0.375034,0.026187,2026-10-21 14:05:34.753,2026-09-10

## Download data file for a specific date using asof_date

In [10]:
Unifier.replicate(name="kalshi_macro_daily_moments", target_location="./data", asof_date='2026-10-21')

Downloading using native python implementation for kalshi_macro_daily_moments...
Found 1 files to download.
Native replication completed for kalshi_macro_daily_moments. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_macro_daily_moments", target_location="./data")