In [1]:
import os
from IPython.display import display

In [2]:
%pip install unifier --upgrade

Requirement already satisfied: unifier in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (0.1.20)
Requirement already satisfied: requests in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from unifier) (3.0.1)
Requirement already satisfied: boto3 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from unifier) (1.42.75)
Requirement already satisfied: botocore<1.43.0,>=1.42.75 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from boto3->unifier) (1.42.75)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from boto3->unifier) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from boto3->unifier) (0.16.0)
Requirement already satisfied: numpy>=1.26.0 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from pandas->unifier) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (2026.2.25)
Requirement already satisfied: six>=1.5 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
from unifier import unifier

In [ ]:


unifier.user = 'unifier email'
unifier.token ='unifier api token'
os.environ['UNIFIER_USER'] = unifier.user
os.environ['UNIFIER_TOKEN'] = unifier.token

Your 'unifier username' is your account email address, and your 'unifier api token' is your account api token found in the access my data page.

Dataset: xtech_apollo_group_aggregates_red_eagle,
 xtech_apollo_group_style_aggregates_gross_position_style_red_eagle, 
 xtech_apollo_group_style_aggregates_trade_size_style_red_eagle, 
 xtech_apollo_group_style_aggregates_turnover_style_red_eagle

In [ ]:
# Replicate a large dataset to a local folder
# Note: rclone must be installed on your system
unifier.replicate(
    name="xtech_apollo_group_aggregates_silver_leopard",
    target_location="./your_local_path",
    back_to="",    # Optional: fetch history back to this date
    up_to="",    # Optional: fetch history up to this date
    bandwidth_limit=20       # Optional: limit download speed to 20MB/s
)

Downloading using native python implementation for xtech_apollo_group_aggregates_red_eagle...
Found 1880 files to download.
Downloaded 10/1880 files...
Downloaded 20/1880 files...
Downloaded 30/1880 files...

KeyboardInterrupt:

In [13]:
df = unifier.get_dataframe(name="xtech_apollo_group_aggregates_silver_leopard", back_to="2021-01-03" , up_to="2021-02-03", limit=20)
display(df)

,asof_date,trade_date,sector,mds_exchange,exchange_country,reportable_product,product_name,xt_group,direction,long_dollar_value,short_dollar_value,net_dollar_value,gross_dollar_value,long_position,short_position,net_position,gross_position,long_position_concentration,short_position_concentration,combined_position_concentration
0,2021-01-06 00:00:00.000,20210105,EQY,EUREX,DEU,(H,EUREX STOXX EUROPE 600 ESG-X FUTURES,nonreportable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,commercial,1.0,4.280311e+08,2.441098e+08,1.839213e+08,6.721410e+08,17513.0,13045.0,4468.0,30558.0,0.140080,0.063812,0.065225
2,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,nonreportable,1.0,4.608522e+08,2.939489e+08,1.669032e+08,7.548011e+08,14903.0,10774.0,4129.0,25677.0,0.018294,0.101396,0.022198
3,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,non_commercial,1.0,4.217689e+07,2.884280e+06,3.929261e+07,4.506117e+07,989.0,79.0,910.0,1068.0,0.076399,0.141203,0.067510
4,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,commercial,-1.0,2.678681e+07,8.015922e+07,-5.337241e+07,1.069460e+08,4430.0,6483.0,-2053.0,10913.0,0.247782,0.114147,0.079672
5,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,nonreportable,1.0,4.017194e+08,2.110762e+08,1.906432e+08,6.127956e+08,17013.0,9232.0,7781.0,26245.0,0.035784,0.073941,0.024151
6,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,non_commercial,1.0,6.174583e+07,1.394220e+06,6.035161e+07,6.314005e+07,2379.0,68.0,2311.0,2447.0,0.081285,0.158915,0.077812
7,2021-01-06 00:00:00.000,20210105,NRG,IPE,GBR,14Y,ICEEU ULSD 10PPM CIF NWE CARGOES F,commercial,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2021-01-06 00:00:00.000,20210105,NRG,IPE,GBR,14Y,ICEEU ULSD 10PPM CIF NWE CARGOES F,nonreportable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,14,CBOT CRC ROUGH RICE FUTURE,commercial,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,14,CBOT CRC ROUGH RICE FUTURE,nonreportable,-1.0,5.344000e+06,3.613784e+07,-3.079384e+07,4.148184e+07,504.0,1725.0,-1221.0,2229.0,0.465920,0.848638,0.651799
11,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,14,CBOT CRC ROUGH RICE FUTURE,non_commercial,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2021-01-06 00:00:00.000,20210105,INT,CBOT,USA,17,CBOT US TREASURY BOND FUTURE,commercial,-1.0,5.332000e+06,3.440000e+07,-2.906800e+07,3.973200e+07,31.0,200.0,-169.0,231.0,0.710718,0.127650,0.108487
13,2021-01-06 00:00:00.000,20210105,INT,CBOT,USA,17,CBOT US TREASURY BOND FUTURE,nonreportable,1.0,4.264224e+09,1.432760e+08,4.120948e+09,4.407500e+09,24853.0,894.0,23959.0,25747.0,0.480577,0.119718,0.449967
14,2021-01-06 00:00:00.000,20210105,INT,CBOT,USA,17,CBOT US TREASURY BOND FUTURE,non_commercial,1.0,5.056800e+07,1.461856e+07,3.594944e+07,6.518656e+07,308.0,99.0,209.0,407.0,0.175274,0.117806,0.111401
15,2021-01-06 00:00:00.000,20210105,EQY,EUREX,DEU,1@,EUREX MSCI WORLD PRICE INDEX FUTURES,nonreportable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2021-01-06 00:00:00.000,20210105,NRG,NYMEX,USA,1L,NYMEX ULSD UP-DOWN BALMO CAL DAILY SWAP,nonreportable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2021-01-06 00:00:00.000,20210105,NRG,NYMEX,USA,1M,NYMEX JET FUEL UP-DWN BALMO CAL DAY SWAP,nonreportable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2021-01-06 00:00:00.000,20210105,INT,CBOT,USA,21,CBOT 10Y US TREASURY NOTE FUTURE,commercial,-1.0,1.916009e+08,1.325092e+09,-1.133491e+09,1.516693e+09,1406.0,9629.0,-8223.0,11035.0,0.438746,0.743703,0.574672
19,2021-01-06 00:00:00.000,20210105,INT,CBOT,USA,21,CBOT 10Y US TREASURY NOTE FUTURE,nonreportable,1.0,8.685094e+08,8.471877e+08,2.132172e+07,1.715697e+09,6446.0,6291.0,155.0,12737.0,0.169848,0.278734,0.111486

In [14]:
df = unifier.get_dataframe(name="xtech_apollo_group_style_aggregates_gross_position_style_silver_leopard", back_to="2021-01-03" , up_to="2021-02-03", limit=20)
display(df)

,asof_date,trade_date,sector,mds_exchange,exchange_country,reportable_product,product_name,xt_group,position_style,direction,...,short_dollar_value,net_dollar_value,gross_dollar_value,long_position,short_position,net_position,gross_position,long_position_concentration,short_position_concentration,combined_position_concentration
0,2021-01-06 00:00:00.000,20210105,EQY,EUREX,DEU,(H,EUREX STOXX EUROPE 600 ESG-X FUTURES,nonreportable,large,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,commercial,small,1,...,641140.0,1813260.0,3095540.0,62.0,18.0,44.0,80.0,0.067874,0.178797,0.050340
2,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,commercial,medium,1,...,3359570.0,6487360.0,13206500.0,310.0,153.0,157.0,463.0,0.084181,0.294635,0.065866
3,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,commercial,large,1,...,179307950.0,175620690.0,534236590.0,17141.0,12874.0,4267.0,30015.0,0.739320,0.122178,0.340086
4,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,non_commercial,small,1,...,338300.0,1904710.0,2581310.0,83.0,39.0,44.0,122.0,0.079899,0.350659,0.066352
5,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,non_commercial,medium,1,...,0.0,2728350.0,2728350.0,72.0,9.0,63.0,81.0,0.059823,0.000000,0.059823
6,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,non_commercial,large,1,...,349230.0,34616370.0,35314830.0,833.0,31.0,802.0,864.0,0.110081,0.978531,0.108010
7,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,nonreportable,small,1,...,691820.0,7440370.0,8824010.0,205.0,28.0,177.0,233.0,0.037502,0.209756,0.033141
8,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,nonreportable,medium,1,...,5466490.0,22195080.0,33128060.0,953.0,443.0,510.0,1396.0,0.041021,0.703794,0.047763
9,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,nonreportable,large,1,...,195719480.0,137337200.0,528776160.0,13738.0,10294.0,3444.0,24032.0,0.080865,0.172629,0.055732
10,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,commercial,small,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,commercial,medium,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,commercial,large,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,non_commercial,small,1,...,0.0,2013642.0,2013642.0,77.0,0.0,77.0,77.0,0.026152,0.000000,0.026152
14,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,non_commercial,medium,1,...,2082.0,5851896.0,5856060.0,252.0,28.0,224.0,280.0,0.043771,1.000000,0.043740
15,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,non_commercial,large,1,...,18720.0,52482930.0,52520370.0,2048.0,38.0,2010.0,2086.0,0.113831,0.625000,0.113750
16,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,nonreportable,small,1,...,760644.0,2492688.0,4013976.0,137.0,41.0,96.0,178.0,0.037403,0.259037,0.033872
17,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,nonreportable,medium,1,...,1812360.0,10179234.0,13803954.0,731.0,335.0,396.0,1066.0,0.088671,0.367325,0.073247
18,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,nonreportable,large,1,...,146672280.0,177971292.0,471315852.0,16145.0,8856.0,7289.0,25001.0,0.123882,0.135522,0.071900
19,2021-01-06 00:00:00.000,20210105,NRG,IPE,GBR,14Y,ICEEU ULSD 10PPM CIF NWE CARGOES F,commercial,large,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df = unifier.get_dataframe(name="xtech_apollo_group_style_aggregates_trade_size_style_silver_leopard", back_to="2021-01-03" , up_to="2021-02-03", limit=20)
display(df)

,asof_date,trade_date,sector,mds_exchange,exchange_country,reportable_product,product_name,xt_group,trade_size_style,direction,...,short_dollar_value,net_dollar_value,gross_dollar_value,long_position,short_position,net_position,gross_position,long_position_concentration,short_position_concentration,combined_position_concentration
0,2021-01-06 00:00:00.000,20210105,EQY,EUREX,DEU,(H,EUREX STOXX EUROPE 600 ESG-X FUTURES,nonreportable,large,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,commercial,small,1,...,48868810.0,12215100.0,109952720.0,2293.0,2033.0,260.0,4326.0,0.452595,0.334806,0.205823
2,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,commercial,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,non_commercial,small,1,...,516130.0,29273530.0,30305790.0,753.0,75.0,678.0,828.0,0.093873,0.488370,0.090845
4,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,non_commercial,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,nonreportable,small,1,...,69186440.0,177516540.0,315889420.0,6873.0,2590.0,4283.0,9463.0,0.044685,0.218052,0.037714
6,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,nonreportable,medium,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,nonreportable,large,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,commercial,small,-1,...,36312798.0,-28685514.0,43940082.0,1027.0,2134.0,-1107.0,3161.0,0.187780,0.207944,0.147676
9,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,commercial,medium,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,non_commercial,small,1,...,20802.0,50407668.0,50449272.0,1997.0,66.0,1931.0,2063.0,0.104710,0.516170,0.104624
11,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,non_commercial,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,nonreportable,small,1,...,61059510.0,227921718.0,350040738.0,12399.0,3311.0,9088.0,15710.0,0.144908,0.170060,0.103938
13,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,nonreportable,medium,-1,...,88185774.0,-37278504.0,139093044.0,4614.0,5921.0,-1307.0,10535.0,0.373582,0.293539,0.168034
14,2021-01-06 00:00:00.000,20210105,NRG,IPE,GBR,14Y,ICEEU ULSD 10PPM CIF NWE CARGOES F,commercial,small,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2021-01-06 00:00:00.000,20210105,NRG,IPE,GBR,14Y,ICEEU ULSD 10PPM CIF NWE CARGOES F,nonreportable,small,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,14,CBOT CRC ROUGH RICE FUTURE,commercial,small,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,14,CBOT CRC ROUGH RICE FUTURE,commercial,medium,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,14,CBOT CRC ROUGH RICE FUTURE,commercial,large,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2021-01-06 00:00:00.000,20210105,AGR,CBOT,USA,14,CBOT CRC ROUGH RICE FUTURE,non_commercial,small,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df = unifier.get_dataframe(name="xtech_apollo_group_style_aggregates_turnover_style_silver_leopard", back_to="2021-01-03" , up_to="2021-02-03", limit=20)
display(df)

,asof_date,trade_date,sector,mds_exchange,exchange_country,reportable_product,product_name,xt_group,turnover_style,direction,...,short_dollar_value,net_dollar_value,gross_dollar_value,long_position,short_position,net_position,gross_position,long_position_concentration,short_position_concentration,combined_position_concentration
0,2021-01-07 00:00:00.000,20210106,EQY,EUREX,DEU,(H,EUREX STOXX EUROPE 600 ESG-X FUTURES,nonreportable,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,commercial,low,1,...,149201790.0,223680430.0,522084010.0,14380.0,9065.0,5315.0,23445.0,0.687208,0.159848,0.363605
2,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,commercial,medium,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,non_commercial,low,1,...,527690.0,28486930.0,29542310.0,726.0,76.0,650.0,802.0,0.100526,0.496249,0.097125
4,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,non_commercial,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,nonreportable,low,1,...,195092360.0,168450210.0,558634930.0,11716.0,7532.0,4184.0,19248.0,0.071160,0.176943,0.051717
6,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,nonreportable,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,commercial,low,-1,...,63067308.0,-37531734.0,88602882.0,5146.0,6595.0,-1449.0,11741.0,0.324031,0.175868,0.116019
8,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,commercial,medium,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,non_commercial,low,1,...,47790.0,54712548.0,54808128.0,2154.0,70.0,2084.0,2224.0,0.098369,0.409489,0.098197
10,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,non_commercial,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,nonreportable,low,1,...,129064524.0,150051228.0,408180276.0,13635.0,7517.0,6118.0,21152.0,0.126804,0.160735,0.075362
12,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,nonreportable,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2021-01-07 00:00:00.000,20210106,NRG,IPE,GBR,14Y,ICEEU ULSD 10PPM CIF NWE CARGOES F,commercial,low,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2021-01-07 00:00:00.000,20210106,NRG,IPE,GBR,14Y,ICEEU ULSD 10PPM CIF NWE CARGOES F,nonreportable,low,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,14,CBOT CRC ROUGH RICE FUTURE,commercial,low,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,14,CBOT CRC ROUGH RICE FUTURE,commercial,medium,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,14,CBOT CRC ROUGH RICE FUTURE,non_commercial,low,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,14,CBOT CRC ROUGH RICE FUTURE,nonreportable,low,-1,...,36452080.0,-33712190.0,39191970.0,410.0,1738.0,-1328.0,2148.0,0.215708,0.902185,0.781506
19,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,14,CBOT CRC ROUGH RICE FUTURE,nonreportable,medium,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN