In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_eqt_flow_r3k_with_isin_1min_trial", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2019-03-06,2019-03-06 04:01:00.000,2019-03-06 04:01:03.000,1,AAPL,US0378331005,2,700.40,0.00,700.40,...,0,350.20,350.20,0,0,0,0,0,0,2019-03-06
1,2019-03-06,2019-03-06 04:01:00.000,2019-03-06 04:01:03.000,1,FB,US30303M1027,19,255180.11,26861.06,228319.05,...,8,73867.93,181312.18,0,8,0,0,0,0,2019-03-06
2,2019-03-06,2019-03-06 04:04:00.000,2019-03-06 04:04:03.000,1,AAPL,US0378331005,1,526.02,0.00,526.02,...,0,263.01,263.01,0,0,0,0,0,0,2019-03-06
3,2019-03-06,2019-03-06 04:04:00.000,2019-03-06 04:04:03.000,1,FB,US30303M1027,1,51420.00,0.00,51420.00,...,0,25710.00,25710.00,0,0,0,0,0,0,2019-03-06
4,2019-03-06,2019-03-06 04:07:00.000,2019-03-06 04:07:03.000,1,FB,US30303M1027,15,69939.28,65276.66,4662.62,...,0,34969.64,34969.64,0,0,0,0,0,0,2019-03-06
5,2019-03-06,2019-03-06 04:08:00.000,2019-03-06 04:08:03.000,1,AMD,US0079031078,1,1876.80,1876.80,0.00,...,1,938.40,938.40,0,0,0,0,0,0,2019-03-06
6,2019-03-06,2019-03-06 04:08:00.000,2019-03-06 04:08:03.000,1,FB,US30303M1027,1,6857.60,0.00,6857.60,...,1,3428.80,3428.80,0,0,0,0,0,0,2019-03-06
7,2019-03-06,2019-03-06 04:10:00.000,2019-03-06 04:10:03.000,1,FB,US30303M1027,1,69078.23,0.00,69078.23,...,1,34539.12,34539.12,0,0,0,0,0,0,2019-03-06
8,2019-03-06,2019-03-06 04:13:00.000,2019-03-06 04:13:03.000,1,AAPL,US0378331005,1,875.55,0.00,875.55,...,1,437.78,437.78,0,0,0,0,0,0,2019-03-06
9,2019-03-06,2019-03-06 04:13:00.000,2019-03-06 04:13:03.000,1,FB,US30303M1027,1,514.26,0.00,514.26,...,0,257.13,257.13,0,0,0,0,0,0,2019-03-06

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_1min_trial', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

Empty DataFrame
Columns: []
Index: []

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_1min_trial',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2019-03-06,2019-03-06 04:01:00.000,2019-03-06 04:01:03.000,1,AAPL,US0378331005,2,700.40,0.00,700.40,...,0,350.20,350.20,0,0,0.0,0.0,0,0,2019-03-06
1,2019-03-06,2019-03-06 04:04:00.000,2019-03-06 04:04:03.000,1,AAPL,US0378331005,1,526.02,0.00,526.02,...,0,263.01,263.01,0,0,0.0,0.0,0,0,2019-03-06
2,2019-03-06,2019-03-06 04:13:00.000,2019-03-06 04:13:03.000,1,AAPL,US0378331005,1,875.55,0.00,875.55,...,1,437.78,437.78,0,0,0.0,0.0,0,0,2019-03-06
3,2019-03-06,2019-03-06 04:18:00.000,2019-03-06 04:18:03.000,1,AAPL,US0378331005,1,525.96,0.00,525.96,...,0,262.98,262.98,0,0,0.0,0.0,0,0,2019-03-06
4,2019-03-06,2019-03-06 04:23:00.000,2019-03-06 04:23:03.000,1,AAPL,US0378331005,1,4553.12,0.00,4553.12,...,1,2276.56,2276.56,0,0,0.0,0.0,0,0,2019-03-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2019-03-06,2019-03-06 08:40:00.000,2019-03-06 08:40:03.000,1,AAPL,US0378331005,9,200469.78,133646.52,66823.26,...,4,0.00,200469.78,0,9,0.0,0.0,0,0,2019-03-06
96,2019-03-06,2019-03-06 08:41:00.000,2019-03-06 08:41:03.000,1,AAPL,US0378331005,7,143422.00,20488.86,122933.14,...,2,20488.86,122933.14,1,6,0.0,0.0,0,0,2019-03-06
97,2019-03-06,2019-03-06 08:42:00.000,2019-03-06 08:42:03.000,1,AAPL,US0378331005,1,1749.80,1749.80,0.00,...,0,0.00,1749.80,0,1,0.0,0.0,0,0,2019-03-06
98,2019-03-06,2019-03-06 08:43:00.000,2019-03-06 08:43:03.000,1,AAPL,US0378331005,7,86436.18,86436.18,0.00,...,2,0.00,86436.18,0,7,0.0,0.0,0,0,2019-03-06
99,2019-03-06,2019-03-06 08:44:00.000,2019-03-06 08:44:03.000,1,AAPL,US0378331005,4,93776.56,93776.56,0.00,...,1,0.00,93776.56,0,4,0.0,0.0,0,0,2019-03-06

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [9]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_1min_trial',key='AAPL', back_to='2019-01-01', up_to='2024-06-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2019-03-06,2019-03-06 04:01:00.000,2019-03-06 04:01:03.000,1,AAPL,US0378331005,2,700.40,0.00,700.40,...,0,350.20,350.20,0,0,0.0,0.0,0,0,2019-03-06
1,2019-03-06,2019-03-06 04:04:00.000,2019-03-06 04:04:03.000,1,AAPL,US0378331005,1,526.02,0.00,526.02,...,0,263.01,263.01,0,0,0.0,0.0,0,0,2019-03-06
2,2019-03-06,2019-03-06 04:13:00.000,2019-03-06 04:13:03.000,1,AAPL,US0378331005,1,875.55,0.00,875.55,...,1,437.78,437.78,0,0,0.0,0.0,0,0,2019-03-06
3,2019-03-06,2019-03-06 04:18:00.000,2019-03-06 04:18:03.000,1,AAPL,US0378331005,1,525.96,0.00,525.96,...,0,262.98,262.98,0,0,0.0,0.0,0,0,2019-03-06
4,2019-03-06,2019-03-06 04:23:00.000,2019-03-06 04:23:03.000,1,AAPL,US0378331005,1,4553.12,0.00,4553.12,...,1,2276.56,2276.56,0,0,0.0,0.0,0,0,2019-03-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2019-03-06,2019-03-06 08:40:00.000,2019-03-06 08:40:03.000,1,AAPL,US0378331005,9,200469.78,133646.52,66823.26,...,4,0.00,200469.78,0,9,0.0,0.0,0,0,2019-03-06
96,2019-03-06,2019-03-06 08:41:00.000,2019-03-06 08:41:03.000,1,AAPL,US0378331005,7,143422.00,20488.86,122933.14,...,2,20488.86,122933.14,1,6,0.0,0.0,0,0,2019-03-06
97,2019-03-06,2019-03-06 08:42:00.000,2019-03-06 08:42:03.000,1,AAPL,US0378331005,1,1749.80,1749.80,0.00,...,0,0.00,1749.80,0,1,0.0,0.0,0,0,2019-03-06
98,2019-03-06,2019-03-06 08:43:00.000,2019-03-06 08:43:03.000,1,AAPL,US0378331005,7,86436.18,86436.18,0.00,...,2,0.00,86436.18,0,7,0.0,0.0,0,0,2019-03-06
99,2019-03-06,2019-03-06 08:44:00.000,2019-03-06 08:44:03.000,1,AAPL,US0378331005,4,93776.56,93776.56,0.00,...,1,0.00,93776.56,0,4,0.0,0.0,0,0,2019-03-06

## Download data file for a specific date using asof_date

In [10]:
Unifier.replicate(name="xtech_us_eqt_flow_r3k_with_isin_1min_trial", target_location="./data", asof_date='2026-01-13')

Starting native python replication for xtech_us_eqt_flow_r3k_with_isin_1min_trial (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_eqt_flow_r3k_with_isin_1min_trial. Downloaded 1 files.