In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Futures Reference Table

In [4]:
df =  Unifier.get_dataframe(name="xtech_futures_flow_forecasts_ident")
display(df)

   identifier       sector             name  contract_multiplier   asof_date
0          CC  Agriculture            Cocoa                 10.0  2026-06-09
1          CT  Agriculture     Cotton No. 2                500.0  2026-06-09
2          DC  Agriculture   Class III Milk               2000.0  2026-06-09
3          GF  Agriculture    Feeder Cattle                500.0  2026-06-09
4          HE  Agriculture        Lean Hogs                400.0  2026-06-09
..        ...          ...              ...                  ...         ...
79         UB   Treasuries    US Ultra Bond               1000.0  2026-06-09
80         ZB   Treasuries  US 30-Year Bond               1000.0  2026-06-09
81         ZF   Treasuries   US 5-Year Note               1000.0  2026-06-09
82         ZN   Treasuries  US 10-Year Note               1000.0  2026-06-09
83         ZT   Treasuries   US 2-Year Note               2000.0  2026-06-09

[84 rows x 5 columns]

## XTech Global Futures Flow Forecasts

In [5]:
df =  Unifier.get_dataframe(name="xtech_futures_flow_forecasts_scenarios",  back_to='2025-11-18', limit=10)
display(df)

,asof_datetime,timestamp,identifier,active_delivery_month,is_continuous_roll_date,xt_group,scenario_type,scenario_label,shock_price,buy_contracts_sensitivity_1,buy_contracts_sensitivity_2,buy_contracts_sensitivity_3,buy_contracts_sensitivity_4,sell_contracts_sensitivity_1,sell_contracts_sensitivity_2,sell_contracts_sensitivity_3,sell_contracts_sensitivity_4,asof_date
0,2025-11-19 07:00:00.000,2025-11-18 00:00:00.000,6A,202512,False,managed_money,reference,ref_-5pct,0.6193,0,0,0,0,4907,5608,12285,15066,2025-11-19
1,2025-11-19 07:00:00.000,2025-11-18 00:00:00.000,6A,202512,False,managed_money,reference,ref_-4pct,0.6258,0,0,0,0,5513,6301,13801,16925,2025-11-19
2,2025-11-19 07:00:00.000,2025-11-18 00:00:00.000,6A,202512,False,managed_money,reference,ref_-3pct,0.6323,0,0,0,0,6221,7109,15572,19097,2025-11-19
3,2025-11-19 07:00:00.000,2025-11-18 00:00:00.000,6A,202512,False,managed_money,reference,ref_-2pct,0.6388,0,0,0,0,6958,7951,17417,21360,2025-11-19
4,2025-11-19 07:00:00.000,2025-11-18 00:00:00.000,6A,202512,False,managed_money,trigger,sell_trigger_3,0.6436,0,0,0,0,6485,7411,16234,19908,2025-11-19
5,2025-11-19 07:00:00.000,2025-11-18 00:00:00.000,6A,202512,False,managed_money,trigger,sell_trigger_3_pre,0.6437,0,0,0,0,6491,7417,16247,19926,2025-11-19
6,2025-11-19 07:00:00.000,2025-11-18 00:00:00.000,6A,202512,False,managed_money,trigger,sell_trigger_2,0.6441,0,0,0,0,3458,3952,8655,10615,2025-11-19
7,2025-11-19 07:00:00.000,2025-11-18 00:00:00.000,6A,202512,False,managed_money,trigger,sell_trigger_2_pre,0.6442,0,0,0,0,3458,3952,8658,10617,2025-11-19
8,2025-11-19 07:00:00.000,2025-11-18 00:00:00.000,6A,202512,False,managed_money,reference,ref_-1pct,0.6453,0,0,0,0,3464,3959,8671,10635,2025-11-19
9,2025-11-19 07:00:00.000,2025-11-18 00:00:00.000,6A,202512,False,managed_money,trigger,sell_trigger_1,0.6495,0,0,0,0,2327,2659,5823,7141,2025-11-19

In [6]:
df = Unifier.get_dataframe(name="xtech_futures_flow_forecasts_scenarios", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,asof_datetime,timestamp,identifier,active_delivery_month,is_continuous_roll_date,xt_group,scenario_type,scenario_label,shock_price,buy_contracts_sensitivity_1,buy_contracts_sensitivity_2,buy_contracts_sensitivity_3,buy_contracts_sensitivity_4,sell_contracts_sensitivity_1,sell_contracts_sensitivity_2,sell_contracts_sensitivity_3,sell_contracts_sensitivity_4,asof_date
0,2024-01-26 07:00:00.000,2024-01-25 00:00:00.000,6A,202403,False,managed_money,reference,ref_-5pct,0.62620,76,87,225,343,0,0,0,0,2024-01-26
1,2024-01-26 07:00:00.000,2024-01-25 00:00:00.000,6A,202403,False,managed_money,reference,ref_-4pct,0.63280,0,0,0,0,269,307,796,1211,2024-01-26
2,2024-01-26 07:00:00.000,2024-01-25 00:00:00.000,6A,202403,False,managed_money,trigger,sell_trigger_2,0.63390,0,0,0,0,114,130,336,512,2024-01-26
3,2024-01-26 07:00:00.000,2024-01-25 00:00:00.000,6A,202403,False,managed_money,trigger,sell_trigger_2_pre,0.63400,96,110,284,432,0,0,0,0,2024-01-26
4,2024-01-26 07:00:00.000,2024-01-25 00:00:00.000,6A,202403,False,managed_money,reference,ref_-3pct,0.63940,0,0,0,0,163,186,482,734,2024-01-26
5,2024-01-26 07:00:00.000,2024-01-25 00:00:00.000,6A,202403,False,managed_money,reference,ref_-2pct,0.64600,0,0,0,0,446,508,1318,2007,2024-01-26
6,2024-01-26 07:00:00.000,2024-01-25 00:00:00.000,6A,202403,False,managed_money,reference,ref_-1pct,0.65260,0,0,0,0,620,708,1833,2792,2024-01-26
7,2024-01-26 07:00:00.000,2024-01-25 00:00:00.000,6A,202403,False,managed_money,trigger,sell_trigger_1,0.65410,0,0,0,0,114,129,336,512,2024-01-26
8,2024-01-26 07:00:00.000,2024-01-25 00:00:00.000,6A,202403,False,managed_money,trigger,sell_trigger_1_pre,0.65420,0,0,0,0,115,130,337,514,2024-01-26
9,2024-01-26 07:00:00.000,2024-01-25 00:00:00.000,6A,202403,False,managed_money,current,current,0.65915,0,0,0,0,0,0,0,0,2024-01-26

In [8]:
df =  Unifier.get_dataframe(name="xtech_futures_flow_forecasts_scenarios", key="6A", back_to='2025-11-18', limit=10)
display(df)

,asof_datetime,timestamp,identifier,active_delivery_month,is_continuous_roll_date,xt_group,scenario_type,scenario_label,shock_price,buy_contracts_sensitivity_1,buy_contracts_sensitivity_2,buy_contracts_sensitivity_3,buy_contracts_sensitivity_4,sell_contracts_sensitivity_1,sell_contracts_sensitivity_2,sell_contracts_sensitivity_3,sell_contracts_sensitivity_4,asof_date
0,2025-11-19 07:00:00.000,2025-11-18 00:00:00.000,6A,202512,False,managed_money,reference,ref_-5pct,0.6193,0,0,0,0,4907,5608,12285,15066,2025-11-19
1,2025-11-19 07:00:00.000,2025-11-18 00:00:00.000,6A,202512,False,managed_money,reference,ref_-4pct,0.6258,0,0,0,0,5513,6301,13801,16925,2025-11-19
2,2025-11-19 07:00:00.000,2025-11-18 00:00:00.000,6A,202512,False,managed_money,reference,ref_-3pct,0.6323,0,0,0,0,6221,7109,15572,19097,2025-11-19
3,2025-11-19 07:00:00.000,2025-11-18 00:00:00.000,6A,202512,False,managed_money,reference,ref_-2pct,0.6388,0,0,0,0,6958,7951,17417,21360,2025-11-19
4,2025-11-19 07:00:00.000,2025-11-18 00:00:00.000,6A,202512,False,managed_money,trigger,sell_trigger_3,0.6436,0,0,0,0,6485,7411,16234,19908,2025-11-19
5,2025-11-19 07:00:00.000,2025-11-18 00:00:00.000,6A,202512,False,managed_money,trigger,sell_trigger_3_pre,0.6437,0,0,0,0,6491,7417,16247,19926,2025-11-19
6,2025-11-19 07:00:00.000,2025-11-18 00:00:00.000,6A,202512,False,managed_money,trigger,sell_trigger_2,0.6441,0,0,0,0,3458,3952,8655,10615,2025-11-19
7,2025-11-19 07:00:00.000,2025-11-18 00:00:00.000,6A,202512,False,managed_money,trigger,sell_trigger_2_pre,0.6442,0,0,0,0,3458,3952,8658,10617,2025-11-19
8,2025-11-19 07:00:00.000,2025-11-18 00:00:00.000,6A,202512,False,managed_money,reference,ref_-1pct,0.6453,0,0,0,0,3464,3959,8671,10635,2025-11-19
9,2025-11-19 07:00:00.000,2025-11-18 00:00:00.000,6A,202512,False,managed_money,trigger,sell_trigger_1,0.6495,0,0,0,0,2327,2659,5823,7141,2025-11-19