In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="kalshi_series_daily", asof_date='2026-10-19', limit=10)
display(df)

,series_ticker,title,category,categories,tags,frequency,fee_type,fee_multiplier,settlement_sources,additional_prohibitions,contract_url,contract_terms_url,volume,last_updated_ts,exchange_index,asof_datetime,asof_date
0,10Y2Y,Treasury spread 10Y-2Y,Financials,[Financials],[Treasuries],custom,quadratic,1,"[{""name"":""Federal Reserve Bank of St. Louis"",""...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/10Y2Y...,0.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19
1,10Y3M,Treasury spread 10Y-3M,Financials,[Financials],[Treasuries],custom,quadratic,1,"[{""name"":""Federal Reserve Bank of St. Louis"",""...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/10Y3M...,0.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19
2,1SONG-DRAKE,Drake top song,Entertainment,[Entertainment],"[Music, Music charts]",custom,quadratic,1,"[{""name"":""Billboard"",""url"":""https://www.billbo...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/1SONG...,0.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19
3,1SONG-KDOT,Kendrick top song,Entertainment,[Entertainment],"[Music, Music charts]",custom,quadratic,1,"[{""name"":""Billboard"",""url"":""https://www.billbo...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/1SONG...,0.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19
4,1SONGBILLIEEILISH,Billie EIlish top song,Entertainment,[Entertainment],"[Music, Music charts]",custom,quadratic,1,"[{""name"":""Billboard"",""url"":""https://www.billbo...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/1SONG...,0.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19
5,1SONGCHAPPELLROAN,Chappell Roan top song,Entertainment,[Entertainment],"[Music, Music charts]",custom,quadratic,1,"[{""name"":""Billboard"",""url"":""https://www.billbo...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/1SONG...,0.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19
6,1SONGMACKLEMORE,Macklemore top song,Entertainment,[Entertainment],"[Music, Music charts]",custom,quadratic,1,"[{""name"":""Billboard"",""url"":""https://www.billbo...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/1SONG...,0.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19
7,538APPROVE,President 538 approval rating this week,Politics,[Politics],"[Approval ratings, Biden]",weekly,quadratic,1,"[{""name"":""FiveThirtyEight"",""url"":""https://proj...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/538AP...,0.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19
8,538APPROVEMAX,Biden 538 highest approval rating,Politics,[Politics],"[Approval ratings, Biden]",custom,quadratic,1,"[{""name"":""FiveThirtyEight"",""url"":""https://proj...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/538AP...,0.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19
9,538APPROVEMIN,Biden 538 lowest approval rating,Politics,[Politics],"[Approval ratings, Biden]",custom,quadratic,1,"[{""name"":""FiveThirtyEight"",""url"":""https://proj...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/538AP...,0.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='kalshi_series_daily', back_to='2026-10-19', up_to='2026-10-21', limit=100)
display(df)

,series_ticker,title,category,categories,tags,frequency,fee_type,fee_multiplier,settlement_sources,additional_prohibitions,contract_url,contract_terms_url,volume,last_updated_ts,exchange_index,asof_datetime,asof_date
0,10Y2Y,Treasury spread 10Y-2Y,Financials,[Financials],[Treasuries],custom,quadratic,1,"[{""name"":""Federal Reserve Bank of St. Louis"",""...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/10Y2Y...,0.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19
1,10Y3M,Treasury spread 10Y-3M,Financials,[Financials],[Treasuries],custom,quadratic,1,"[{""name"":""Federal Reserve Bank of St. Louis"",""...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/10Y3M...,0.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19
2,1SONG-DRAKE,Drake top song,Entertainment,[Entertainment],"[Music, Music charts]",custom,quadratic,1,"[{""name"":""Billboard"",""url"":""https://www.billbo...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/1SONG...,0.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19
3,1SONG-KDOT,Kendrick top song,Entertainment,[Entertainment],"[Music, Music charts]",custom,quadratic,1,"[{""name"":""Billboard"",""url"":""https://www.billbo...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/1SONG...,0.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19
4,1SONGBILLIEEILISH,Billie EIlish top song,Entertainment,[Entertainment],"[Music, Music charts]",custom,quadratic,1,"[{""name"":""Billboard"",""url"":""https://www.billbo...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/1SONG...,0.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,BANKRUPTS,Companies going bankrupt,Economics,[Economics],[Bankruptcy & Defaults],monthly,quadratic,1,"[{""name"":""Standard & Poor's"",""url"":""https://di...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/BANKR...,0.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19
96,BANKRUPTSY,Companies going bankrupt yearly,Economics,[Economics],[Bankruptcy & Defaults],annual,quadratic,1,"[{""name"":""Standard & Poor's"",""url"":""https://di...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/BANKR...,0.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19
97,BARR,Barr confirmation as Fed Vice Chairman for Sup...,Politics,[Politics],[Confirmations],custom,quadratic,1,"[{""name"":""Library of Congress"",""url"":""https://...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/BARR.pdf,0.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19
98,BBB,HR 5376,Politics,[Politics],[Bills],custom,quadratic,1,"[{""name"":""Library of Congress"",""url"":""https://...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/BBB.pdf,0.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19
99,BEDOYA,Alvaro Bedoya FTC confirmation,Politics,[Politics],[Confirmations],custom,quadratic,1,"[{""name"":""Library of Congress"",""url"":""https://...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/BEDOY...,0.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19

## Retrieve data for a specific date with a specific series_ticker (key='series_ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='kalshi_series_daily',key='KXFED', asof_date='2026-10-19', limit=100)
display(df)

,series_ticker,title,category,categories,tags,frequency,fee_type,fee_multiplier,settlement_sources,additional_prohibitions,contract_url,contract_terms_url,volume,last_updated_ts,exchange_index,asof_datetime,asof_date
0,KXFED,Fed funds rate,Economics,[Economics],[Fed],custom,quadratic_with_maker_fees,1,"[{""name"":""Federal Reserve Board of Governors"",...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/FED.pdf,NaN,2026-08-29 22:27:15.072,0,2026-10-08 12:04:27.461,2026-10-08
1,KXFED,Fed funds rate,Economics,[Economics],[Fed],custom,quadratic_with_maker_fees,1,"[{""name"":""Federal Reserve Board of Governors"",...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/FED.pdf,60081271.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19

## Retrieve data for a specific date range with a specific series_ticker (key='series_ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='kalshi_series_daily',key='KXFED', back_to='2026-10-19', up_to='2026-10-21', limit=100)
display(df)

,series_ticker,title,category,categories,tags,frequency,fee_type,fee_multiplier,settlement_sources,additional_prohibitions,contract_url,contract_terms_url,volume,last_updated_ts,exchange_index,asof_datetime,asof_date
0,KXFED,Fed funds rate,Economics,[Economics],[Fed],custom,quadratic_with_maker_fees,1,"[{""name"":""Federal Reserve Board of Governors"",...",[Persons who are employed by any of the Source...,https://assets.kalshi.com/regulatory/product-c...,https://assets.kalshi.com/contract_terms/FED.pdf,60081271.00,2026-10-15 08:14:10.230,0,2026-10-19 10:33:29.384,2026-10-19

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="kalshi_series_daily", target_location="./data", asof_date='2026-10-19')

Downloading using native python implementation for kalshi_series_daily...
Found 1 files to download.
Native replication completed for kalshi_series_daily. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_series_daily", target_location="./data")