In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="kalshi_candles_1h", asof_date='2026-10-21', limit=10)
display(df)

,ticker,period_minutes,timestamp,date,yes_bid_open,yes_bid_high,yes_bid_low,yes_bid_close,yes_ask_open,yes_ask_high,...,price_high,price_low,price_close,price_mean,price_previous,volume,open_interest,source_tier,asof_datetime,asof_date
0,APPLEUS-29DEC31,60,2026-10-21 01:00:00.000,2026-10-21,0.2800,0.2800,0.2500,0.2700,0.3100,0.3100,...,0.2800,0.2800,0.2800,0.2800,0.3100,1.03,7614.21,live,2026-10-22 03:09:20.167,2026-10-21
1,APPLEUS-29DEC31,60,2026-10-21 02:00:00.000,2026-10-21,0.2700,0.2700,0.2600,0.2700,0.3100,0.3100,...,NaN,NaN,NaN,NaN,0.2800,0.00,7614.21,live,2026-10-22 03:09:20.167,2026-10-21
2,APPLEUS-29DEC31,60,2026-10-21 03:00:00.000,2026-10-21,0.2700,0.2700,0.2700,0.2700,0.3100,0.3100,...,NaN,NaN,NaN,NaN,0.2800,0.00,7614.21,live,2026-10-22 03:09:20.167,2026-10-21
3,APPLEUS-29DEC31,60,2026-10-21 04:00:00.000,2026-10-21,0.2700,0.2700,0.2700,0.2700,0.3100,0.3100,...,NaN,NaN,NaN,NaN,0.2800,0.00,7614.21,live,2026-10-22 03:09:20.167,2026-10-21
4,APPLEUS-29DEC31,60,2026-10-21 05:00:00.000,2026-10-21,0.2700,0.2700,0.2700,0.2700,0.3100,0.3100,...,NaN,NaN,NaN,NaN,0.2800,0.00,7614.21,live,2026-10-22 03:09:20.167,2026-10-21
5,APPLEUS-29DEC31,60,2026-10-21 06:00:00.000,2026-10-21,0.2700,0.2700,0.2700,0.2700,0.3100,0.3100,...,NaN,NaN,NaN,NaN,0.2800,0.00,7614.21,live,2026-10-22 03:09:20.167,2026-10-21
6,APPLEUS-29DEC31,60,2026-10-21 07:00:00.000,2026-10-21,0.2700,0.2700,0.2700,0.2700,0.3100,0.3100,...,NaN,NaN,NaN,NaN,0.2800,0.00,7614.21,live,2026-10-22 03:09:20.167,2026-10-21
7,APPLEUS-29DEC31,60,2026-10-21 08:00:00.000,2026-10-21,0.2700,0.2700,0.2700,0.2700,0.3100,0.3100,...,NaN,NaN,NaN,NaN,0.2800,0.00,7614.21,live,2026-10-22 03:09:20.167,2026-10-21
8,APPLEUS-29DEC31,60,2026-10-21 09:00:00.000,2026-10-21,0.2700,0.2700,0.2700,0.2700,0.3100,0.3100,...,NaN,NaN,NaN,NaN,0.2800,0.00,7614.21,live,2026-10-22 03:09:20.167,2026-10-21
9,APPLEUS-29DEC31,60,2026-10-21 10:00:00.000,2026-10-21,0.2700,0.2700,0.2700,0.2700,0.3000,0.3000,...,NaN,NaN,NaN,NaN,0.2800,0.00,7614.21,live,2026-10-22 03:09:20.167,2026-10-21

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='kalshi_candles_1h', back_to='2026-10-01', up_to='2026-10-21', limit=100)
display(df)

Empty DataFrame
Columns: []
Index: []

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='kalshi_candles_1h',key='KXFEDDECISION-26OCT-H0', asof_date='2026-10-21', limit=100)
display(df)

,ticker,period_minutes,timestamp,date,yes_bid_open,yes_bid_high,yes_bid_low,yes_bid_close,yes_ask_open,yes_ask_high,...,price_high,price_low,price_close,price_mean,price_previous,volume,open_interest,source_tier,asof_datetime,asof_date
0,KXFEDDECISION-26OCT-H0,60,2026-10-21 01:00:00.000,2026-10-21,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,0.8800,0.8700,0.8700,0.8795,0.8800,1504.41,2022086.05,live,2026-10-22 03:09:20.167,2026-10-21
1,KXFEDDECISION-26OCT-H0,60,2026-10-21 02:00:00.000,2026-10-21,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,0.8800,0.8700,0.8700,0.8723,0.8700,150.06,2022119.85,live,2026-10-22 03:09:20.167,2026-10-21
2,KXFEDDECISION-26OCT-H0,60,2026-10-21 03:00:00.000,2026-10-21,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,0.8800,0.8700,0.8800,0.8751,0.8700,220.13,2022267.35,live,2026-10-22 03:09:20.167,2026-10-21
3,KXFEDDECISION-26OCT-H0,60,2026-10-21 04:00:00.000,2026-10-21,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,0.8800,0.8700,0.8800,0.8800,0.8800,3080.79,2025347.01,live,2026-10-22 03:09:20.167,2026-10-21
4,KXFEDDECISION-26OCT-H0,60,2026-10-21 05:00:00.000,2026-10-21,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,0.8800,0.8700,0.8700,0.8766,0.8800,52.56,2025381.94,live,2026-10-22 03:09:20.167,2026-10-21
5,KXFEDDECISION-26OCT-H0,60,2026-10-21 06:00:00.000,2026-10-21,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,0.8800,0.8700,0.8800,0.8794,0.8700,18.04,2025398.83,live,2026-10-22 03:09:20.167,2026-10-21
6,KXFEDDECISION-26OCT-H0,60,2026-10-21 07:00:00.000,2026-10-21,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,0.8800,0.8700,0.8800,0.8800,0.8800,50463.14,2075547.06,live,2026-10-22 03:09:20.167,2026-10-21
7,KXFEDDECISION-26OCT-H0,60,2026-10-21 08:00:00.000,2026-10-21,0.8700,0.8800,0.8700,0.8700,0.8800,0.8900,...,0.8900,0.8700,0.8700,0.8777,0.8800,605.02,2075748.57,live,2026-10-22 03:09:20.167,2026-10-21
8,KXFEDDECISION-26OCT-H0,60,2026-10-21 09:00:00.000,2026-10-21,0.8700,0.8800,0.8700,0.8800,0.8900,0.8900,...,0.8900,0.8700,0.8700,0.8826,0.8700,188.34,2075799.41,live,2026-10-22 03:09:20.167,2026-10-21
9,KXFEDDECISION-26OCT-H0,60,2026-10-21 10:00:00.000,2026-10-21,0.8800,0.8800,0.8700,0.8800,0.8900,0.8900,...,0.8900,0.8700,0.8800,0.8866,0.8700,1456.15,2076756.38,live,2026-10-22 03:09:20.167,2026-10-21
10,KXFEDDECISION-26OCT-H0,60,2026-10-21 11:00:00.000,2026-10-21,0.8800,0.8800,0.8800,0.8800,0.8900,0.8900,...,0.8900,0.8800,0.8900,0.8849,0.8800,997.65,2077245.77,live,2026-10-22 03:09:20.167,2026-10-21
11,KXFEDDECISION-26OCT-H0,60,2026-10-21 12:00:00.000,2026-10-21,0.8800,0.8800,0.8800,0.8800,0.8900,0.8900,...,0.8900,0.8800,0.8800,0.8899,0.8900,29401.95,2105651.73,live,2026-10-22 03:09:20.167,2026-10-21
12,KXFEDDECISION-26OCT-H0,60,2026-10-21 13:00:00.000,2026-10-21,0.8800,0.8800,0.8800,0.8800,0.8900,0.8900,...,0.8900,0.8800,0.8800,0.8839,0.8800,2863.73,2106531.75,live,2026-10-22 03:09:20.167,2026-10-21
13,KXFEDDECISION-26OCT-H0,60,2026-10-21 14:00:00.000,2026-10-21,0.8800,0.8800,0.8800,0.8800,0.8900,0.8900,...,0.8900,0.8800,0.8900,0.8894,0.8800,7894.50,2108335.82,live,2026-10-22 03:09:20.167,2026-10-21
14,KXFEDDECISION-26OCT-H0,60,2026-10-21 15:00:00.000,2026-10-21,0.8800,0.8800,0.8800,0.8800,0.8900,0.8900,...,0.8900,0.8800,0.8900,0.8885,0.8900,12231.90,2114844.88,live,2026-10-22 03:09:20.167,2026-10-21
15,KXFEDDECISION-26OCT-H0,60,2026-10-21 16:00:00.000,2026-10-21,0.8800,0.8800,0.8700,0.8700,0.8900,0.8900,...,0.8900,0.8700,0.8700,0.8800,0.8900,44980.07,2154671.72,live,2026-10-22 03:09:20.167,2026-10-21
16,KXFEDDECISION-26OCT-H0,60,2026-10-21 17:00:00.000,2026-10-21,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,0.8800,0.8700,0.8800,0.8792,0.8700,913.52,2155508.05,live,2026-10-22 03:09:20.167,2026-10-21
17,KXFEDDECISION-26OCT-H0,60,2026-10-21 18:00:00.000,2026-10-21,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,0.8800,0.8700,0.8800,0.8726,0.8800,137.57,2155546.50,live,2026-10-22 03:09:20.167,2026-10-21
18,KXFEDDECISION-26OCT-H0,60,2026-10-21 19:00:00.000,2026-10-21,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,0.8800,0.8700,0.8800,0.8787,0.8800,18359.78,2165554.90,live,2026-10-22 03:09:20.167,2026-10-21
19,KXFEDDECISION-26OCT-H0,60,2026-10-21 20:00:00.000,2026-10-21,0.8700,0.8800,0.8700,0.8800,0.8800,0.8900,...,0.8900,0.8700,0.8800,0.8855,0.8800,35967.00,2188318.75,live,2026-10-22 03:09:20.167,2026-10-21
20,KXFEDDECISION-26OCT-H0,60,2026-10-21 21:00:00.000,2026-10-21,0.8800,0.8800,0.8800,0.8800,0.8900,0.8900,...,0.8900,0.8800,0.8800,0.8823,0.8800,1423.72,2189468.14,live,2026-10-22 03:09:20.167,2026-10-21
21,KXFEDDECISION-26OCT-H0,60,2026-10-21 22:00:00.000,2026-10-21,0.8800,0.8800,0.8800,0.8800,0.8900,0.8900,...,0.8900,0.8800,0.8900,0.8833,0.8800,1292.72,2190142.54,live,2026-10-22 03:09:20.167,2026-10-21
22,KXFEDDECISION-26OCT-H0,60,2026-10-21 23:00:00.000,2026-10-21,0.8800,0.8800,0.8800,0.8800,0.8900,0.8900,...,0.8900,0.8800,0.8900,0.8851,0.8900,375.62,2190332.92,live,2026-10-22 03:09:20.167,2026-10-21
23,KXFEDDECISION-26OCT-H0,60,2026-10-22 00:00:00.000,2026-10-22,0.8800,0.8800,0.8800,0.8800,0.8900,0.8900,...,0.8900,0.8800,0.8800,0.8880,0.8900,532.23,2190761.35,live,2026-10-22 03:09:20.167,2026-10-21

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [15]:
df = Unifier.get_dataframe(name='kalshi_candles_1h',key='KXFEDDECISION-26OCT-H0', back_to='2026-10-02', up_to='2026-10-22', limit=100)
display(df)

,ticker,period_minutes,timestamp,date,yes_bid_open,yes_bid_high,yes_bid_low,yes_bid_close,yes_ask_open,yes_ask_high,...,price_high,price_low,price_close,price_mean,price_previous,volume,open_interest,source_tier,asof_datetime,asof_date
0,KXFEDDECISION-26OCT-H0,60,2026-10-21 01:00:00.000,2026-10-21,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,0.8800,0.8700,0.8700,0.8795,0.8800,1504.41,2022086.05,live,2026-10-22 03:09:20.167,2026-10-21
1,KXFEDDECISION-26OCT-H0,60,2026-10-21 02:00:00.000,2026-10-21,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,0.8800,0.8700,0.8700,0.8723,0.8700,150.06,2022119.85,live,2026-10-22 03:09:20.167,2026-10-21
2,KXFEDDECISION-26OCT-H0,60,2026-10-21 03:00:00.000,2026-10-21,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,0.8800,0.8700,0.8800,0.8751,0.8700,220.13,2022267.35,live,2026-10-22 03:09:20.167,2026-10-21
3,KXFEDDECISION-26OCT-H0,60,2026-10-21 04:00:00.000,2026-10-21,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,0.8800,0.8700,0.8800,0.8800,0.8800,3080.79,2025347.01,live,2026-10-22 03:09:20.167,2026-10-21
4,KXFEDDECISION-26OCT-H0,60,2026-10-21 05:00:00.000,2026-10-21,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,0.8800,0.8700,0.8700,0.8766,0.8800,52.56,2025381.94,live,2026-10-22 03:09:20.167,2026-10-21
5,KXFEDDECISION-26OCT-H0,60,2026-10-21 06:00:00.000,2026-10-21,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,0.8800,0.8700,0.8800,0.8794,0.8700,18.04,2025398.83,live,2026-10-22 03:09:20.167,2026-10-21
6,KXFEDDECISION-26OCT-H0,60,2026-10-21 07:00:00.000,2026-10-21,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,0.8800,0.8700,0.8800,0.8800,0.8800,50463.14,2075547.06,live,2026-10-22 03:09:20.167,2026-10-21
7,KXFEDDECISION-26OCT-H0,60,2026-10-21 08:00:00.000,2026-10-21,0.8700,0.8800,0.8700,0.8700,0.8800,0.8900,...,0.8900,0.8700,0.8700,0.8777,0.8800,605.02,2075748.57,live,2026-10-22 03:09:20.167,2026-10-21
8,KXFEDDECISION-26OCT-H0,60,2026-10-21 09:00:00.000,2026-10-21,0.8700,0.8800,0.8700,0.8800,0.8900,0.8900,...,0.8900,0.8700,0.8700,0.8826,0.8700,188.34,2075799.41,live,2026-10-22 03:09:20.167,2026-10-21
9,KXFEDDECISION-26OCT-H0,60,2026-10-21 10:00:00.000,2026-10-21,0.8800,0.8800,0.8700,0.8800,0.8900,0.8900,...,0.8900,0.8700,0.8800,0.8866,0.8700,1456.15,2076756.38,live,2026-10-22 03:09:20.167,2026-10-21
10,KXFEDDECISION-26OCT-H0,60,2026-10-21 11:00:00.000,2026-10-21,0.8800,0.8800,0.8800,0.8800,0.8900,0.8900,...,0.8900,0.8800,0.8900,0.8849,0.8800,997.65,2077245.77,live,2026-10-22 03:09:20.167,2026-10-21
11,KXFEDDECISION-26OCT-H0,60,2026-10-21 12:00:00.000,2026-10-21,0.8800,0.8800,0.8800,0.8800,0.8900,0.8900,...,0.8900,0.8800,0.8800,0.8899,0.8900,29401.95,2105651.73,live,2026-10-22 03:09:20.167,2026-10-21
12,KXFEDDECISION-26OCT-H0,60,2026-10-21 13:00:00.000,2026-10-21,0.8800,0.8800,0.8800,0.8800,0.8900,0.8900,...,0.8900,0.8800,0.8800,0.8839,0.8800,2863.73,2106531.75,live,2026-10-22 03:09:20.167,2026-10-21
13,KXFEDDECISION-26OCT-H0,60,2026-10-21 14:00:00.000,2026-10-21,0.8800,0.8800,0.8800,0.8800,0.8900,0.8900,...,0.8900,0.8800,0.8900,0.8894,0.8800,7894.50,2108335.82,live,2026-10-22 03:09:20.167,2026-10-21
14,KXFEDDECISION-26OCT-H0,60,2026-10-21 15:00:00.000,2026-10-21,0.8800,0.8800,0.8800,0.8800,0.8900,0.8900,...,0.8900,0.8800,0.8900,0.8885,0.8900,12231.90,2114844.88,live,2026-10-22 03:09:20.167,2026-10-21
15,KXFEDDECISION-26OCT-H0,60,2026-10-21 16:00:00.000,2026-10-21,0.8800,0.8800,0.8700,0.8700,0.8900,0.8900,...,0.8900,0.8700,0.8700,0.8800,0.8900,44980.07,2154671.72,live,2026-10-22 03:09:20.167,2026-10-21
16,KXFEDDECISION-26OCT-H0,60,2026-10-21 17:00:00.000,2026-10-21,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,0.8800,0.8700,0.8800,0.8792,0.8700,913.52,2155508.05,live,2026-10-22 03:09:20.167,2026-10-21
17,KXFEDDECISION-26OCT-H0,60,2026-10-21 18:00:00.000,2026-10-21,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,0.8800,0.8700,0.8800,0.8726,0.8800,137.57,2155546.50,live,2026-10-22 03:09:20.167,2026-10-21
18,KXFEDDECISION-26OCT-H0,60,2026-10-21 19:00:00.000,2026-10-21,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,0.8800,0.8700,0.8800,0.8787,0.8800,18359.78,2165554.90,live,2026-10-22 03:09:20.167,2026-10-21
19,KXFEDDECISION-26OCT-H0,60,2026-10-21 20:00:00.000,2026-10-21,0.8700,0.8800,0.8700,0.8800,0.8800,0.8900,...,0.8900,0.8700,0.8800,0.8855,0.8800,35967.00,2188318.75,live,2026-10-22 03:09:20.167,2026-10-21
20,KXFEDDECISION-26OCT-H0,60,2026-10-21 21:00:00.000,2026-10-21,0.8800,0.8800,0.8800,0.8800,0.8900,0.8900,...,0.8900,0.8800,0.8800,0.8823,0.8800,1423.72,2189468.14,live,2026-10-22 03:09:20.167,2026-10-21
21,KXFEDDECISION-26OCT-H0,60,2026-10-21 22:00:00.000,2026-10-21,0.8800,0.8800,0.8800,0.8800,0.8900,0.8900,...,0.8900,0.8800,0.8900,0.8833,0.8800,1292.72,2190142.54,live,2026-10-22 03:09:20.167,2026-10-21
22,KXFEDDECISION-26OCT-H0,60,2026-10-21 23:00:00.000,2026-10-21,0.8800,0.8800,0.8800,0.8800,0.8900,0.8900,...,0.8900,0.8800,0.8900,0.8851,0.8900,375.62,2190332.92,live,2026-10-22 03:09:20.167,2026-10-21
23,KXFEDDECISION-26OCT-H0,60,2026-10-22 00:00:00.000,2026-10-22,0.8800,0.8800,0.8800,0.8800,0.8900,0.8900,...,0.8900,0.8800,0.8800,0.8880,0.8900,532.23,2190761.35,live,2026-10-22 03:09:20.167,2026-10-21

## Download data file for a specific date using asof_date

In [13]:
Unifier.replicate(name="kalshi_candles_1h", target_location="./data", asof_date='2026-10-21')

Downloading using native python implementation for kalshi_candles_1h...
Found 1 files to download.
Native replication completed for kalshi_candles_1h. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_candles_1h", target_location="./data")