In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="kalshi_orderbook_snapshots", asof_date='2026-10-24', limit=10)
display(df)

,ticker,event_ticker,series_ticker,yes_bid,yes_bid_size,yes_ask,yes_ask_size,no_bid,no_bid_size,no_ask,...,spread,yes_levels,no_levels,yes_depth,no_depth,yes_depth_notional,no_depth_notional,is_empty,asof_datetime,asof_date
0,AMAZONFTC-29DEC31,AMAZONFTC-29DEC31,AMAZONFTC,0.4700,5.00,0.5000,200.00,0.5000,200.00,0.5300,...,0.0300,30,24,39328.71,42294.40,802.0354,1237.8592,False,2026-10-23 04:26:58.081,2026-10-23
1,APPLEUS-29DEC31,APPLEUS,APPLEUS,0.2800,2.00,0.3200,228.24,0.6800,228.24,0.7200,...,0.0400,13,13,11234.51,8994.59,397.4010,572.7961,False,2026-10-23 04:26:58.081,2026-10-23
2,BEYONCEGENRE-30-AFA,BEYONCEGENRE-30,BEYONCEGENRE,0.2100,3.00,0.2900,200.00,0.7100,200.00,0.7900,...,0.0800,6,5,1783.00,1979.00,96.0500,294.6400,False,2026-10-23 04:26:58.081,2026-10-23
3,BEYONCEGENRE-30-DEA,BEYONCEGENRE-30,BEYONCEGENRE,0.0600,200.00,0.1500,200.00,0.8500,200.00,0.9400,...,0.0900,1,10,200.00,17830.00,12.0000,1409.2000,False,2026-10-23 04:26:58.081,2026-10-23
4,BEYONCEGENRE-30-RA,BEYONCEGENRE-30,BEYONCEGENRE,0.1300,200.00,0.2200,200.00,0.7800,200.00,0.8700,...,0.0900,1,5,200.00,1175.00,26.0000,271.6000,False,2026-10-23 04:26:58.081,2026-10-23
5,BEYONCEGENRE-30-TAA,BEYONCEGENRE-30,BEYONCEGENRE,0.1300,5.50,0.2100,200.00,0.7900,200.00,0.8700,...,0.0800,2,9,205.50,2322.00,24.7150,624.7500,False,2026-10-23 04:26:58.081,2026-10-23
6,BEYONCEGENRE-30-TCA,BEYONCEGENRE-30,BEYONCEGENRE,0.0800,200.00,0.1700,200.00,0.8300,200.00,0.9200,...,0.0900,1,9,200.00,1762.00,16.0000,516.0200,False,2026-10-23 04:26:58.081,2026-10-23
7,BEYONCEGENRE-30-TGA,BEYONCEGENRE-30,BEYONCEGENRE,0.1700,10.00,0.2500,200.00,0.7500,200.00,0.8300,...,0.0800,5,5,1330.00,1675.00,91.1000,291.5000,False,2026-10-23 04:26:58.081,2026-10-23
8,BEYONCEGENRE-30-THA,BEYONCEGENRE-30,BEYONCEGENRE,0.0300,200.00,0.1100,200.00,0.8900,200.00,0.9700,...,0.0800,2,12,450.00,17469.00,11.0000,1387.4700,False,2026-10-23 04:26:58.081,2026-10-23
9,BEYONCEGENRE-30-TRA,BEYONCEGENRE-30,BEYONCEGENRE,0.6200,5.06,0.6700,5.35,0.3300,5.35,0.3800,...,0.0500,11,13,2094.03,2141.30,269.8359,174.0561,False,2026-10-23 04:26:58.081,2026-10-23

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='kalshi_orderbook_snapshots', back_to='2026-10-22', up_to='2026-10-24', limit=10)
display(df)

,ticker,event_ticker,series_ticker,yes_bid,yes_bid_size,yes_ask,yes_ask_size,no_bid,no_bid_size,no_ask,...,spread,yes_levels,no_levels,yes_depth,no_depth,yes_depth_notional,no_depth_notional,is_empty,asof_datetime,asof_date
0,AMAZONFTC-29DEC31,AMAZONFTC-29DEC31,AMAZONFTC,0.4700,5.00,0.5000,200.00,0.5000,200.00,0.5300,...,0.0300,30,24,39328.71,42294.40,802.0354,1237.8592,False,2026-10-23 04:26:58.081,2026-10-23
1,APPLEUS-29DEC31,APPLEUS,APPLEUS,0.2800,2.00,0.3200,228.24,0.6800,228.24,0.7200,...,0.0400,13,13,11234.51,8994.59,397.4010,572.7961,False,2026-10-23 04:26:58.081,2026-10-23
2,BEYONCEGENRE-30-AFA,BEYONCEGENRE-30,BEYONCEGENRE,0.2100,3.00,0.2900,200.00,0.7100,200.00,0.7900,...,0.0800,6,5,1783.00,1979.00,96.0500,294.6400,False,2026-10-23 04:26:58.081,2026-10-23
3,BEYONCEGENRE-30-DEA,BEYONCEGENRE-30,BEYONCEGENRE,0.0600,200.00,0.1500,200.00,0.8500,200.00,0.9400,...,0.0900,1,10,200.00,17830.00,12.0000,1409.2000,False,2026-10-23 04:26:58.081,2026-10-23
4,BEYONCEGENRE-30-RA,BEYONCEGENRE-30,BEYONCEGENRE,0.1300,200.00,0.2200,200.00,0.7800,200.00,0.8700,...,0.0900,1,5,200.00,1175.00,26.0000,271.6000,False,2026-10-23 04:26:58.081,2026-10-23
5,BEYONCEGENRE-30-TAA,BEYONCEGENRE-30,BEYONCEGENRE,0.1300,5.50,0.2100,200.00,0.7900,200.00,0.8700,...,0.0800,2,9,205.50,2322.00,24.7150,624.7500,False,2026-10-23 04:26:58.081,2026-10-23
6,BEYONCEGENRE-30-TCA,BEYONCEGENRE-30,BEYONCEGENRE,0.0800,200.00,0.1700,200.00,0.8300,200.00,0.9200,...,0.0900,1,9,200.00,1762.00,16.0000,516.0200,False,2026-10-23 04:26:58.081,2026-10-23
7,BEYONCEGENRE-30-TGA,BEYONCEGENRE-30,BEYONCEGENRE,0.1700,10.00,0.2500,200.00,0.7500,200.00,0.8300,...,0.0800,5,5,1330.00,1675.00,91.1000,291.5000,False,2026-10-23 04:26:58.081,2026-10-23
8,BEYONCEGENRE-30-THA,BEYONCEGENRE-30,BEYONCEGENRE,0.0300,200.00,0.1100,200.00,0.8900,200.00,0.9700,...,0.0800,2,12,450.00,17469.00,11.0000,1387.4700,False,2026-10-23 04:26:58.081,2026-10-23
9,BEYONCEGENRE-30-TRA,BEYONCEGENRE-30,BEYONCEGENRE,0.6200,5.06,0.6700,5.35,0.3300,5.35,0.3800,...,0.0500,11,13,2094.03,2141.30,269.8359,174.0561,False,2026-10-23 04:26:58.081,2026-10-23

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='kalshi_orderbook_snapshots',key='KXFEDDECISION-26OCT-H0', asof_date='2026-10-24', limit=10)
display(df)

,ticker,event_ticker,series_ticker,yes_bid,yes_bid_size,yes_ask,yes_ask_size,no_bid,no_bid_size,no_ask,...,spread,yes_levels,no_levels,yes_depth,no_depth,yes_depth_notional,no_depth_notional,is_empty,asof_datetime,asof_date
0,KXFEDDECISION-26OCT-H0,KXFEDDECISION-26OCT,KXFEDDECISION,0.9300,136465.25,0.9400,764287.11,0.0600,764287.11,0.0700,...,0.0100,61,6,1472499.81,5685999.12,396998.2326,167868.0516,False,2026-10-23 04:26:58.081,2026-10-23

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='kalshi_orderbook_snapshots',key='KXFEDDECISION-26OCT-H0', back_to='2026-10-22', up_to='2026-10-24', limit=10)
display(df)

,ticker,event_ticker,series_ticker,yes_bid,yes_bid_size,yes_ask,yes_ask_size,no_bid,no_bid_size,no_ask,...,spread,yes_levels,no_levels,yes_depth,no_depth,yes_depth_notional,no_depth_notional,is_empty,asof_datetime,asof_date
0,KXFEDDECISION-26OCT-H0,KXFEDDECISION-26OCT,KXFEDDECISION,0.9300,136465.25,0.9400,764287.11,0.0600,764287.11,0.0700,...,0.0100,61,6,1472499.81,5685999.12,396998.2326,167868.0516,False,2026-10-23 04:26:58.081,2026-10-23

## Download data file for a specific date using asof_date

In [9]:
Unifier.replicate(name="kalshi_orderbook_snapshots", target_location="./data", asof_date='2026-10-23')

Downloading using native python implementation for kalshi_orderbook_snapshots...
Found 1 files to download.
Native replication completed for kalshi_orderbook_snapshots. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_orderbook_snapshots", target_location="./data")