In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="kalshi_markets_daily", asof_date='2026-10-19', limit=10)
display(df)

,ticker,event_ticker,series_ticker,market_type,title,yes_sub_title,no_sub_title,status,result,created_time,...,rules_secondary,price_level_structure,yes_bid_size,yes_ask_size,updated_time,expected_expiration_time,expiration_value,settlement_timer_seconds,asof_datetime,asof_date
0,CONTROLH-2028-R,CONTROLH-2028,CONTROLH,binary,Will the Republican party win the House in 2028?,Republican party,Republican party,active,None,2026-05-15 18:09:17.488,...,This market may be determined early based on a...,linear_cent,4695.04,2514.71,2026-10-10 09:24:14.973,2029-02-01 15:00:00.000,None,3600,2026-10-19 10:33:32.802,2026-10-19
1,CONTROLS-2028-R,CONTROLS-2028,CONTROLS,binary,Will the Republican party win the Senate in 2028?,Republican party,Republican party,active,None,2026-05-15 18:04:16.707,...,This market may be determined early based on a...,linear_cent,2169.34,6348.59,2026-10-10 09:24:32.173,2029-02-01 15:00:00.000,None,3600,2026-10-19 10:33:32.802,2026-10-19
2,ECMOV-28NOV07-DEM31T60,ECMOV-28NOV07,ECMOV,binary,Will the Democratic candidate win the 2028 pre...,Democratic by 31 to 60,Democratic by 31 to 60,active,None,2026-05-14 18:17:12.275,...,NaN,linear_cent,8946.00,3019.00,2026-10-14 16:30:59.746,2029-01-08 15:00:00.000,None,14,2026-10-19 10:33:32.802,2026-10-19
3,ECMOV-28NOV07-DEM91T130,ECMOV-28NOV07,ECMOV,binary,Will the Democratic candidate win the 2028 pre...,Democratic by 91 to 130,Democratic by 91 to 130,active,None,2026-05-14 18:17:12.275,...,NaN,linear_cent,7723.00,4366.00,2026-10-14 16:30:59.746,2029-01-08 15:00:00.000,None,14,2026-10-19 10:33:32.802,2026-10-19
4,ECMOV-28NOV07-DEM11T30,ECMOV-28NOV07,ECMOV,binary,Will the Democratic candidate win the 2028 pre...,Democratic by 11 to 30,Democratic by 11 to 30,active,None,2026-05-14 18:17:12.275,...,NaN,linear_cent,12971.00,3049.00,2026-10-14 16:30:59.746,2029-01-08 15:00:00.000,None,14,2026-10-19 10:33:32.802,2026-10-19
5,ECMOV-28NOV07-REP211T538,ECMOV-28NOV07,ECMOV,binary,Will the Republican candidate win the 2028 pre...,Republican by 211 or more,Republican by 211 or more,active,None,2026-05-14 18:17:12.275,...,NaN,linear_cent,25826.00,2823.00,2026-10-14 16:30:59.746,2029-01-08 15:00:00.000,None,14,2026-10-19 10:33:32.802,2026-10-19
6,ECMOV-28NOV07-REP61T90,ECMOV-28NOV07,ECMOV,binary,Will the Republican candidate win the 2028 pre...,Republican by 61 to 90,Republican by 61 to 90,active,None,2026-05-14 18:17:12.275,...,NaN,linear_cent,8255.00,3354.00,2026-10-14 16:30:59.746,2029-01-08 15:00:00.000,None,14,2026-10-19 10:33:32.802,2026-10-19
7,ECMOV-28NOV07-REP131T210,ECMOV-28NOV07,ECMOV,binary,Will the Republican candidate win the 2028 pre...,Republican by 131 to 210,Republican by 131 to 210,active,None,2026-05-14 18:17:12.275,...,NaN,linear_cent,23171.00,2731.00,2026-10-14 16:30:59.746,2029-01-08 15:00:00.000,None,14,2026-10-19 10:33:32.802,2026-10-19
8,ECMOV-28NOV07-DEM1T10,ECMOV-28NOV07,ECMOV,binary,Will the Democratic candidate win the 2028 pre...,Democratic by 1 to 10,Democratic by 1 to 10,active,None,2026-05-14 18:17:12.275,...,NaN,linear_cent,18626.00,3426.00,2026-10-14 16:30:59.746,2029-01-08 15:00:00.000,None,14,2026-10-19 10:33:32.802,2026-10-19
9,GOVPARTYRI-26-KBLO,GOVPARTYRI-26,GOVPARTYRI,binary,Will Ken Block (Independent) win the governors...,Ken Block,Ken Block,active,None,2026-04-20 19:04:46.321,...,This market is eligible for accelerated determ...,linear_cent,29.64,2807.00,2026-10-15 17:13:26.514,2027-01-06 15:00:00.000,None,14,2026-10-19 10:33:32.802,2026-10-19

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='kalshi_markets_daily', back_to='2026-10-19', up_to='2026-10-21', limit=100)
display(df)

,ticker,event_ticker,series_ticker,market_type,title,yes_sub_title,no_sub_title,status,result,created_time,...,rules_secondary,price_level_structure,yes_bid_size,yes_ask_size,updated_time,expected_expiration_time,expiration_value,settlement_timer_seconds,asof_datetime,asof_date
0,CONTROLH-2028-R,CONTROLH-2028,CONTROLH,binary,Will the Republican party win the House in 2028?,Republican party,Republican party,active,None,2026-05-15 18:09:17.488,...,This market may be determined early based on a...,linear_cent,4695.04,2514.71,2026-10-10 09:24:14.973,2029-02-01 15:00:00.000,None,3600,2026-10-19 10:33:32.802,2026-10-19
1,CONTROLS-2028-R,CONTROLS-2028,CONTROLS,binary,Will the Republican party win the Senate in 2028?,Republican party,Republican party,active,None,2026-05-15 18:04:16.707,...,This market may be determined early based on a...,linear_cent,2169.34,6348.59,2026-10-10 09:24:32.173,2029-02-01 15:00:00.000,None,3600,2026-10-19 10:33:32.802,2026-10-19
2,ECMOV-28NOV07-DEM31T60,ECMOV-28NOV07,ECMOV,binary,Will the Democratic candidate win the 2028 pre...,Democratic by 31 to 60,Democratic by 31 to 60,active,None,2026-05-14 18:17:12.275,...,NaN,linear_cent,8946.00,3019.00,2026-10-14 16:30:59.746,2029-01-08 15:00:00.000,None,14,2026-10-19 10:33:32.802,2026-10-19
3,ECMOV-28NOV07-DEM91T130,ECMOV-28NOV07,ECMOV,binary,Will the Democratic candidate win the 2028 pre...,Democratic by 91 to 130,Democratic by 91 to 130,active,None,2026-05-14 18:17:12.275,...,NaN,linear_cent,7723.00,4366.00,2026-10-14 16:30:59.746,2029-01-08 15:00:00.000,None,14,2026-10-19 10:33:32.802,2026-10-19
4,ECMOV-28NOV07-DEM11T30,ECMOV-28NOV07,ECMOV,binary,Will the Democratic candidate win the 2028 pre...,Democratic by 11 to 30,Democratic by 11 to 30,active,None,2026-05-14 18:17:12.275,...,NaN,linear_cent,12971.00,3049.00,2026-10-14 16:30:59.746,2029-01-08 15:00:00.000,None,14,2026-10-19 10:33:32.802,2026-10-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,INXI-25FEB12H1300-T5890,INXI-25FEB12H1300,INXI,binary,Will the value of the S&P 500 be at least 5890...,5890.00 or above,5890.00 or above,closed,None,2025-02-12 06:17:03.698,...,"The market will close on Feb 12, 2025 at 1pm E...",linear_cent,0.00,0.00,2026-04-09 09:31:02.574,2025-02-12 18:00:00.000,None,300,2026-10-19 10:33:32.802,2026-10-19
96,INXI-25FEB12H1300-T5880,INXI-25FEB12H1300,INXI,binary,Will the value of the S&P 500 be at least 5880...,5880.00 or above,5880.00 or above,closed,None,2025-02-12 06:17:03.698,...,"The market will close on Feb 12, 2025 at 1pm E...",linear_cent,0.00,0.00,2026-04-09 09:31:02.324,2025-02-12 18:00:00.000,None,300,2026-10-19 10:33:32.802,2026-10-19
97,INXI-25FEB12H1300-T5870,INXI-25FEB12H1300,INXI,binary,Will the value of the S&P 500 be at least 5870...,5870.00 or above,5870.00 or above,closed,None,2025-02-12 06:17:03.698,...,"The market will close on Feb 12, 2025 at 1pm E...",linear_cent,0.00,0.00,2026-04-09 09:31:02.117,2025-02-12 18:00:00.000,None,300,2026-10-19 10:33:32.802,2026-10-19
98,INXI-25FEB12H1200-T6260,INXI-25FEB12H1200,INXI,binary,Will the value of the S&P 500 be at least 6260...,6260.00 or above,6260.00 or above,closed,None,2025-02-12 06:17:00.356,...,"The market will close on Feb 12, 2025 at 12pm ...",linear_cent,0.00,0.00,2026-04-09 09:30:32.767,2025-02-12 17:00:00.000,None,300,2026-10-19 10:33:32.802,2026-10-19
99,INXI-25FEB12H1300-T6240,INXI-25FEB12H1300,INXI,binary,Will the value of the S&P 500 be at least 6240...,6240.00 or above,6240.00 or above,closed,None,2025-02-12 06:17:03.698,...,"The market will close on Feb 12, 2025 at 1pm E...",linear_cent,0.00,0.00,2026-04-09 09:31:10.124,2025-02-12 18:00:00.000,None,300,2026-10-19 10:33:32.802,2026-10-19

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='kalshi_markets_daily',key='KXFED-26DEC-T4.50', asof_date='2026-10-19', limit=100)
display(df)

,ticker,event_ticker,series_ticker,market_type,title,yes_sub_title,no_sub_title,status,result,created_time,...,rules_secondary,price_level_structure,yes_bid_size,yes_ask_size,updated_time,expected_expiration_time,expiration_value,settlement_timer_seconds,asof_datetime,asof_date
0,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,binary,Will the upper bound of the federal funds rate...,Above 4.50%,Above 4.50%,active,None,2025-08-06 14:29:24.100,...,This market will expire the first 2:05 PM ET f...,linear_cent,10.75,23.00,2026-09-30 19:07:31.672,2026-12-09 19:05:00.000,None,300.0,2026-10-19 10:33:32.802,2026-10-19
1,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,binary,Will the upper bound of the federal funds rate...,Above 4.50%,Above 4.50%,active,None,2025-08-06 14:29:24.100,...,This market will expire the first 2:05 PM ET f...,"""linear_cent""",NaN,NaN,NaN,NaN,None,NaN,2026-10-08 12:04:46.754,2026-10-08

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='kalshi_markets_daily',key='KXFED-26DEC-T4.50', back_to='2026-10-19', up_to='2026-10-21', limit=100)
display(df)

,ticker,event_ticker,series_ticker,market_type,title,yes_sub_title,no_sub_title,status,result,created_time,...,rules_secondary,price_level_structure,yes_bid_size,yes_ask_size,updated_time,expected_expiration_time,expiration_value,settlement_timer_seconds,asof_datetime,asof_date
0,KXFED-26DEC-T4.50,KXFED-26DEC,KXFED,binary,Will the upper bound of the federal funds rate...,Above 4.50%,Above 4.50%,active,None,2025-08-06 14:29:24.100,...,This market will expire the first 2:05 PM ET f...,linear_cent,10.75,23.00,2026-09-30 19:07:31.672,2026-12-09 19:05:00.000,None,300,2026-10-19 10:33:32.802,2026-10-19

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="kalshi_markets_daily", target_location="./data", asof_date='2026-10-19')

Downloading using native python implementation for kalshi_markets_daily...
Found 1 files to download.
Native replication completed for kalshi_markets_daily. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_markets_daily", target_location="./data")