In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [5]:
df = Unifier.get_dataframe(name="kalshi_orderbook_levels", asof_date='2026-10-23', limit=10)
display(df)

,ticker,event_ticker,series_ticker,side,level,price,quantity,cum_quantity,implied_ask,asof_datetime,asof_date
0,BEYONCEGENRE-30-DEA,BEYONCEGENRE-30,BEYONCEGENRE,no,1,0.8500,200.00,200.00,0.1500,2026-10-23 04:26:58.081,2026-10-23
1,BEYONCEGENRE-30-DEA,BEYONCEGENRE-30,BEYONCEGENRE,no,2,0.4700,734.00,934.00,0.5300,2026-10-23 04:26:58.081,2026-10-23
2,BEYONCEGENRE-30-DEA,BEYONCEGENRE-30,BEYONCEGENRE,no,3,0.4600,954.00,1888.00,0.5400,2026-10-23 04:26:58.081,2026-10-23
3,BEYONCEGENRE-30-DEA,BEYONCEGENRE-30,BEYONCEGENRE,no,4,0.4400,1.00,1889.00,0.5600,2026-10-23 04:26:58.081,2026-10-23
4,BEYONCEGENRE-30-DEA,BEYONCEGENRE-30,BEYONCEGENRE,no,5,0.3600,230.00,2119.00,0.6400,2026-10-23 04:26:58.081,2026-10-23
5,BEYONCEGENRE-30-DEA,BEYONCEGENRE-30,BEYONCEGENRE,no,6,0.1400,481.00,2600.00,0.8600,2026-10-23 04:26:58.081,2026-10-23
6,BEYONCEGENRE-30-DEA,BEYONCEGENRE-30,BEYONCEGENRE,no,7,0.0400,100.00,2700.00,0.9600,2026-10-23 04:26:58.081,2026-10-23
7,BEYONCEGENRE-30-DEA,BEYONCEGENRE-30,BEYONCEGENRE,no,8,0.0300,4370.00,7070.00,0.9700,2026-10-23 04:26:58.081,2026-10-23
8,BEYONCEGENRE-30-DEA,BEYONCEGENRE-30,BEYONCEGENRE,no,9,0.0200,6210.00,13280.00,0.9800,2026-10-23 04:26:58.081,2026-10-23
9,BEYONCEGENRE-30-DEA,BEYONCEGENRE-30,BEYONCEGENRE,no,10,0.0100,4550.00,17830.00,0.9900,2026-10-23 04:26:58.081,2026-10-23

## Retrieve data for a specific date range using the back_to and up_to parameters

In [10]:
df = Unifier.get_dataframe(name='kalshi_orderbook_levels', back_to='2026-10-22', up_to='2026-10-24', limit=10)
display(df)

,ticker,event_ticker,series_ticker,side,level,price,quantity,cum_quantity,implied_ask,asof_datetime,asof_date
0,BEYONCEGENRE-30-THA,BEYONCEGENRE-30,BEYONCEGENRE,no,1,0.8900,200.00,200.00,0.1100,2026-10-23 04:26:58.081,2026-10-23
1,BEYONCEGENRE-30-THA,BEYONCEGENRE-30,BEYONCEGENRE,no,2,0.7000,1.00,201.00,0.3000,2026-10-23 04:26:58.081,2026-10-23
2,BEYONCEGENRE-30-THA,BEYONCEGENRE-30,BEYONCEGENRE,no,3,0.4500,273.00,474.00,0.5500,2026-10-23 04:26:58.081,2026-10-23
3,BEYONCEGENRE-30-THA,BEYONCEGENRE-30,BEYONCEGENRE,no,4,0.4200,536.00,1010.00,0.5800,2026-10-23 04:26:58.081,2026-10-23
4,BEYONCEGENRE-30-THA,BEYONCEGENRE-30,BEYONCEGENRE,no,5,0.4100,1052.00,2062.00,0.5900,2026-10-23 04:26:58.081,2026-10-23
5,BEYONCEGENRE-30-THA,BEYONCEGENRE-30,BEYONCEGENRE,no,6,0.4000,106.00,2168.00,0.6000,2026-10-23 04:26:58.081,2026-10-23
6,BEYONCEGENRE-30-THA,BEYONCEGENRE-30,BEYONCEGENRE,no,7,0.3800,1.00,2169.00,0.6200,2026-10-23 04:26:58.081,2026-10-23
7,BEYONCEGENRE-30-THA,BEYONCEGENRE-30,BEYONCEGENRE,no,8,0.1600,100.00,2269.00,0.8400,2026-10-23 04:26:58.081,2026-10-23
8,BEYONCEGENRE-30-THA,BEYONCEGENRE-30,BEYONCEGENRE,no,9,0.1500,520.00,2789.00,0.8500,2026-10-23 04:26:58.081,2026-10-23
9,BEYONCEGENRE-30-THA,BEYONCEGENRE-30,BEYONCEGENRE,no,10,0.0300,4060.00,6849.00,0.9700,2026-10-23 04:26:58.081,2026-10-23

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [7]:
df = Unifier.get_dataframe(name='kalshi_orderbook_levels',key='KXFEDDECISION-26OCT-H0', asof_date='2026-10-23', limit=10)
display(df)

,ticker,event_ticker,series_ticker,side,level,price,quantity,cum_quantity,implied_ask,asof_datetime,asof_date
0,KXFEDDECISION-26OCT-H0,KXFEDDECISION-26OCT,KXFEDDECISION,no,1,0.0600,764287.11,764287.11,0.9400,2026-10-23 04:26:58.081,2026-10-23
1,KXFEDDECISION-26OCT-H0,KXFEDDECISION-26OCT,KXFEDDECISION,no,2,0.0500,1053367.86,1817654.97,0.9500,2026-10-23 04:26:58.081,2026-10-23
2,KXFEDDECISION-26OCT-H0,KXFEDDECISION-26OCT,KXFEDDECISION,no,3,0.0400,352100.58,2169755.55,0.9600,2026-10-23 04:26:58.081,2026-10-23
3,KXFEDDECISION-26OCT-H0,KXFEDDECISION-26OCT,KXFEDDECISION,no,4,0.0300,503512.34,2673267.89,0.9700,2026-10-23 04:26:58.081,2026-10-23
4,KXFEDDECISION-26OCT-H0,KXFEDDECISION-26OCT,KXFEDDECISION,no,5,0.0200,1002572.63,3675840.52,0.9800,2026-10-23 04:26:58.081,2026-10-23
5,KXFEDDECISION-26OCT-H0,KXFEDDECISION-26OCT,KXFEDDECISION,no,6,0.0100,2010158.60,5685999.12,0.9900,2026-10-23 04:26:58.081,2026-10-23
6,KXFEDDECISION-26OCT-H0,KXFEDDECISION-26OCT,KXFEDDECISION,yes,1,0.9300,136465.25,136465.25,0.0700,2026-10-23 04:26:58.081,2026-10-23
7,KXFEDDECISION-26OCT-H0,KXFEDDECISION-26OCT,KXFEDDECISION,yes,2,0.9200,129784.67,266249.92,0.0800,2026-10-23 04:26:58.081,2026-10-23
8,KXFEDDECISION-26OCT-H0,KXFEDDECISION-26OCT,KXFEDDECISION,yes,3,0.9100,53775.67,320025.59,0.0900,2026-10-23 04:26:58.081,2026-10-23
9,KXFEDDECISION-26OCT-H0,KXFEDDECISION-26OCT,KXFEDDECISION,yes,4,0.9000,2274.29,322299.88,0.1000,2026-10-23 04:26:58.081,2026-10-23

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [8]:
df = Unifier.get_dataframe(name='kalshi_orderbook_levels',key='KXFEDDECISION-26OCT-H0', back_to='2026-10-22', up_to='2026-10-24', limit=10)
display(df)

Empty DataFrame
Columns: []
Index: []

## Download data file for a specific date using asof_date

In [9]:
Unifier.replicate(name="kalshi_orderbook_levels", target_location="./data", asof_date='2026-10-23')

Downloading using native python implementation for kalshi_orderbook_levels...
Found 1 files to download.
Native replication completed for kalshi_orderbook_levels. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_orderbook_levels", target_location="./data")