In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [2]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.17)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (3.0.0)
Requirement already satisfied: boto3 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (1.42.66)
Requirement already satisfied: botocore<1.43.0,>=1.42.66 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from boto3->unifier) (1.42.66)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from boto3->unifier) (1.0.1)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from boto3->unifier) (0.16.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from botocore<1.43.0,>=1.42.66->boto3->unifier) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from botocore<1.43.0,>=1.42.66->boto3->unifier) (2.5.0)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.43.0,>=1.42.66->boto3->unifier) (1.17.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.4.1)
Requirement already satisfied: tzdata in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='xtech_us_edi_eod_prices_adjusted_allcomposite_v2', back_to='2022-01-31', up_to='2024-02-01', limit=100)
display(df)

,secid,issuername,sectycd,isin,sedol,status,market,symbol,exdate,reason,...,uscode,primeex,closed,resisin,reslocal,sentiment,errors,currency,asof_datetime,asof_date
0,4552918,Exchange Listed Funds Trust,ETF,US46143U8493,None,A,ARCX,KLDW,2023-12-20 00:00:00.000,17,...,46143U849,USPAC,41.8786,None,None,0.986423,$0000,USD,2024-01-08 12:00:00.000,2024-01-08
1,549892,BlackRock Institutional Trust Company N.A.,ETF,US4642877967,None,A,ARCX,IYE,2023-12-20 00:00:00.000,17,...,464287796,USPAC,45.1900,None,None,0.995132,$0000,USD,2024-01-08 12:00:00.000,2024-01-08
2,549892,BlackRock Institutional Trust Company N.A.,ETF,US4642877967,None,R,ARCX,IYE,2023-12-20 00:00:00.000,17,...,464287796,USPAC,45.1900,None,None,0.995132,$0000,USD,2024-01-08 12:00:00.000,2024-01-08
3,4552918,Exchange Listed Funds Trust,ETF,US46143U8493,None,R,ARCX,KLDW,2023-12-20 00:00:00.000,17,...,46143U849,USPAC,41.8786,None,None,0.986423,$0000,USD,2024-01-08 12:00:00.000,2024-01-08
4,121909,Oncternal Therapeutics Inc,EQS,US68236P1075,None,A,XNYS,ONCT,2024-01-08 00:00:00.000,6,...,68236P107,USNASD,5.9600,None,None,1.000000,$0000,USD,2024-01-08 12:00:00.000,2024-01-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,4909940,Schwab Capital Trust,MF,US8085094006,None,A,XNAS,SWBGX,2023-12-28 00:00:00.000,17,...,808509400,USNASD,NaN,None,None,1.000000,$0001,NaN,2024-01-08 12:00:00.000,2024-01-08
96,4909943,Schwab Capital Trust,MF,US8085095664,None,A,XNAS,SWBRX,2023-12-28 00:00:00.000,17,...,808509566,USNASD,NaN,None,None,1.000000,$0001,NaN,2024-01-08 12:00:00.000,2024-01-08
97,4909967,Schwab Capital Trust,MF,US8085095581,None,A,XNAS,SWCRX,2023-12-28 00:00:00.000,17,...,808509558,USNASD,NaN,None,None,1.000000,$0001,NaN,2024-01-08 12:00:00.000,2024-01-08
98,4909970,Schwab Capital Trust,MF,US8085095417,None,A,XNAS,SWDRX,2023-12-28 00:00:00.000,17,...,808509541,USNASD,NaN,None,None,1.000000,$0001,NaN,2024-01-08 12:00:00.000,2024-01-08
99,4909982,Schwab Capital Trust,MF,US8085098148,None,A,XNAS,SWEGX,2023-12-28 00:00:00.000,17,...,808509814,USNASD,NaN,None,None,1.000000,$0001,NaN,2024-01-08 12:00:00.000,2024-01-08

## Retrieve data for a specific date with a specific ticker (key='SecID') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='xtech_us_edi_eod_prices_adjusted_allcomposite_v2',key='4909982', asof_date='2023-09-12', limit=100)
display(df)

,secid,issuername,sectycd,isin,sedol,status,market,symbol,exdate,reason,...,uscode,primeex,closed,resisin,reslocal,sentiment,errors,currency,asof_datetime,asof_date
0,4909982,Schwab Capital Trust,MF,US8085098148,None,A,XNAS,SWEGX,2021-12-30 00:00:00.000,17,...,808509814,USNASD,24.41,None,None,0.960672,$0000,USD,2022-01-21 12:00:00.000,2022-01-21
1,4909982,Schwab Capital Trust,MF,US8085098148,None,A,XNAS,SWEGX,2021-12-30 00:00:00.000,17,...,808509814,USNASD,NaN,None,None,1.000000,$0001,NaN,2022-01-21 12:00:00.000,2022-01-21
2,4909982,Schwab Capital Trust,MF,US8085098148,None,A,XNAS,SWEGX,2021-12-30 00:00:00.000,17,...,808509814,USNASD,24.41,None,None,0.960672,$0000,USD,2022-01-24 12:00:00.000,2022-01-24
3,4909982,Schwab Capital Trust,MF,US8085098148,None,A,XNAS,SWEGX,2022-12-29 00:00:00.000,17,...,808509814,USNASD,17.94,None,None,1.000000,$0000,USD,2022-12-30 12:00:00.000,2022-12-30
4,4909982,Schwab Capital Trust,MF,US8085098148,None,A,XNAS,SWEGX,2022-12-29 00:00:00.000,17,...,808509814,USNASD,NaN,None,None,1.000000,$0001,NaN,2022-12-30 12:00:00.000,2022-12-30

## Retrieve data for a specific date range with a specific SecID (key='SecID') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='xtech_us_edi_eod_prices_adjusted_allcomposite_v2',key='4909982', back_to='2022-01-01', up_to='2024-06-01', limit=100)
display(df)

,secid,issuername,sectycd,isin,sedol,status,market,symbol,exdate,reason,...,uscode,primeex,closed,resisin,reslocal,sentiment,errors,currency,asof_datetime,asof_date
0,4909982,Schwab Capital Trust,MF,US8085098148,None,A,XNAS,SWEGX,2023-12-28 00:00:00.000,17,...,808509814,USNASD,NaN,None,None,1.000000,$0001,NaN,2024-01-08 12:00:00.000,2024-01-08
1,4909982,Schwab Capital Trust,MF,US8085098148,None,A,XNAS,SWEGX,2023-12-28 00:00:00.000,17,...,808509814,USNASD,17.94,None,None,1.000000,$0001,USD,2024-01-08 12:00:00.000,2024-01-08
2,4909982,Schwab Capital Trust,MF,US8085098148,None,A,XNAS,SWEGX,2021-12-30 00:00:00.000,17,...,808509814,USNASD,24.41,None,None,0.960672,$0000,USD,2022-01-21 12:00:00.000,2022-01-21
3,4909982,Schwab Capital Trust,MF,US8085098148,None,A,XNAS,SWEGX,2021-12-30 00:00:00.000,17,...,808509814,USNASD,NaN,None,None,1.000000,$0001,NaN,2022-01-21 12:00:00.000,2022-01-21
4,4909982,Schwab Capital Trust,MF,US8085098148,None,A,XNAS,SWEGX,2021-12-30 00:00:00.000,17,...,808509814,USNASD,24.41,None,None,0.960672,$0000,USD,2022-01-24 12:00:00.000,2022-01-24
5,4909982,Schwab Capital Trust,MF,US8085098148,None,A,XNAS,SWEGX,2022-12-29 00:00:00.000,17,...,808509814,USNASD,17.94,None,None,1.000000,$0000,USD,2022-12-30 12:00:00.000,2022-12-30
6,4909982,Schwab Capital Trust,MF,US8085098148,None,A,XNAS,SWEGX,2022-12-29 00:00:00.000,17,...,808509814,USNASD,NaN,None,None,1.000000,$0001,NaN,2022-12-30 12:00:00.000,2022-12-30

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="xtech_us_edi_eod_prices_adjusted_allcomposite_v2", target_location="./data", asof_date='2026-01-13')

Starting native python replication for xtech_us_edi_eod_prices_adjusted_allcomposite_v2 (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_edi_eod_prices_adjusted_allcomposite_v2. Downloaded 1 files.