In [2]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [3]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [5]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_1min_extra_v2", back_to='2025-11-18', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2026-07-09 14:57:00.000,2026-07-09 14:57:03.000,AA,48.2800,48.330,48.2700,48.3300,3509,55,48.292156,48.272216,48.303334,48.30,48.33,48.315,2026-07-09,2026-07-09
1,2026-07-09 15:20:00.000,2026-07-09 15:20:03.000,AA,48.6494,48.710,48.6093,48.6650,3472,70,48.673707,48.663919,48.698641,48.63,48.70,48.665,2026-07-09,2026-07-09
2,2026-07-09 15:19:00.000,2026-07-09 15:19:03.000,AA,48.5964,48.714,48.5200,48.6700,9066,140,48.598664,48.548095,48.603098,48.66,48.72,48.690,2026-07-09,2026-07-09
3,2026-07-09 14:42:00.000,2026-07-09 14:42:03.000,AA,48.2800,48.360,48.2600,48.3400,7382,102,48.311711,48.277098,48.308100,48.32,48.36,48.340,2026-07-09,2026-07-09
4,2026-07-09 14:31:00.000,2026-07-09 14:31:03.000,AA,48.4900,48.490,48.1969,48.3950,17029,188,48.410656,48.410366,48.406275,48.36,48.43,48.395,2026-07-09,2026-07-09
5,2026-07-09 15:26:00.000,2026-07-09 15:26:03.000,AA,48.8750,48.960,48.7449,48.9300,9039,111,48.908969,48.900956,48.905981,48.91,48.95,48.930,2026-07-09,2026-07-09
6,2026-07-09 15:02:00.000,2026-07-09 15:02:03.000,AA,48.7800,48.780,48.4518,48.4588,4129,69,48.737464,48.731456,48.757165,48.72,48.76,48.740,2026-07-09,2026-07-09
7,2026-07-09 18:40:00.000,2026-07-09 18:40:03.000,AA,49.0050,49.060,48.9197,49.0450,4875,84,49.035488,49.034728,49.035512,49.04,49.07,49.055,2026-07-09,2026-07-09
8,2026-07-09 15:07:00.000,2026-07-09 15:07:03.000,AA,48.8500,48.950,48.6685,48.8538,4822,95,48.894474,48.855151,48.901024,48.93,48.95,48.940,2026-07-09,2026-07-09
9,2026-07-09 14:35:00.000,2026-07-09 14:35:03.000,AA,48.3200,48.360,48.3100,48.3300,5497,88,48.339505,48.315797,48.343465,48.31,48.35,48.330,2026-07-09,2026-07-09

In [6]:
df = Unifier.get_dataframe(name='xtech_us_eqt_sip_bardata_flow_1min_extra_v2', back_to='2021-01-11', up_to='2021-02-01', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2021-01-29 20:33:00.000,2021-01-29 20:33:03.000,AAIC,3.6600,3.6600,3.6600,3.6600,3.0,1.0,3.660000,NaN,3.6600,3.65,3.67,3.660,2021-01-29,2021-01-29
1,2021-01-29 21:04:00.000,2021-01-29 21:04:03.000,AAIC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.51,3.69,3.600,2021-01-29,2021-01-29
2,2021-01-29 20:23:00.000,2021-01-29 20:23:03.000,AAIC,3.6300,3.6300,3.6300,3.6300,300.0,3.0,3.630000,NaN,NaN,3.62,3.64,3.630,2021-01-29,2021-01-29
3,2021-01-29 20:13:00.000,2021-01-29 20:13:03.000,AAIC,3.6468,3.6468,3.6468,3.6468,5.0,1.0,3.646800,NaN,3.6468,3.63,3.65,3.640,2021-01-29,2021-01-29
4,2021-01-29 19:45:00.000,2021-01-29 19:45:03.000,AAIC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.61,3.62,3.615,2021-01-29,2021-01-29
5,2021-01-29 15:42:00.000,2021-01-29 15:42:03.000,AAIC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.67,3.69,3.680,2021-01-29,2021-01-29
6,2021-01-29 17:01:00.000,2021-01-29 17:01:03.000,AAIC,3.6600,3.6600,3.6600,3.6600,405.0,13.0,3.660000,3.66,3.6600,3.64,3.67,3.655,2021-01-29,2021-01-29
7,2021-01-29 16:57:00.000,2021-01-29 16:57:03.000,AAIC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.64,3.66,3.650,2021-01-29,2021-01-29
8,2021-01-29 14:45:00.000,2021-01-29 14:45:03.000,AAIC,3.6300,3.6300,3.6300,3.6300,2.0,2.0,3.630000,3.63,NaN,3.63,3.66,3.645,2021-01-29,2021-01-29
9,2021-01-29 15:14:00.000,2021-01-29 15:14:03.000,AAIC,3.6868,3.6868,3.6700,3.6700,202.0,2.0,3.670166,3.67,3.6868,3.67,3.69,3.680,2021-01-29,2021-01-29

In [7]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_1min_extra_v2", key='AA', back_to='2025-10-29', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2026-07-09 14:57:00.000,2026-07-09 14:57:03.000,AA,48.2800,48.330,48.2700,48.3300,3509,55,48.292156,48.272216,48.303334,48.30,48.33,48.315,2026-07-09,2026-07-09
1,2026-07-09 15:20:00.000,2026-07-09 15:20:03.000,AA,48.6494,48.710,48.6093,48.6650,3472,70,48.673707,48.663919,48.698641,48.63,48.70,48.665,2026-07-09,2026-07-09
2,2026-07-09 15:19:00.000,2026-07-09 15:19:03.000,AA,48.5964,48.714,48.5200,48.6700,9066,140,48.598664,48.548095,48.603098,48.66,48.72,48.690,2026-07-09,2026-07-09
3,2026-07-09 14:42:00.000,2026-07-09 14:42:03.000,AA,48.2800,48.360,48.2600,48.3400,7382,102,48.311711,48.277098,48.308100,48.32,48.36,48.340,2026-07-09,2026-07-09
4,2026-07-09 14:31:00.000,2026-07-09 14:31:03.000,AA,48.4900,48.490,48.1969,48.3950,17029,188,48.410656,48.410366,48.406275,48.36,48.43,48.395,2026-07-09,2026-07-09
5,2026-07-09 15:26:00.000,2026-07-09 15:26:03.000,AA,48.8750,48.960,48.7449,48.9300,9039,111,48.908969,48.900956,48.905981,48.91,48.95,48.930,2026-07-09,2026-07-09
6,2026-07-09 15:02:00.000,2026-07-09 15:02:03.000,AA,48.7800,48.780,48.4518,48.4588,4129,69,48.737464,48.731456,48.757165,48.72,48.76,48.740,2026-07-09,2026-07-09
7,2026-07-09 18:40:00.000,2026-07-09 18:40:03.000,AA,49.0050,49.060,48.9197,49.0450,4875,84,49.035488,49.034728,49.035512,49.04,49.07,49.055,2026-07-09,2026-07-09
8,2026-07-09 15:07:00.000,2026-07-09 15:07:03.000,AA,48.8500,48.950,48.6685,48.8538,4822,95,48.894474,48.855151,48.901024,48.93,48.95,48.940,2026-07-09,2026-07-09
9,2026-07-09 14:35:00.000,2026-07-09 14:35:03.000,AA,48.3200,48.360,48.3100,48.3300,5497,88,48.339505,48.315797,48.343465,48.31,48.35,48.330,2026-07-09,2026-07-09

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="xtech_us_eqt_sip_bardata_flow_1min_extra_v2", target_location="./data", asof_date='2025-02-12')

Downloading using native python implementation for xtech_us_eqt_sip_bardata_flow_1min_extra_v2...
Found 1 files to download.
Native replication completed for xtech_us_eqt_sip_bardata_flow_1min_extra_v2. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_eqt_sip_bardata_flow_1min_extra_v2", target_location="./data")