In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="lseg_us_equity_options_flow_1min_v2_3", asof_date='2024-01-31', limit=10)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2016-10-11,2016-10-11 23:30:30.000,2016-10-11 20:06:00.000,SPXW,SPXW,RegularMkt,EQT,Put,14,10,...,0,0,0,1,1,9.00,0.000,0,0.917,2016-10-11
1,2016-10-11,2016-10-11 23:30:30.000,2016-10-11 20:06:00.000,SPXW,SPXW,RegularMkt,EQT,Call,14,10,...,0,0,0,1,5,4.24,0.000,0,3.910,2016-10-11
2,2016-10-11,2016-10-11 23:30:30.000,2016-10-11 20:06:00.000,SPXW,SPXW,RegularMkt,EQT,Put,19,10,...,0,8,0,0,0,0.00,18.882,0,0.000,2016-10-11
3,2016-10-11,2016-10-11 23:30:30.000,2016-10-11 20:06:00.000,SPXW,SPXW,RegularMkt,EQT,Put,14,10,...,0,1,0,0,0,0.00,3.710,0,0.000,2016-10-11
4,2016-10-11,2016-10-11 23:30:30.000,2016-10-11 20:06:00.000,SPXW,SPXW,RegularMkt,EQT,Call,9,11,...,0,0,0,1,2,1.73,0.000,0,1.640,2016-10-11
5,2016-10-11,2016-10-11 23:30:30.000,2016-10-11 20:06:00.000,SPXW,SPXW,RegularMkt,EQT,Put,19,10,...,0,8,0,0,0,0.00,15.609,0,0.000,2016-10-11
6,2016-10-11,2016-10-11 23:30:30.000,2016-10-11 20:06:00.000,SPXW,SPXW,RegularMkt,EQT,Call,14,10,...,0,0,0,1,5,2.82,0.000,0,3.345,2016-10-11
7,2016-10-11,2016-10-11 23:30:30.000,2016-10-11 20:06:00.000,SPXW,SPXW,RegularMkt,EQT,Put,4,11,...,0,1,0,0,0,0.00,9.970,0,0.000,2016-10-11
8,2016-10-11,2016-10-11 23:30:30.000,2016-10-11 20:06:00.000,SPXW,SPXW,RegularMkt,EQT,Call,31,10,...,0,0,0,1,2,2.87,0.000,0,2.138,2016-10-11
9,2016-10-11,2016-10-11 23:30:30.000,2016-10-11 20:06:00.000,SPXW,SPXW,RegularMkt,EQT,Call,14,10,...,0,0,0,1,9,1.70,0.000,0,4.734,2016-10-11

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='lseg_us_equity_options_flow_1min_v2_3', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 16:48:00.000,SPXW,SPXW,RegularMkt,EQT,Put,31,1,...,0,4,0,0,0,0.000000,0.124524,0,0.000000,2024-01-31
1,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 16:48:00.000,SPXW,SPXW,RegularMkt,EQT,Put,31,1,...,0,2,0,1,1,0.050000,0.057973,0,0.025296,2024-01-31
2,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 16:48:00.000,SPXW,SPXW,RegularMkt,EQT,Put,31,1,...,0,1,0,2,10,0.080000,0.089210,0,0.381338,2024-01-31
3,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 16:48:00.000,SPXW,SPXW,RegularMkt,EQT,Put,31,1,...,0,0,0,3,13,0.084615,0.000000,0,0.535514,2024-01-31
4,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 16:48:00.000,SPXW,SPXW,RegularMkt,EQT,Put,31,1,...,0,1,0,0,0,0.000000,0.318639,0,0.000000,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 16:48:00.000,SPXW,SPXW,RegularMkt,EQT,Call,2,2,...,0,10,0,0,0,0.000000,134.487000,0,0.000000,2024-01-31
96,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 16:48:00.000,SPXW,SPXW,RegularMkt,EQT,Call,2,2,...,0,1,0,0,0,0.000000,1.725500,0,0.000000,2024-01-31
97,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 16:48:00.000,SPXW,SPXW,RegularMkt,EQT,Call,2,2,...,0,2,0,4,12,12.600000,81.387100,0,18.800580,2024-01-31
98,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 16:48:00.000,SPXW,SPXW,RegularMkt,EQT,Call,2,2,...,0,1,0,0,0,0.000000,1.287780,0,0.000000,2024-01-31
99,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 16:48:00.000,SPXW,SPXW,RegularMkt,EQT,Call,2,2,...,0,2,0,0,0,0.000000,11.987200,0,0.000000,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [8]:
df = Unifier.get_dataframe(name='lseg_us_equity_options_flow_1min_v2_3', key='SPXW', asof_date='2024-01-01', limit=10)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2016-10-11,2016-10-11 23:30:30.000,2016-10-11 20:06:00.000,SPXW,SPXW,RegularMkt,EQT,Put,14,10,...,0,0,0,1,1,9.00,0.000,0,0.917,2016-10-11
1,2016-10-11,2016-10-11 23:30:30.000,2016-10-11 20:06:00.000,SPXW,SPXW,RegularMkt,EQT,Call,14,10,...,0,0,0,1,5,4.24,0.000,0,3.910,2016-10-11
2,2016-10-11,2016-10-11 23:30:30.000,2016-10-11 20:06:00.000,SPXW,SPXW,RegularMkt,EQT,Put,19,10,...,0,8,0,0,0,0.00,18.882,0,0.000,2016-10-11
3,2016-10-11,2016-10-11 23:30:30.000,2016-10-11 20:06:00.000,SPXW,SPXW,RegularMkt,EQT,Put,14,10,...,0,1,0,0,0,0.00,3.710,0,0.000,2016-10-11
4,2016-10-11,2016-10-11 23:30:30.000,2016-10-11 20:06:00.000,SPXW,SPXW,RegularMkt,EQT,Call,9,11,...,0,0,0,1,2,1.73,0.000,0,1.640,2016-10-11
5,2016-10-11,2016-10-11 23:30:30.000,2016-10-11 20:06:00.000,SPXW,SPXW,RegularMkt,EQT,Put,19,10,...,0,8,0,0,0,0.00,15.609,0,0.000,2016-10-11
6,2016-10-11,2016-10-11 23:30:30.000,2016-10-11 20:06:00.000,SPXW,SPXW,RegularMkt,EQT,Call,14,10,...,0,0,0,1,5,2.82,0.000,0,3.345,2016-10-11
7,2016-10-11,2016-10-11 23:30:30.000,2016-10-11 20:06:00.000,SPXW,SPXW,RegularMkt,EQT,Put,4,11,...,0,1,0,0,0,0.00,9.970,0,0.000,2016-10-11
8,2016-10-11,2016-10-11 23:30:30.000,2016-10-11 20:06:00.000,SPXW,SPXW,RegularMkt,EQT,Call,31,10,...,0,0,0,1,2,2.87,0.000,0,2.138,2016-10-11
9,2016-10-11,2016-10-11 23:30:30.000,2016-10-11 20:06:00.000,SPXW,SPXW,RegularMkt,EQT,Call,14,10,...,0,0,0,1,9,1.70,0.000,0,4.734,2016-10-11

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='lseg_us_equity_options_flow_1min_v2_3',key='SPX', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-09,2024-01-09 23:30:30.000,2024-01-09 17:41:00.000,SPX,SPX,RegularMkt,EQT,Put,19,1,...,0,1,0,0,0,0.0,3.96110,0,0.0000,2024-01-09
1,2024-01-09,2024-01-09 23:30:30.000,2024-01-09 17:41:00.000,SPX,SPX,RegularMkt,EQT,Put,19,1,...,0,10,0,0,0,0.0,19.88368,0,0.0000,2024-01-09
2,2024-01-09,2024-01-09 23:30:30.000,2024-01-09 17:41:00.000,SPX,SPX,RegularMkt,EQT,Call,19,1,...,0,1,0,0,0,0.0,3.06517,0,0.0000,2024-01-09
3,2024-01-09,2024-01-09 23:30:30.000,2024-01-09 17:41:00.000,SPX,SPX,RegularMkt,EQT,Put,16,2,...,0,1,0,0,0,0.0,3.85618,0,0.0000,2024-01-09
4,2024-01-09,2024-01-09 23:30:30.000,2024-01-09 17:41:00.000,SPX,SPX,RegularMkt,EQT,Put,16,2,...,0,1,0,0,0,0.0,4.58839,0,0.0000,2024-01-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-09,2024-01-09 23:30:30.000,2024-01-09 17:45:00.000,SPX,SPX,RegularMkt,EQT,Put,18,10,...,0,0,0,1,1,28.8,0.00000,0,4.9145,2024-01-09
96,2024-01-09,2024-01-09 23:30:30.000,2024-01-09 17:45:00.000,SPX,SPX,RegularMkt,EQT,Put,18,10,...,0,1,0,0,0,0.0,6.25044,0,0.0000,2024-01-09
97,2024-01-09,2024-01-09 23:30:30.000,2024-01-09 17:45:00.000,SPX,SPX,RegularMkt,EQT,Put,18,10,...,0,1,0,0,0,0.0,6.63359,0,0.0000,2024-01-09
98,2024-01-09,2024-01-09 23:30:30.000,2024-01-09 17:45:00.000,SPX,SPX,RegularMkt,EQT,Call,20,12,...,0,0,0,1,1,289.8,0.00000,0,18.1417,2024-01-09
99,2024-01-09,2024-01-09 23:30:30.000,2024-01-09 17:45:00.000,SPX,SPX,RegularMkt,EQT,Call,20,12,...,0,0,0,1,1,207.4,0.00000,0,18.1815,2024-01-09

## Download data file for a specific date using asof_date

In [ ]:
Unifier.replicate(name="lseg_us_equity_options_flow_1min_v2_3", target_location="./data", asof_date='2014-01-31')

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_equity_options_flow_1min_v2_3", target_location="./data")